### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by Haggle1996** [Funwayguy/BetterQuesting#1]
Okay, how the hell do you get started with this mod? It's installed, along with standard questing pack. I can see a couple of loot chests in NEI, a block, and a few options on the config file. Not certain where to start or how a player interacts with it.

Edit: Okay, found the keybinds: GRAVE, MINUS, and EQUALS and can get to the editors. Now trying to figure out how the player is supposed to know there's quests. Doesn't seem to be a book or an item the player is given to hint to them there's something to do.

**Comment by Funwayguy** [comment]
I'll write up a tutorial book in game

**Comment by Funwayguy** [comment]
Closing issue now that the guide book exists.
