### ISSUE TITLE
Client crash when doing a search within the Item section of the GUI

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#10]
I just updated to Better Questing 1.0.15 and Standard Expansion 1.0.10 to test out the Ore Dictionary functionality.  When I edited the item I had setup with my quest and tried to search for "wood" it crashed and I got this error:

http://pastebin.com/Q9mnyP16

Here is a copy of my current QuestDatabase.json

http://pastebin.com/bziQkF7h

**Comment by Funwayguy** [comment]
This is actually part of a bug with xreliquary and their Void Tear item tool tips. I could add handling to contain this and future crashes but ultimately this has to be fixed by the developer of the items.

**Comment by Funwayguy** [comment]
I've fixed the crash while searching but this still won't prevent the crash when hovering over the item, that's still up to the item's developer to fix.
