### ISSUE TITLE
Question on Licensing

### ISSUE THREAD

**Issue by Ristellise** [Funwayguy/BetterQuesting#101]
are we allowed to make special builds for debugging purposes?

**Comment by Funwayguy** [comment]
What debugging could you possibly need? Plus, BQ2 is still in development so not all the code is final anyway

**Comment by Ristellise** [comment]
i know that... basically extremely verbose logging as some issues like concurrent Exception happens to modpacks quite frequently... so basic can i make a build for testing purposes?

**Comment by Funwayguy** [comment]
Most of the CME crash issues I fix in BetterQuesting doesn't involve verbose logging. I just read the crash logs, deobfuscate the method calls by hand and figure out what list was modified and where.

I will say yes you can make a private build purely for testing but you may not distribute it and it can only be of the BQ2 development branches (debugging the deprecated BQ1 code is pointless at this point)

**Comment by Ristellise** [comment]
thanks. May i ask you one last thing... since i am also helping in The Ferret Business modpack i would like to redistribute to our own contributors and the caigan the modpack make himself. is it possible? we will not redistribute to the public as it can have issues.

**Comment by Funwayguy** [comment]
You may have up to 4 people (you, caigan and 2 others) use the debugging builds and you'll need to list out their names so I know who should and should not have them. I am however waiting on caigan to confirm this first

**Comment by Ristellise** [comment]
@CaiganMythFang @thebluetroll and me

**Comment by CaiganMythFang** [comment]
Confirming that josh and thebluetroll assist me with code and debugging issues with The Ferret Business.

**Comment by Funwayguy** [comment]
Cleaning up some issue threads at the moment. If you need to ask anything else about the debugging builds you can just ping me on Curse.
