### ISSUE TITLE
[1.7.10][Server] Hardcore, player doesn't get kicked and banned

### ISSUE THREAD

**Issue by Sir-Will** [Funwayguy/BetterQuesting#102]
hey,
so I did run out of lives and got this:
http://i.imgur.com/YHjBhg7.jpg

I clicked "Leave Server" which respawned me but it didn't kick and ban me like it should.

Did I miss anything or why does it not kick/ban?

**Comment by Funwayguy** [comment]
Odd... Is this using the new BQ2 beta builds?

**Comment by Sir-Will** [comment]
Sry, forgot to mention the version. Version is 1.0.173

**Comment by Sir-Will** [comment]
It seems to work on a fresh world. Do I need to change something that it works with a old world which didn't have BetterQuesting at start?

**Comment by Funwayguy** [comment]
Closing issue as I don't do updates for 1.x.x builds anymore
