### ISSUE TITLE
Can't add lives for offline users

### ISSUE THREAD

**Issue by Hoffs** [Funwayguy/BetterQuesting#104]
So it's pretty simple. If a user is not currently in the server you can't add lives to him. 

This is on 1.7.10 version of the mod. Searched for open/closed issue on github, but didn't see anything.

**Comment by Funwayguy** [comment]
Just added this functionality to builds 2.0.202 and 2.3.203. The other commands should work with offline players now too. Keep in mind that the players have to have been on the server at least once for their names and IDs to be listed in BetterQuesting's databases
