### ISSUE TITLE
Percent characters in description cause "Format error" to show

### ISSUE THREAD

**Issue by WesCook** [Funwayguy/BetterQuesting#105]
I'm not sure why, but percent characters (%) create a "Format error" message at the front of the quest description.  I ended up tearing out all my formatting code trying to figure out which was causing it.

**Comment by WesCook** [comment]
As a workaround for now, the full-width percent character (％) doesn't have this problem.

That's U+FF05, or &#65285 in HTML.

**Comment by Funwayguy** [comment]
I think this has to do with how the localisation files use % as an escape character and since quest names and descriptions have translation support, it doesn't particularly like the use of them. I'll look for a potential solution but it may be tricky without breaking translations
