### ISSUE TITLE
1.7.10 Title Card config missing

### ISSUE THREAD

**Issue by Cazadorsniper** [Funwayguy/BetterQuesting#106]
The Title Card config seems to be missing in Better Questing-2.0.177 so I'm un able to change the default minecraft title card with PO2's.

**Comment by Funwayguy** [comment]
It's not missing, I just moved it inside the QuestDatabase file so it's bundled with the rest of the relevant quests. I just haven't made a GUI for it yet

**Comment by Funwayguy** [comment]
Now has an editor, closing issue.
