### ISSUE TITLE
crash on moving quest(1.10.2)

### ISSUE THREAD

**Issue by SDUBZ** [Funwayguy/BetterQuesting#107]
i was moving quest around in the designer page and all of a sudden it crashed me back to desktop

forge:1.10.2-2185
bqm version: BetterQuesting-1.3.180
crash report:
[crash-2016-12-25_09.56.34-server.txt](https://github.com/Funwayguy/BetterQuesting/files/671990/crash-2016-12-25_09.56.34-server.txt)

**Comment by Funwayguy** [comment]
1.x.x builds are not supported any more. Please update to the current 2.x.x versions and try again
