### ISSUE TITLE
Crashing when removing quests

### ISSUE THREAD

**Issue by Lgk2** [Funwayguy/BetterQuesting#109]
Hey I'm still experiencing crashing when trying to remove certain quests in the add/remove quest gui.

I'm using
BetterQuesting-2.3.186.jar
StandardExpansion-2.3.116.jar

**Comment by Funwayguy** [comment]
I've identified the issue and fixed it for the next build but I'm going to spruce up some UIs before I post it so I'm not updating for a one line edit.

PS: 320+ quests sounds like quite the amount of work.

**Comment by Lgk2** [comment]
Well I have quite a lot of work left since I'm not done with descriptions and quest rewards. Thinking of clever quest rewards that are relevant for the player is really tough. 

Nice I guess i don't have to worry about that issue anymore!
