### ISSUE TITLE
Bug: User client crash when trying to select a Fluid as a quest icon

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#11]
Our quest writer tried to assign a fluid to the Quest Icon via the Advanced tab and was had her client crash with this error log:
http://pastebin.com/29FRPcxf

When I tried the same quest and editing the icon I was able to select Fluid, I picked one from the list, and clicked done.  While it didn't take the icon, I did not get crashed out.

Upon loading back in our quest writer tried go from Object to Fluid in the Advanced menu and crashed a second time with this error:
http://pastebin.com/29FRPcxf

I then tried to edit the icon from the placeholder to and Item.  When I got in to select an item I tried to search for Nether to set it back to the nether star and it crashed with this error:
http://pastebin.com/WVUkXqyv

Edit:
This all happened on a dedicated server.  Will try testing locally to see if it happens there as well.

**Comment by Funwayguy** [comment]
Seems I missed some handling for non-fluid data. I should have a fix out in the next day or so.

**Comment by Funwayguy** [comment]
Got a bit side tracked with other mods but this has been fixed and pushed out to release.
