### ISSUE TITLE
Crash on moving quests 2-3.191

### ISSUE THREAD

**Issue by Lgk2** [Funwayguy/BetterQuesting#110]
Crash when moving/resizing quests in the designer. 

**I'm using:
BetterQuesting-2.3.191.jar
StandardExpansion-2.3.116.jar**

**Comment by Funwayguy** [comment]
Same location, same day, different bug. That's quite the achievement. Guess I need to make this editor a little more robust though it's hard to test without hundreds of quests.

**Comment by Lgk2** [comment]
Well it's becoming more robust since you're patching the issues that we report!

**Comment by Funwayguy** [comment]
So how did that last build work out? Still managing to break all the things?

**Comment by Lgk2** [comment]
BetterQuesting-2.3.195.jar seems stable. I haven't been able to crash it so far, but I'll inform you if i do!
