### ISSUE TITLE
Quests can be clicked when not shown

### ISSUE THREAD

**Issue by cj89898** [Funwayguy/BetterQuesting#111]
When you open the quest book, you can click on any quest as if it was there and it will open up even if it is not shown.

Example: https://i.gyazo.com/1e27e7615391185f961d326f0bd40b5b.gif

**Comment by Funwayguy** [comment]
I was just about to post a new build too >_>

EDIT: And I fixed it already \o/

**Comment by cj89898** [comment]
man you're good! a shame it's in a pack :L and idk if it will update xD
