### ISSUE TITLE
Parties work Now, However...

### ISSUE THREAD

**Issue by Subprimal** [Funwayguy/BetterQuesting#114]
Thanks so much on fixing the party system Funway, works flawlessly with the update, however, you can no longer click on quests within the menu, I have done testing with the versions and fresh installs of PO2, on brand new worlds,

Symptoms, Clicking quests do nothing but move the menu around, can not claim quests but It does still detect quests. 
BQ Edit mode DOES open up quests.
Versions that did not work
BQ 2.0.192 and 2.0.194

BQ 2.0.190 works with any version of Standard expansion. Currently 2.0.117

**Comment by Funwayguy** [comment]
*flails around panicking*
*mashes keyboard*

Fixed. New update has been sent out
