### ISSUE TITLE
Reproducible crash in edit mode with parentheses

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#118]
Minecraft 1.7.10, BQ 2.0.197

To reproduce:
1) Create a new quest 
2) edit the quest, and hit the "Aa" button for the description.
2) Delete the existing description, and paste in the following:
"(abcdefghijklmnop abcdefghijklmnop abcdefghijklmnop abcdefghijklmnop abcdefghijklmnop.)"
(No quotes, though I'm not sure it matters.)
3) Click on the text you just pasted in. Note that the UI just froze.
4) Click again to crash Minecraft.

Here's the crash report:
[crash.txt](https://github.com/Funwayguy/BetterQuesting/files/681681/crash.txt)

I have the (custom private) modpack here if you can't repro it, but this doesn't feel like a mod interaction issue.
Note 1) What seems to matter is the length of the string inside the (); a shorter string works fine.
Note 2) This is just an issue in the full page edit mode and when clicking.

**Comment by Funwayguy** [comment]
Got this fixed up. Should be in an update as soon as I finish fixing up a handful of other bugs
