### ISSUE TITLE
Unable to edit first item in long task list

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#119]
Minecraft 1.7.10, BQ 2.0.197

Repro:
1) Create a new quest.
2) Edit the tasks: add a bq_standard:retrieval
3) Open the retrieval task you created, and open the requiredItems
4) Add a lot of elements to the list. (Reproduced with Text and Item) There should be a scrollbar, and if you scroll to the bottom, the first element (#0) should be completely hidden. (If in doubt, add a couple extra elements.)
5) Try to edit element #0. Clicking on it has no effect. The edit, "...", "+", and "x" buttons are all useless.
6) Resize the window so the list fits on a single screen without a scrollbar. Note that now you can edit element #0.
7) Resize the window so fewer elements fit on the screen. Note that the broken elements are those that are not visible at all if the list is scrolled to the bottom. (Even a single pixel will allow access to the full button.)

**Comment by Funwayguy** [comment]
Confirmed this to be a thing. Seem to only affect the JSON editors though so it's not inherently a problem with scrolling lists.

**Comment by Funwayguy** [comment]
Found the bug and it's fixed up for next release \o/
