### ISSUE TITLE
ScrollBar on ThemeSelector doesn't seem to work

### ISSUE THREAD

**Issue by TheCodedOne** [Funwayguy/BetterQuesting#12]
I've added 6 themes to the theme menu but the scroll bar on it doesn't seem to scroll down the list.. it doesn't move at all, i don't know if its just for viewing or its actually supposed to be functional.

**Comment by Funwayguy** [comment]
Are you sure you've registered them properly and they are actually on the list?

**Comment by TheCodedOne** [comment]
They should be registered properly since i see some of them but the rest aren't there and cant scroll..

**Comment by TheCodedOne** [comment]
Fixed by getting new deobf jar
