### ISSUE TITLE
guh

### ISSUE THREAD

**Issue by trismegistis** [Funwayguy/BetterQuesting#120]
cant work in 1.11.2.... barely no change in change but I think artificial blockage....

**Comment by Funwayguy** [comment]
What? Is... is this a report?

**Comment by trismegistis** [comment]
needs to work but artificial constrained to only work on version assigned unlock it pls ty

**Comment by Funwayguy** [comment]
Look I'm sorry but it is extremely difficult to understand what exactly you're asking for. My only guess is that you're looking for a 1.11.2 update. Is that right?

**Comment by trismegistis** [comment]
seems you make program disable itself if not match version but doesnt have to

**Comment by Funwayguy** [comment]
No I don't. If you're getting version warnings from Forge then you are using the wrong version and they are not compatible. That's your fault not mine. 

I also do not have a 1.11.2 compatible version yet. The mod doesn't magically make itself work in new versions.
