### ISSUE TITLE
Party Quest Not Sharing

### ISSUE THREAD

**Issue by Subprimal** [Funwayguy/BetterQuesting#121]
While in a LAN game the Quest Party system doesn't share properly. With sharing on in the Party System, I could redeem and claim a prize but my partner could not claim it; even though it says that it is claimable. It will pop up blue, but once clicked it will say that it is not completed. They can't submit or try to complete it at all, after I claim the quest. 

Using version 2.0.197 in 1.7.10 MC

Hope this is helpful enough for future updates. Thanks!

**Comment by Funwayguy** [comment]
This is probably a little confusing but the 'share' option literally means you're sharing the single reward. The quest however should be marked as claimed for both of you if only one person claims it

**Comment by Subprimal** [comment]
OH okay, so now if share is OFF one player can complete a quest and the other can just claim it? or does that other person still need to be required to do the quest. thanks for clearing that up.

**Comment by Funwayguy** [comment]
Yes. When Loot Share is off your completion status is still shared but you can still claim your individual rewards

**Comment by Subprimal** [comment]
Welp rip, Now i feel like the most utmost noob. sorry Funway! haha
thanks
