### ISSUE TITLE
Unable to change the quantity of fluids

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#122]
Minecraft 1.7.10, BQ 2.0.197

I cannot change the quantity of most fluids I request in quests. Repro:
1) Create a new quest, and add a bq_standard:fluid task under it.
2) Add a new fluid type entry to the requiredFluids list.
3) Edit the new entry to be 12345mB of lava.
4) Hit done a bunch of times to return to the main quest page. Note that it's asking for 1000mB of lava.

Workaround: manually editing the json to change the quantity appears to work.

Note: There appears to be some sequence of actions that allows editing, because I managed to end up with 1 quest with the proper amount, but I can't figure out what I did differently.

**Comment by Funwayguy** [comment]
The problem actually lies with the value applying after you click away from the text box however clicking done will close the GUI before the value is applied. I've fixed this for next release in both 1.7.10 and 1.10.2
