### ISSUE TITLE
[1.10.2] Error while checking version

### ISSUE THREAD

**Issue by xSparky911x** [Funwayguy/BetterQuesting#125]
Forge - 2215
BQ - 2.3.203
BQ Standard Expansion - 2.3.120
BQ RF Expansion - 2.3.24

As the title states I get an error checking Better Questing version. I get it for all the expansions installed (even though update notifications are turned off in the config.

Attached is a screen shot 

![bq-error](https://cloud.githubusercontent.com/assets/6767483/21970509/9d7f6782-db6c-11e6-80ee-a04120fc4e09.png)

and here is the error from the launcher log...
http://pastebin.com/DdrXNBJ6

**Comment by Funwayguy** [comment]
I am aware of this and in a bit of a crisis about it. This is because the build service I use to update all my mods is migrating stuff and all of my mods' update checkers are unable to access the old files. I'm trying to fix this as quickly as possible

**Comment by xSparky911x** [comment]
Ahh that really sucks. I feel your pain :( I figured it was a connection issue. But I also didn't want to get yelled at by Darkosto for not reporting it lol Best of luck!
