### ISSUE TITLE
Issues with BQM multiplayer (possibly LAN related)

### ISSUE THREAD

**Issue by JonathanCSmith** [Funwayguy/BetterQuesting#128]
I am currently observing a couple of issues with BQM when using the project ozone 2 modpack. I am not sure if this is due to it being on the 1.7.10 branch but I thought I would report them just in case.

I am currently playing on LAN and experiencing a great deal of difficulty with creating a party and syncing progress. Invites to party seem to disappear or not register. Additionally, when I complete a quests it shows completed in the book for the other players on the team but it is incomplete when opened (and cannot be completed). This was tried with a fresh book (bqs was reset), Player 1 completed the diamond quest in PO2 (first quest), the second player is now locked from completing or claiming the reward). Along side this we have experience issues with forcing BQM to detect items in the inventory for completing a quest, but this may have been a side affect of this sync issue. 

In the meantime we will move to a server, which I suspect works fine as you don't seem to have any other reported issues.

**Comment by Funwayguy** [comment]
Most of the party related stuff I'm already in the process of fixing however I have yet to see invites disappear. You could try looking into the QuestingParties.json file if you want to check if the invites are still listed and valid

**Comment by JonathanCSmith** [comment]
Well, I just want to confirm and mention a couple of things.

Just switched to a fresh server (last was an existing save where we used HQM that we updated). One thing I did notice was that in our 2.2.2 - 2.2.3 LAN world (modpack version) only a few of the quests were shown (i.e. many were hidden due to the previous quest not being complete), but in the current fresh install on a server I can see all of the available quests in a section.

Not sure if this is a facet of the above problem of a feature. Everything else seems to be working well on the server though!

**Comment by JonathanCSmith** [comment]
Another update, seems I spoke too soon. Player 1 completed a two stage quest (in PO2 it was pound the ground) and then places one of the items from the quest on the ground (furnace). Player 2's icon marks as complete (i.e. blue halo) but when the quest is opened the first part of the quest (collect 64 cobble) is marked as incomplete, but registers as 64 whilst the second section says 0/1 for the furnace.

Quests that are locked out because of quest dependency that another player has completed are still achievable.

As you say your fixing party stuff now, I assume you know these, but thought I would provide as much information as possible to aid in testing!

**Comment by Funwayguy** [comment]
Just sent out those updates. Can you see if your issue is still happening in those versions?

**Comment by JonathanCSmith** [comment]
Just downloaded 208, the fix didn't backport to our old progress for some reason. There was a weird situation where both players synced a completion correctly but only one could claim it. Resetting the book completely seems to have fixed everything though. Happy to call this one resolved (and thanks for this swift fix!!!)

**Comment by JonathanCSmith** [comment]
Spoke too soon. After a few staying in sync (working together) we separated and once we diverged far enough the completion trees broke again (we have a bunch of completed quests but 50% green 50% blue). 

Sometimes a quest can be brought back into sync by completing with items in your own inventory, but only rarely (and again detect does not work - see #130)

**Comment by Ryukossei** [comment]
I am also having the same issue with my game as well. I am showing in the quest book that it has been completed (by either my brother or his friend) Yet if I open it, I cant complete it to continue on. I was trying to complete quests today to try and get my book caught up with my brother and his freind but it is not allowing me to complete any quests that the have completed, nor collect any rewards from those completed quests. I cant even continue on in the game because i have no access to any of the quests at all. We have tried resetting the book, deleting and recreating the book and a few other things that my brother has tried server side. I dont know what to do because i cant really play with them because I cant do anything to help them at all.

**Comment by Funwayguy** [comment]
Took me way longer than it should have but I figured out what happened this time. Classic 'missed a spot' problem. I fixed automatic quest completion for things like crafting and item detection but not on manual detect/consume. Next update should resolve it but unfortunately like last time it won't have retroactive fixes.

**Comment by Funwayguy** [comment]
Just uploaded builds 2.0.210 (1.7.10) and 2.3.211 (1.10.2). Let me know how these work out for you

**Comment by JonathanCSmith** [comment]
For me the latest version works great. Also closes Funwayguy/StandardQuestingPack#44. 

One thing that might be worth considering is greying out the detect/submit for tasks that cannot be completed using items already in the inventory. Might reduce some of the confusion for task completion in PO2.
