### ISSUE TITLE
Party System not notifying upon invite

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#13]
When we try to create a party and invite other players I see this in the server logs:
```
06.02 15:54:40 [Server] STDOUT [betterquesting.network.PktHandlerPartyAction:handleServer:127]: Inviting player Drethic
```
But I never get a notification saying I've been invited.  And when I checked my party book there wasn't a notification.  However, when I created my own party, kicked myself, closed and opened the party book I was in the party I was invited to.

**Comment by Funwayguy** [comment]
This may partly be a client-server desync issue I've overlooked but the notifications were in fact missing.

**Comment by Funwayguy** [comment]
I have fixed this but I decided against having chat notifications for invites because of the potential risk of spam on bigger servers.
