### ISSUE TITLE
Command to set/unset Hardcore instead of toggle

### ISSUE THREAD

**Issue by TinkerWorX** [Funwayguy/BetterQuesting#132]
I have a couple of quests setup that allow the player to pick between regular mode and hardcore mode before starting. I currently have it working by ensuring that the game starts with hardcore off and then only toggle if they select the hardcore path. However, it would be safer if I could simply do something along the lines of
`/bq_admin set hardcore true`
`/bq_admin set hardcore false`
The existing command would still be fine as `/bq_admin hardcore`

If you think this is a good idea, it would be a great small tweak for someone who wants to contribute.

**Comment by Funwayguy** [comment]
Just pushed out an update which includes this feature. You can now either use the old method of `"/bq_admin hardcore"` to toggle or `"/bq_admin hardcore true"` to set it to a particular mode.

There's also `"/bq_user hardcore"` for users in single player who want to play hardcore without activating cheat mode. This one however cannot be reversed like the admin variant and can only be used in single player or by the LAN host.

**Comment by TinkerWorX** [comment]
Nicely done.
