### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by DarkBlade177** [Funwayguy/BetterQuesting#134]
Is that possible to edit the Questings online (inside of the Multiplayer Server? )

**Comment by Funwayguy** [comment]
Yes. You can also have multiple editors at the same time (just try to refrain from editing the same quest at the same time)

**Comment by DarkBlade177** [comment]
Thank you, i will do that :D

**Comment by DarkBlade177** [comment]
Is there a way to disable the rewards on the NEI?

![image](https://cloud.githubusercontent.com/assets/18588529/22353221/a0dd9cb2-e406-11e6-98a8-4d05e664a93d.png)

**Comment by DarkBlade177** [comment]
up :D

**Comment by Funwayguy** [comment]
no it can't be disabled. Can you not keep reopening this thread. These questions are better suited for the forums where other people can help you just as well.
