### ISSUE TITLE
[Suggestion] A config do disable the opening of QuestGUI from keyboard

### ISSUE THREAD

**Issue by EverNife** [Funwayguy/BetterQuesting#137]
This is useful when you use the `QuestBook` mod

Sou you force people to use the book and not use the keyboard

**Comment by Funwayguy** [comment]
...or you could just bind the key to none.

**Comment by EverNife** [comment]
then the player could just change it back again?

**Comment by EverNife** [comment]
Whatever... seems something that the questbook mod itself should take care
