### ISSUE TITLE
NPC Int Crash

### ISSUE THREAD

**Issue by jordanasch** [Funwayguy/BetterQuesting#138]
Hey Funwayguy figured I'd let you know this crash happens every time I try and add the NPC addon

Thanks
Aschy

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.1-70.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 1/28/17 1:52 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: noppes/npcs/controllers/QuestController
	at bq_npc_integration.NpcQuestDB.onWorldLoad(NpcQuestDB.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_75_NpcQuestDB_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: noppes.npcs.controllers.QuestController
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1220883264 bytes (1164 MB) / 1409286144 bytes (1344 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx2048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151-universal.jar) 
	UCHIJAA	Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151-universal.jar) 
	UCHIJAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAA	betterquesting{2.3.211} [Better Questing] (BetterQuesting-2.3.211.jar) 
	UCHIJAA	Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
	UCHIJAA	tem{2.1.0} [Tim's Expansion Mod] (ExpansionMod-2.1.0(MC1.10.2).jar) 
	UCHIJAA	gemcraft{1.2.5} [Gem Craft] (gemcraft-1.10.2-1.2.5.jar) 
	UCHIJAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.6-1.10.2.jar) 
	UCHIJAA	bq_npc_integration{2.3.19} [NPC Integration] (NPCIntegration-2.3.19.jar) 
	UCHIJAA	bq_rf{2.3.24} [RF Expansion] (RFExpansion-2.3.24.jar) 
	UCHIJAA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCHIJAA	bq_standard{2.3.124} [Standard Expansion] (StandardExpansion-2.3.124.jar) 
	UCHIJAA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Funwayguy** [comment]
You know it took me a while to notice but you don't have Custom NPCs installed to use the integration mod.

**Comment by jordanasch** [comment]
Oh crud! Sorry thank you very much for the heads up!
