### ISSUE TITLE
1.10.2 Quests Constantly Being Saved

### ISSUE THREAD

**Issue by Bartz24** [Funwayguy/BetterQuesting#144]
Each completed repeatable quest is causing the `Quest database saved as default` to show up in the console, even when the cooldown is finished.
With enough completed quests, the game will start having lag spikes every second.

**Comment by Funwayguy** [comment]
I don't auto save the database to default. I think that might be an issue related to this mod:
https://minecraft.curseforge.com/projects/better-questing-auto-reload

**Comment by Bartz24** [comment]
Oh, ok thanks
