### ISSUE TITLE
Object Submission Station doesn't work with repeatable quests 

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#145]
Minecraft 1.7.10
BQ 2.0.216
Repro:
1) Create a quest. Set it to a cooldown. (I used a task for 1 stone, reward of 1 wood, 0 second cooldown.)
2) Open the Object Submission Station, note that it can see that quest.
3) Complete the quest. (Manual or OSS)
4) It is now impossible to select the quest in the OSS.

You can still manually complete the quest as many times as you want, but the OSS only works for the first completion.

**Comment by Funwayguy** [comment]
This was somewhat fixed in 2.0.218 and 2.3.219. The task can be completed again using the OSS but will need to be set via the GUI each time. I may change this in a later update so the OSS supports continuous use.
