### ISSUE TITLE
Cooldown is in ticks, but displayed as seconds

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#146]
Minecraft 1.7.10
BQ 2.0.216
Repro:

1) Create a quest. Set the repeatTime to 1200. (60*20, should be 1 minute.)
2) Look at the quest in the designer/quest category screen, while holding shift.
3) Note the Cooldown is 20 minutes.
4) Complete the quest. Note the actual cooldown is 60 seconds.

**Comment by Funwayguy** [comment]
Fixed in 2.0.218 and 2.3.219
