### ISSUE TITLE
Object Submission Station can't automatically complete quests

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#147]
Minecraft 1.7.10
BQ 2.0.216

1) Create a quest. I used 10 stone, with a reward of 1 wood plank, but the details don't matter too much.
2) Set an Object Submission Station to this quest, then feed the items needed.
3) Open the quest in the regular BQ interface. Note that the retrieval task isn't actually complete, even though all of the required items have been sent in. You need to hit the "Detect/Submit" button for BQ to recognize the quest is actually complete and offer up the reward.

**Comment by Funwayguy** [comment]
Part of this is actually normal behaviour if you're in edit mode. Better Questing doesn't auto-update some tasks in edit mode to keep them from automatically completing themselves mid edit.
