### ISSUE TITLE
Object Submission Station needs a better quest selection method

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#148]
Minecraft 1.7.10
BQ 2.0.216

Well, it does. Right now, it can just scroll through quests via 2 arrows, and I already have over 70 quests. That's unwieldy, and there are HQM modpacks that brag of having hundreds of quests.
(Also, the quests are arranged by quest ID (I think), instead of being alphabetical or something that has actual meaning to the player.)

Suggestions:
* Drop down list.
* Make it so you select the quest group, then the quest.
* Right-click with BQ quest book. (Which may not be installed, but still useful.)
* Including the main BQ UI inside the OSS.
* Button to create a quest token while looking at a quest inside the BQ UI. (Like a right-click with a BQ quest book, but doesn't need the quest book installed.)

**Comment by Funwayguy** [comment]
The OSS should only show unlocked quests (this needs some slight adjusting with the new cache). It's highly unlikely anyone would have 70 active quests at any given time. That said, I do have plans to upgrade the UI but it won't be any of the above suggestions. The solution I'm going for is swapping out the arrows for a single scrolling list.

**Comment by evilmrhenry** [comment]
Because of the nature of my modpack, most of my 70+ quests are active at all times.
