### ISSUE TITLE
Error in log during world unload during server shutdown

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#15]
We are currently using Better Question 1.0.20 and during a log review I found this error:
http://pastebin.com/2xKW34XK

This seems to happen any time we shut down based on the logs for the last few days.

**Comment by Funwayguy** [comment]
That's actually a really bad bug. Fix coming ASAP

**Comment by Funwayguy** [comment]
Fixed in build 1.0.23
