### ISSUE TITLE
Object Submission Station breaks after completing a repeatable quest

### ISSUE THREAD

**Issue by evilmrhenry** [Funwayguy/BetterQuesting#150]
Minecraft 1.7.10
BQ 2.0.216
Repro:
1) Create 3 repeatable quests. (Tested with cooldowns of 0 and 1200)
2) Complete quest 3.
3) Open the OSS, and try to go to quest 2.
4) The OSS will switch back to quest 1 nearly instantly.
5) Bonus: try to edit the title of any of the quests. Your changes will revert nearly instantly.

**Comment by Funwayguy** [comment]
Fixed in 2.0.218 and 2.3.219
