### ISSUE TITLE
Loot-chest "Max retrieval count"

### ISSUE THREAD

**Issue by EverNife** [Funwayguy/BetterQuesting#152]
An option to make a loot-chest be received only x times.

(Exemple, i want to give each part of draconic armor into rare loot-chest... but i don't want the player to receive, for exemple, 2 helmets '-' )

**Comment by DarkBlade177** [comment]
I was about to ask for that too. I passed all my 150 quests to Questbook and when i was passing the rewards I noticed that. (Great mod if i may say) :+1:

**Comment by Funwayguy** [comment]
I'll take a look at it at a later date. Trying to port everything up to 1.11.2 at the moment
