### ISSUE TITLE
Editmode strange behaviour

### ISSUE THREAD

**Issue by drz2k** [Funwayguy/BetterQuesting#154]
Has anyone seen this before? Cant move Quests around anymore :/

https://youtu.be/f1ZKQioF2HI

**Comment by drz2k** [comment]
Restarted the client several times, even the whole PC. 
Having the client sit (with the strange behaviour) in the background for 2h+ and coming back to it, it magically selfhealed ;)

**Comment by drz2k** [comment]
Strange it happens over and over again

**Comment by drz2k** [comment]
Slowly but surely its getting on my nerves not beeing able to work on the quests. Thoo im at a point where kicking out BQM and doing HQM again would hurt.

**Comment by Funwayguy** [comment]
I'm a bit caught up in Uni assignments a the moment. I have a potential fix in mind but until I get this work out the way I can't implement it.

**Comment by drz2k** [comment]
Well any workaround would be welcome...but i cant even edit texts right now and since this weekend was reserved for galactic science 2 this is quite a bummer :(

**Comment by Funwayguy** [comment]
If it helps, it has to do with repeatable tasks constantly ticking the editors. Disable them and you should be able to edit per-usual for now

**Comment by drz2k** [comment]
Well i have no repeatable quests but your hint with the ticking was right.

I had an active RF submission quest going on. Poking the submission block out of existence fixed the issue!

This also explains how it magically fixed itself the first time. The quest was done i think ;)

**Comment by Funwayguy** [comment]
Well that's interesting, didn't account for the OSS. Guess I'll have to fix that too

**Comment by drz2k** [comment]
Aye. But well, I can continue work now *happypanda*
