### ISSUE TITLE
Custom Home Screen Image Is Counter-intuitive and has 2 Images for What purpose?

### ISSUE THREAD

**Issue by Darkosto** [Funwayguy/BetterQuesting#157]
https://i.artdude.uk/darkosto/uzuGlwu0.png

I'm still not quite sure why there are two images? Why does the default home image not follow this same structure? It should be simple to add a home image, not require me to spend hours on a non-essential part of a modpack.

**Comment by Boolyman** [comment]
I figured out while working on mine, that It's actually a messed up wrap of the same picture.  To work around it, I had to create a PNG with top half of the canvas the picture, and the bottom half a blank background.  So when the bottom half wrapped back over, it could  not be seen.
Click below to see how blank background extends.

![questfront2](https://cloud.githubusercontent.com/assets/24765883/22990537/628351b0-f36e-11e6-9194-f262691e3762.png)
