### ISSUE TITLE
Add-on approval and Party Notification API

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#16]
Can you please review an add-on I've made [Quest Book](https://github.com/Drethic/QuestBook) and let me know if you approve it's release to Curse?

Also, I was looking the through the Party API and didn't see a way to hook notifications.  I was going to setup the book to shimmer when a user got an invite.  I know earlier you didn't want to inform the user due to risk of spamming, but would this be a viable option?  If so, what would be the best way to listen for that event?

**Comment by Funwayguy** [comment]
I suppose this would be useful for people obsessed with the need to have a book for questing. Also you don't necessarily need to ask me for permission or approval, feel free to make whatever add-on you like.

If you need to check party invites for the player you could do something like:

`
public boolean lastStatus = false;

public boolean showInviteNotice(EntityPlayer player)
{
    // Only updates the variable every 10 seconds
    if(player.ticksExisted%200 != 0)
    {
        lastStatus = PartyManager.getParty(player.getUniqueID()) == null && PartyManager.getInvites(player.getUniqueID()).size() > 0;
    }
    
    return lastStatus;
}
`
