### ISSUE TITLE
1.11.2 Crash when making an optional quest reward for block break quest

### ISSUE THREAD

**Issue by DingoX3** [Funwayguy/BetterQuesting#162]
I made a block break quest for wood. First quest edited. When i choose an oak sapling for the first optional reward it crashes.

full crash report: [HERE](http://pastebin.com/dN0dpJgz)

minecraft version 1.11.2
Forge version: 13.20.0.2230
better questing version: 2.4.223
better questing standard version: 2.4.129

**Comment by SDUBZ** [comment]
crashed also when trying to change amount of items to retrieve 
[crash-2017-02-17_07.32.36-client.txt](https://github.com/Funwayguy/BetterQuesting/files/781475/crash-2017-02-17_07.32.36-client.txt)

minecraft version 1.11.2
Forge version: 13.20.0.2230
better questing version: 2.4.223
better questing standard version: 2.4.129
