### ISSUE TITLE
Problem Scrolling in Loot Rewards

### ISSUE THREAD

**Issue by RKAHN82** [Funwayguy/BetterQuesting#164]
Forever Stranded Modpack, 1.10.2
Was told to report this here.

https://clips.twitch.tv/kasrith/WittyCrocodileTheTarFu

Whenever I scroll down to select a loot reward the scroll bar automatically pops back to the top and I cannot select any rewards below cutoff.

**Comment by Funwayguy** [comment]
Just sent out a bug fix update for this now
