### ISSUE TITLE
Crafting tasks do not detect crafting out of order

### ISSUE THREAD

**Issue by codewarrior0** [Funwayguy/BetterQuesting#165]
A quest that is grey because it has unmet requirements will not give the player credit for crafting any items required for its crafting tasks. This leads to the player needing to craft extra, often useless items to receive quest credit if he had crafted some of them "too soon". 

This problem is much worse when playing some less-than-quality quest books where the order of quests does not match the crafting tech-tree.

**Comment by Funwayguy** [comment]
Better Questing can in fact detect crafting out of order but it's up to pack developers to enable the "lockedProgress" flag on the quest's properties.

**Comment by codewarrior0** [comment]
Then that flag should be enabled by default, and it should be up to pack developers to disable it. It's pointlessly cruel that the default behavior is to force me to craft a second Transmutation Table or Tool Station or whatever, only because I crafted the first one "too soon".

**Comment by codewarrior0** [comment]
It isn't obvious what the "lockedProgress" flag does as there is no descriptive text nearby, and the option is also buried behind three layers of "Advanced" property sheets. I doubt a single questbook author even knows about it.

Once again, giving quest credit even for locked quests should be the default.
