### ISSUE TITLE
Issue with .JSON files

### ISSUE THREAD

**Issue by dethbeginsagain** [Funwayguy/BetterQuesting#168]
when i was working on my modpack i noticed that the JSON files failed be created and the configs wont fully load, it isn't a issue with the other mods, and it was tested solo, it still seem to follow, my version for minecraft is 1.7.10.

**Comment by Funwayguy** [comment]
Are you sure it isn't loading? They'd be some pretty serious errors in your log files if that was the case. JSON files should normally be saved with the world directory not in the config directory.

**Comment by Flabort** [comment]
As far as I know, JSON files aren't created in the config directory until you save a default quest line. So like the dev said, look around in your world folder.

**Comment by dethbeginsagain** [comment]
ok i found that, the json files there, how can i make them default?

is there and option i click or a possible command i use to make them?

**Comment by dethbeginsagain** [comment]
i see the different files but... i can't seem to find the defaults. Any way of those being found?

**Comment by Flabort** [comment]
You need to make a default quest line for one to appear in the config.

Do it like this:
Step 1: /bq_admin edit
Step 2: Create a quest
Step 3: /bq_admin edit
Step 4: /bq_admin default save
Step 5: Minecraft/config/betterquesting/DefaultQuests.json

**Comment by dethbeginsagain** [comment]
huh
mm k then i'll give it a shot, but i made a ton of quests already. Do i have to redo?

**Comment by Flabort** [comment]
If you already made quests, just do steps 3 through 5.
