### ISSUE TITLE
Source code is not licensed

### ISSUE THREAD

**Issue by codewarrior0** [Funwayguy/BetterQuesting#169]
There is no license text, either in the file `LICENSE.md` or in each source code file, which explains what our rights are regarding the source code. By default, this means we have none - "Copyright Funwayguy, All Rights Reserved"

**Comment by Funwayguy** [comment]
From GitHub's TOS:

> We claim no intellectual property rights over the material you provide to the Service. Your profile and materials uploaded remain yours. However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, **you agree to allow others to view and fork your repositories**.

So yes you are allowed view all the code and fork the project, you just can't redistribute it. I however do not own the rights to code submitted by pull requests. Although two PRs have been made to BQ, I haven't actually merged them for various reasons and instead used my own implementation meaning I still hold the rights to everything currently in BQ.

**Comment by WesCook** [comment]
>More ominously, several forks of your project already exist, and if you have not issued copyright notices to them (or explicitly granted them permission) you may stand to lose your copyright due to lack of due diligence.

Are you sure you're not thinking of trademark law?  As far as I know, there's nothing in copyright law which says that the IP holder must be be vigilant in enforcing their copyright.
