### ISSUE TITLE
quest detecting percentage or items in inventory

### ISSUE THREAD

**Issue by SDUBZ** [Funwayguy/BetterQuesting#17]
i made quest but its not detecting items done but also saying complete [http://puu.sh/nPuxT/398c49486a.png](url) also [http://puu.sh/nPuCz/961518b119.png](url)

**Comment by Funwayguy** [comment]
That's not a bug, it just auto completed before you added the first task. Use the commands to reset it and you can test it then. If it bothers you that much I can tweak it slightly to not do that in edit mode

**Comment by AnimeniacYuuto** [comment]
I am having a similar/the same problem with a repeatable consume quest. When creating the quest by default it has the same issue where I can't turn in the items and is already allowing me to claim the reward. I attempted to fix this with the reset command to no avail. 

I can temporarily alleviate the issue by deleting the object added to the "completed" list, how ever the issue resurfaces as soon as I claim the reward the first time.

If it is worth noting the repeatTime is set to 20

**Comment by Funwayguy** [comment]
@AnimeniacYuuto repeat time is in game ticks so 20 would be equal to only 1 second. I'll look into this a bit more but updates 1.0.47, 1.1.48 and 49 should fix the immediate issue of auto-complete when editing task-less quest.

**Comment by Funwayguy** [comment]
Pretty sure I fixed this a number of versions ago.
