### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by chrsgddrd** [Funwayguy/BetterQuesting#171]
I'm having a hard time using this mod at all, here's pictures of what's happening:

https://gyazo.com/e988afd6caa0af7cb6a750768dde8d04
https://gyazo.com/7db6b698630f11ccde34375c195356d2
https://gyazo.com/62441738dfd401e92700dbdedd562aef

So the first one, I try and make a party, but any time I try and type in any kind of name, it resets the field. I cannot put in a party name. 

Second one, I try and scroll down in the book, it auto scrolls up to the top, won't ever stop.

Third one is a crafting task, I make a crook but it won't detect it being made in the book. I'm clicking detect/submit at the end of the gif.

Everyone on my server are experiencing these.

**Comment by Funwayguy** [comment]
Seems repeatable tasks and OSS blocks are still breaking things with their constant ticking... uhhhgggg. I'll see what I can do but I'm juggling some Uni assignments at the moment so no guarantees.

**Comment by chrsgddrd** [comment]
Alrighty, thanks!

**Comment by Broklyndatroll** [comment]
chrsgdded, I can confirm your first 2 issues on the Project Ozone2 - Kappa server I play and am staff on. Additionally, the scroll reset also happens on our Ferret Business server where it happens near instantly and non-stop if a RF Submission quest is active.

In regards to you 3rd issue, that is a Retrieval Task, not a Crafting Task. Try having the Oak wood, planks, and sapling in your inventory at the same time as the Crook.
