### ISSUE TITLE
[2.3.225] Crash with selecting Forestry bees in Quest Editor

### ISSUE THREAD

**Issue by SPMoo66** [Funwayguy/BetterQuesting#176]
Tried selecting a bee as a quest objective and the game crashed.

http://pastebin.com/xPJnEBH9

Using Forestry 5.2.17.368 alongside Better Questing 2.3.225 on 1.10.2.

Never had this crash with earlier versions of Better Questing/Forestry. Taking a wild guess that this isn't on Forestry's end, but I could be wrong.

**Comment by Funwayguy** [comment]
From a quick look it seems Forestry doesn't take too kindly to having a Bee item with blank NBTs and doesn't have any fallback handling code. I could catch the error and prevent Minecraft from hard crashing but the item/task/quest would still be broken in the background constantly throwing errors.

**Comment by SPMoo66** [comment]
Hmm, that's interesting. It didn't crash when I initially set up the quests a while back. Must've been a recent update then.
I'd appreciate it if you could prevent the hard crash if only so I could salvage the quests I'd already written until I change the bees out, but I suppose I'd be able to edit the Database json file directly if that's not an option.
I tried putting blank NBT in as a catch-all for bee stats in Better Questing, but would it matter if I just pick the default one shown by Forestry? I know that Better Questing can be really picky when it comes to some things.
