### ISSUE TITLE
crash when making quest

### ISSUE THREAD

**Issue by SDUBZ** [Funwayguy/BetterQuesting#179]
forge: 1.11.2-2259
D3 core: D3Core-1.11.2-1.3.0.65
lumber axe: Lumberjack-1.11.2-1.3.1.48
bqm: BetterQuesting-2.4.226
crash report:
[crash-2017-03-24_03.35.13-client.txt](https://github.com/Funwayguy/BetterQuesting/files/865468/crash-2017-03-24_03.35.13-client.txt)

**Comment by Funwayguy** [comment]
This appears to be a crash with doubledoordev not BetterQuesting.
