### ISSUE TITLE
BQM requires all items when validating a quest

### ISSUE THREAD

**Issue by andre-paulo98** [Funwayguy/BetterQuesting#183]
I'm on modpack Project Ozone 2 (1.7.10)
It has BQM version 2.0.224
Sorry if it was already reported and fixed, didn't had time to search.
Lets say on one quest you teach the player how to make a piston. You ask the player to hold 3 planks, 4 cobblestone, one iron and one redstone. Then with that craft a piston.
The Detect/Submit button should work for each item of the quest, not all of them.
You would have to craft the piston and then grab all the items again, the planks, cobblestone iron and redstone

**Comment by Funwayguy** [comment]
There's a setting in the retrieval task called groupDetect that toggles this functionality
