### ISSUE TITLE
1.7.10 Suggestion

### ISSUE THREAD

**Issue by Gamerbolts** [Funwayguy/BetterQuesting#184]
Hi, enjoying this mod greatly. Creating a big questing/tutorial modpack and have been implementing quests as I was doing so was wondering something, I have my questline for a certain mod completed. but if I have to don't want to move everything over one at a time, is there a way or can there be a way to make a selection and move everything? If not that would be a great feature for myself and possibly others :) Thanks!

**Comment by Funwayguy** [comment]
Box selecting multiple things at once is one of the ideas I've had for the UI rewrite, in the mod's current state it isn't really possible so until that day comes one-by-one is the only way, sorry.
