### ISSUE TITLE
1.7.10 Suggestion #2 - Quest progession unlocks gamerule keepInventory false

### ISSUE THREAD

**Issue by Gamerbolts** [Funwayguy/BetterQuesting#187]
Hi again, I was wondering if something was going to be possible. Let me explain

I have a modpack *Bolts Crazzzy Adventure* (Yes with 3 Zs on purpose) It is a very hard modpack. Quite hard in fact to start out. Many things want to kill you, They can break down walls etc. I have been wondering if there was a way with the BQ mod to set it for when someone reaches a certain amount of quests done or a certain questline, then the gamerule KeepInventory will be turned off. While it is still on for everyone else. That way new players to the modpack aren't turned away by how hard it is and can get a footing in the world before keepinventory is turned off. And if that is possible would like them to have a message that pops up that warns them.

If this or something like this already exists in BQ and I am missing it please let me know. If it is possible or something like this is possible please let me know. If it is not possible at all please let me know

Thank you very much
-Bolts

**Comment by EverNife** [comment]
Hmm, i think you should use a plugin for that :/

BQ allow us to execute commands as quest rewards, so, a command to enable this.

Seems to be something really out of BQ...
But i think its not hard at all to be done, soo...

**Comment by Gamerbolts** [comment]
ok, ty I will check plugins and see what I can find. Thats for the help

**Comment by Funwayguy** [comment]
BQ can run the vanilla gamerule commands as rewards, no special plugins required for that, but if you want it to be player specific then yes you're going to need a mod to manage that.

**Comment by Gamerbolts** [comment]
I see yeah that is the problem I was running into my friend thinks he can find something with spigot. Seems unheard of for a mod to give just one person a different gamerule lol.

**Comment by Funwayguy** [comment]
Think less 'gamerule' and more like a Soulbound inventory. In actuality if you know what event to hook you could pull this off in a very small amount of code. In comparison, the mod container and command to modify the player would take more code than the hook itself.

**Comment by EverNife** [comment]
I suggest a plugin called Skript, in my oppinion is the best one! I have already done what you need (keep inventory on death) once in the past.

Just warning that baubles itens will not store (bukkit cant handle that) .

**Comment by Gamerbolts** [comment]
ok, my friend is the coder so he'll work that out. I'm the modpack maker and quest designer. But I will show him what you guys said and see if we can get this idea working. Thanks a lot guys. You've helped a lot
