### ISSUE TITLE
Server play error

### ISSUE THREAD

**Issue by BakermanLP** [Funwayguy/BetterQuesting#19]
Hello,
I am playing the modpack ProjectOzone on a server. Last Update (Beta) includes BetterQuesting and there is my problem. After starting the server and client, connecting to the server and opening the questbook all seems ok. After completing the first quest, the client disconnects from the server.

Partial server log:
http://pastebin.com/eysaKYHV

Partial client log (latest.log):
[10:54:40] [Client thread/INFO]: betterquesting.client.gui.GuiHome

Versions:
- BetterQuesting-1.0.65.jar
- StandardExpansion-1.0.36.jar
- questbook-1.0.1.jar

After this error i can't relog to the server.

Can this be fixed???

Michael (aka BakermanLP)

**Comment by Funwayguy** [comment]
Seems I made another client-server mistake when syncing choice rewards. Working on fixing it

**Comment by Funwayguy** [comment]
This should be fixed now in 1.0.71, I'd highly recommend updating Standard Expansion to 1.0.45 too as that contains a fix for choice rewards.
