### ISSUE TITLE
Same quest, two screens!

### ISSUE THREAD

**Issue by EverNife** [Funwayguy/BetterQuesting#194]
Some of my new quests (trying to create new quests in the MultiPlayer) are appearing in more them one screen.

For exemple, i create this one in the ` Geração de Energia`
![2017-05-15_19 58 29](https://cloud.githubusercontent.com/assets/11357801/26084781/3a272164-39b5-11e7-8cb3-b763fef29934.png)

But, when i was looking into the other pages, it appeared in the  `Botania`

![2017-05-15_19 58 31](https://cloud.githubusercontent.com/assets/11357801/26084804/680c8038-39b5-11e7-959a-c446a5d48c6b.png)

The id is the same..
This is not the first time, in the previous one i tried to delete the quest that was in the wrong page, but, it result that both of them were deleted... the correct one and the wrong one :/

**Comment by Funwayguy** [comment]
Quests can actually be added to two separate quest lines, this is perfectly normal and intended. When editing them you'd use the 'remove' tool not 'delete' if you want to remove the quest from one line and not any others.

**Comment by EverNife** [comment]
Ty :D
