### ISSUE TITLE
[1.10.2] @p not parsed properly in command block. 

### ISSUE THREAD

**Issue by KompuLogix** [Funwayguy/BetterQuesting#197]
As the title says. 

/bq_admin reset all username 
this works in the command block.
however 
/bq_admin reset all @p
to grab nearest player doesn't work. just shows usage information.

**Comment by WesCook** [comment]
@p doesn't actually seem to work in the command form either.  I need to enter the username directly.

**Comment by KompuLogix** [comment]
The @p argument in a command block works to replace @p with the nearest players username.

**Comment by WesCook** [comment]
Yes, but what I'm saying is that `/bq_admin reset all @p` doesn't work when entered into chat, or command blocks.  Whereas `/bq_admin reset all KompuLogix` will work.

BetterQuesting doesn't support the @p syntax at all.  It's not a command block specific issue.

**Comment by KompuLogix** [comment]
Yes that i understand, however @p is a function of the commandblock command executor and if the base command "/bq_admin reset all %user%" was implemented properly to anticipate the usage of the command with command blocks it should work. 

Now don't get me wrong im not complaining, im just wishing the command was fully functional with commandblocks like many other mod commands. 

But if you choose to not bother making it function fully with command blocks that's up to you.

My purpose for this was that i was making a spot in spawn where a user could go if they want a completely fresh start press a button and a series of command blocks resets their profile to default. without the need of an admin, nor the need to manually make a button for every user on the server.

**Comment by WesCook** [comment]
>But if you choose to not bother making it function fully with command blocks that's up to you.

I'm not the developer, so I have no impact on that decision.  I was just looking to clarify the issue.

**Comment by KompuLogix** [comment]
Sorry, long day. But yes i think this has been fleshed out better for the dev to understand the underlying principle thanks to you. Good Work.

**Comment by KompuLogix** [comment]
For the time being i am writing my own plugin for sponge that handles this and runs a bunch of commands in succession manually putting in the user after finding it once. No more need for an array of command blocks. I just wish i didn't need to do this.

**Comment by Funwayguy** [comment]
Part of the reason I haven't 'fixed' this is because I'm not entirely in charge of how that parameter functions. The command tells Minecraft which argument is the username parameter (which I do) and after that Minecraft does all the fancy stuff.

EDIT: Okay... seems Minecraft has a VERY specific way of dealing with selector tokens that aren't `@a` (which I test with). Seems `@r` and `@p` don't even give me the username/uuid of the player unless I specifically ask for it from code. I might be able to make a fix fairly quick but not this weekend

**Comment by KompuLogix** [comment]
No rush, thanks for taking a look into it.

**Comment by Funwayguy** [comment]
New updates posted to fix this. I've tested it myself with `@p` and `@r` but let me know if it works for you.
