### ISSUE TITLE
Crash on gui interface usage

### ISSUE THREAD

**Issue by jordanasch** [Funwayguy/BetterQuesting#198]
Hello, I am having a problem on a LAN server using 1.10.2 and a very recent version of forge.

This only happens to players logged in and not the host client.

When clicking the ">" button to scroll through the "Claim" tabs it crashes, only with quests way down the the quest tree.

The quests do involve the "faction" reward type from NPC integration, and is the first appearance of this faction in rewards. But it is not the first time this reward type is used and in the first ones there is no crashing.

Here is the crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (CustomStuff3-1.10.2-0.11.7 .jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  MDECore-Core (mdecore-1.10.2-1.5.1.jar)
  ServerPropertiesLAN (ServerPropertiesLAN-2.4.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  ProgressionTransformer (Progression-1.10.2-0.6.9.jar)
  SurgeLoadingPlugin (Surge-1.10.2-1.1.0.70.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/26/17 12:03 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at bq_npc_integration.client.gui.rewards.GuiRewardNpcFaction.drawBackground(GuiRewardNpcFaction.java:37)
	at betterquesting.api.client.gui.GuiScreenThemed.drawBackPanel(GuiScreenThemed.java:96)
	at betterquesting.client.gui.GuiQuestInstance.drawBackPanel(GuiQuestInstance.java:122)
	at betterquesting.api.client.gui.GuiScreenThemed.func_73863_a(GuiScreenThemed.java:108)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:512)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1409)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bq_npc_integration.client.gui.rewards.GuiRewardNpcFaction.drawBackground(GuiRewardNpcFaction.java:37)
	at betterquesting.api.client.gui.GuiScreenThemed.drawBackPanel(GuiScreenThemed.java:96)
	at betterquesting.client.gui.GuiQuestInstance.drawBackPanel(GuiQuestInstance.java:122)
	at betterquesting.api.client.gui.GuiScreenThemed.func_73863_a(GuiScreenThemed.java:108)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:512)

-- Screen render details --
Details:
	Screen name: betterquesting.client.gui.GuiQuestInstance
	Mouse location: Scaled: (182, 186). Absolute: (364, 107)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['talmiiorCAM'/32631, l='MpServer', x=-3374.18, y=46.50, z=3353.69]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,35,0), Chunk: (at 0,2,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 395379199 game time, 3349853 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 120 total; [EntityCustomNpc['Chef'/32768, l='MpServer', x=-3349.50, y=32.00, z=3328.50], EntityPlayerSP['talmiiorCAM'/32631, l='MpServer', x=-3374.18, y=46.50, z=3353.69], EntityItem['item.item.goldNugget'/32769, l='MpServer', x=-3347.44, y=52.00, z=3330.17], EntityXPOrb['Experience Orb'/32770, l='MpServer', x=-3341.82, y=52.00, z=3327.09], EntityXPOrb['Experience Orb'/32771, l='MpServer', x=-3343.97, y=51.00, z=3325.04], EntityXPOrb['Experience Orb'/32772, l='MpServer', x=-3340.20, y=51.00, z=3326.03], EntityCustomNpc['Netherxile Gate Guard'/32773, l='MpServer', x=-3341.50, y=52.00, z=3327.50], EntityPigZombie['Zombie'/32774, l='MpServer', x=-3353.70, y=32.00, z=3317.70], EntityPigZombie['Zombie'/32775, l='MpServer', x=-3367.48, y=37.75, z=3334.70], EntityPigZombie['Zombie'/32776, l='MpServer', x=-3366.72, y=37.00, z=3333.49], EntityPigZombie['Zombie'/32777, l='MpServer', x=-3353.69, y=32.00, z=3314.89], EntityCustomNpc['Netherxile Tower Guard'/32778, l='MpServer', x=-3346.43, y=56.50, z=3320.86], EntityXPOrb['Experience Orb'/32779, l='MpServer', x=-3344.19, y=51.00, z=3326.22], EntityBlaze['Blaze'/32780, l='MpServer', x=-3341.50, y=74.00, z=3305.50], EntityBlaze['Blaze'/32781, l='MpServer', x=-3341.50, y=74.00, z=3305.50], EntityPigZombie['Zombie'/32782, l='MpServer', x=-3339.50, y=74.00, z=3306.50], EntityHorse['Skeleton Horse'/32783, l='MpServer', x=-3358.55, y=56.00, z=3389.22], EntityBlaze['Blaze'/32784, l='MpServer', x=-3353.66, y=53.00, z=3377.70], EntityBlaze['Blaze'/32785, l='MpServer', x=-3345.50, y=69.00, z=3388.50], EntityHorse['Skeleton Horse'/32786, l='MpServer', x=-3346.55, y=54.00, z=3375.48], EntityHorse['Skeleton Horse'/32787, l='MpServer', x=-3328.99, y=73.00, z=3366.05], EntityHorse['Skeleton Horse'/32788, l='MpServer', x=-3343.91, y=106.00, z=3364.01], EntityItem['item.item.rottenFlesh'/32789, l='MpServer', x=-3355.82, y=39.00, z=3364.32], EntityItem['item.item.goldNugget'/32790, l='MpServer', x=-3356.35, y=42.00, z=3366.06], EntityXPOrb['Experience Orb'/32791, l='MpServer', x=-3348.59, y=45.00, z=3362.98], EntityXPOrb['Experience Orb'/32792, l='MpServer', x=-3353.05, y=45.00, z=3363.51], EntityItem['item.item.rottenFlesh'/32793, l='MpServer', x=-3354.69, y=40.00, z=3364.59], EntityXPOrb['Experience Orb'/32794, l='MpServer', x=-3354.25, y=42.00, z=3362.25], EntityItem['item.item.rottenFlesh'/32795, l='MpServer', x=-3353.66, y=44.00, z=3362.35], EntityItem['item.item.goldNugget'/32796, l='MpServer', x=-3354.13, y=40.00, z=3364.34], EntityXPOrb['Experience Orb'/32797, l='MpServer', x=-3354.25, y=41.00, z=3363.25], EntityXPOrb['Experience Orb'/32798, l='MpServer', x=-3354.75, y=41.00, z=3363.25], EntityZombie['Zombie'/32799, l='MpServer', x=-3351.14, y=45.00, z=3363.86], EntityItem['item.item.rottenFlesh'/32800, l='MpServer', x=-3354.13, y=42.00, z=3362.50], EntityItem['item.item.rottenFlesh'/32801, l='MpServer', x=-3347.70, y=45.00, z=3364.31], EntityCustomNpc['Netherxile Gate Guard'/32802, l='MpServer', x=-3350.86, y=46.00, z=3365.14], EntityItem['item.item.rottenFlesh'/32803, l='MpServer', x=-3349.08, y=47.00, z=3367.04], EntityCustomNpc['Netherxile Gate Guard'/32804, l='MpServer', x=-3349.52, y=45.00, z=3358.49], EntityCustomNpc['Netherxile Tower Guard'/32805, l='MpServer', x=-3354.93, y=51.50, z=3362.41], EntityCustomNpc['Netherxile Gate Guard'/32807, l='MpServer', x=-3343.66, y=51.00, z=3331.52], EntityPigZombie['Zombie'/32816, l='MpServer', x=-3296.88, y=60.88, z=3338.54], EntityHorse['Skeleton Horse'/32817, l='MpServer', x=-3308.04, y=47.00, z=3384.20], EntityPigZombie['Zombie'/32819, l='MpServer', x=-3302.22, y=59.00, z=3344.31], EntityCustomNpc['Rayme'/32632, l='MpServer', x=-3366.59, y=37.00, z=3353.44], EntityArmorStand['Armor Stand'/32633, l='MpServer', x=-3370.50, y=35.00, z=3347.50], EntityArmorStand['Armor Stand'/32634, l='MpServer', x=-3370.50, y=35.00, z=3346.50], EntityArmorStand['Armor Stand'/32635, l='MpServer', x=-3370.50, y=35.00, z=3345.50], EntityPigZombie['Zombie'/32636, l='MpServer', x=-3379.50, y=89.00, z=3345.50], EntityHorse['Zombie Horse'/32653, l='MpServer', x=-3444.90, y=98.00, z=3316.02], EntityCustomNpc['Netherxile Tower Guard'/32654, l='MpServer', x=-3384.19, y=43.50, z=3366.92], EntityPigZombie['Zombie'/32656, l='MpServer', x=-3377.01, y=39.50, z=3360.50], EntityBabyPigZombie['Zombie'/32657, l='MpServer', x=-3385.23, y=43.00, z=3366.77], EntityPigZombie['Zombie'/32658, l='MpServer', x=-3385.50, y=35.00, z=3362.81], EntityXPOrb['Experience Orb'/32659, l='MpServer', x=-3378.98, y=35.00, z=3368.68], EntityXPOrb['Experience Orb'/32660, l='MpServer', x=-3379.59, y=35.00, z=3365.00], EntityHorse['Zombie Horse'/32664, l='MpServer', x=-3449.70, y=46.00, z=3376.07], EntityHorse['Skeleton Horse'/32672, l='MpServer', x=-3426.99, y=99.00, z=3325.14], EntityHorse['Zombie Horse'/32673, l='MpServer', x=-3437.19, y=99.00, z=3327.16], EntityZombiePig['Zombie Pig'/32674, l='MpServer', x=-3432.78, y=38.00, z=3303.17], EntityBabyPigZombie['Zombie'/32675, l='MpServer', x=-3432.78, y=38.14, z=3303.17], EntityMagmaCube['Magma Cube'/32676, l='MpServer', x=-3424.19, y=32.00, z=3328.85], EntityHorse['Skeleton Horse'/32677, l='MpServer', x=-3430.08, y=19.00, z=3425.13], EntityPigZombie['Zombie'/32681, l='MpServer', x=-3432.48, y=60.00, z=3397.80], EntityPigZombie['Zombie'/32682, l='MpServer', x=-3431.50, y=60.88, z=3402.50], EntityZombiePig['Zombie Pig'/32683, l='MpServer', x=-3431.59, y=39.00, z=3391.55], EntityBlaze['Blaze'/32684, l='MpServer', x=-3438.50, y=99.00, z=3365.50], EntityMagmaCube['Magma Cube'/32687, l='MpServer', x=-3412.70, y=32.00, z=3322.67], EntitySkeleton['Skeleton'/32689, l='MpServer', x=-3421.48, y=57.00, z=3402.32], EntitySkeleton['Skeleton'/32690, l='MpServer', x=-3427.35, y=60.00, z=3404.50], EntityMagmaCube['Magma Cube'/32691, l='MpServer', x=-3399.17, y=31.69, z=3341.64], EntityCustomNpc['Netherxile Gate Guard'/32692, l='MpServer', x=-3403.49, y=36.00, z=3329.69], EntityCustomNpc['Netherxile Gate Guard'/32693, l='MpServer', x=-3403.50, y=36.00, z=3335.50], EntityItem['item.item.rottenFlesh'/32694, l='MpServer', x=-3404.11, y=36.00, z=3333.22], EntityItem['item.item.rottenFlesh'/32695, l='MpServer', x=-3404.44, y=36.00, z=3335.36], EntityItem['item.item.goldNugget'/32696, l='MpServer', x=-3402.75, y=36.00, z=3335.89], EntityXPOrb['Experience Orb'/32697, l='MpServer', x=-3405.19, y=35.00, z=3334.32], EntityXPOrb['Experience Orb'/32698, l='MpServer', x=-3403.05, y=36.00, z=3333.54], EntityItem['item.item.goldNugget'/32700, l='MpServer', x=-3374.10, y=36.00, z=3365.42], EntityCustomNpc['Netherxile Ranged Guard'/32701, l='MpServer', x=-3374.50, y=39.50, z=3364.01], EntityCustomNpc['Netherxile Guard'/32702, l='MpServer', x=-3374.49, y=35.00, z=3361.77], EntityHorse['Skeleton Horse'/32703, l='MpServer', x=-3362.99, y=103.00, z=3364.13], EntityPigZombie['Zombie'/32704, l='MpServer', x=-3432.50, y=77.00, z=3306.50], EntityPigZombie['Zombie'/32705, l='MpServer', x=-3425.50, y=77.00, z=3301.50], EntityBlaze['Blaze'/32707, l='MpServer', x=-3442.50, y=101.00, z=3363.50], EntityHorse['Zombie Horse'/32708, l='MpServer', x=-3405.94, y=13.00, z=3432.00], EntityHorse['Zombie Horse'/32709, l='MpServer', x=-3406.96, y=44.00, z=3427.80], EntityPigZombie['Zombie'/32710, l='MpServer', x=-3386.89, y=33.02, z=3387.25], EntitySkeleton['Skeleton'/32711, l='MpServer', x=-3380.50, y=19.00, z=3404.69], EntityPigZombie['Zombie'/32724, l='MpServer', x=-3378.30, y=68.00, z=3288.30], EntityPigZombie['Zombie'/32725, l='MpServer', x=-3398.96, y=33.00, z=3366.88], EntityItem['item.item.rottenFlesh'/32726, l='MpServer', x=-3398.62, y=33.00, z=3368.00], EntityItem['item.item.goldNugget'/32727, l='MpServer', x=-3399.88, y=33.00, z=3368.64], EntityXPOrb['Experience Orb'/32728, l='MpServer', x=-3399.75, y=33.00, z=3368.49], EntityXPOrb['Experience Orb'/32729, l='MpServer', x=-3399.43, y=33.00, z=3369.20], EntityPigZombie['Zombie'/32730, l='MpServer', x=-3399.31, y=33.00, z=3366.07], EntityPigZombie['Zombie'/32731, l='MpServer', x=-3399.90, y=33.00, z=3366.64], EntityHorse['Skeleton Horse'/32732, l='MpServer', x=-3394.01, y=94.00, z=3364.08], EntityMagmaCube['Magma Cube'/32733, l='MpServer', x=-3403.10, y=33.00, z=3341.82], EntityItem['item.item.rottenFlesh'/32734, l='MpServer', x=-3406.29, y=34.00, z=3357.49], EntityCustomNpc['Netherxile Tower Guard'/32735, l='MpServer', x=-3394.93, y=53.50, z=3343.77], EntityPigZombie['Zombie'/32736, l='MpServer', x=-3376.50, y=89.00, z=3342.50], EntityCustomNpc['Honf'/32741, l='MpServer', x=-3365.50, y=26.00, z=3341.50], EntityColoredItemFrame['Colored Item Frame'/32742, l='MpServer', x=-3362.03, y=28.50, z=3340.50], EntityColoredItemFrame['Colored Item Frame'/32743, l='MpServer', x=-3362.03, y=27.50, z=3340.50], EntityColoredItemFrame['Colored Item Frame'/32744, l='MpServer', x=-3362.03, y=28.50, z=3339.50], EntityColoredItemFrame['Colored Item Frame'/32745, l='MpServer', x=-3362.03, y=27.50, z=3339.50], EntityColoredItemFrame['Colored Item Frame'/32746, l='MpServer', x=-3366.97, y=28.50, z=3339.50], EntityColoredItemFrame['Colored Item Frame'/32747, l='MpServer', x=-3366.97, y=28.50, z=3338.50], EntityHorse['Skeleton Horse'/32748, l='MpServer', x=-3372.98, y=47.00, z=3397.96], EntityHorse['Skeleton Horse'/32749, l='MpServer', x=-3371.03, y=48.00, z=3400.10], EntityPigZombie['Zombie'/32750, l='MpServer', x=-3367.50, y=19.00, z=3416.50], EntityHorse['Skeleton Horse'/32751, l='MpServer', x=-3365.41, y=62.88, z=3414.19], EntityHorse['Skeleton Horse'/32752, l='MpServer', x=-3365.04, y=53.00, z=3407.97], EntityBabyPigZombie['Zombie'/32753, l='MpServer', x=-3370.20, y=83.00, z=3293.40], EntitySkeleton['Skeleton'/32754, l='MpServer', x=-3365.31, y=83.00, z=3298.23], EntityBabyBlaze['Baby Blaze'/32755, l='MpServer', x=-3367.50, y=83.00, z=3299.95], EntityPigZombie['Zombie'/32756, l='MpServer', x=-3370.70, y=82.00, z=3308.49], EntitySkeleton['Skeleton'/32757, l='MpServer', x=-3364.44, y=81.00, z=3301.11], EntityHorse['Skeleton Horse'/32766, l='MpServer', x=-3352.64, y=74.00, z=3350.05], EntityZombieChicken['Zombie Chicken'/32767, l='MpServer', x=-3352.49, y=22.00, z=3337.92]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 501805032 bytes (478 MB) / 1947205632 bytes (1857 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 Optifine OptiFine_1.10.2_HD_U_D7 48 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJA	serverpropertieslan{2.4} [Server Properties LAN] (minecraft.jar) 
	UCHIJA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.10.2-1.5.4.jar) 
	UCHIJA	XaeroBetterPvP{1.11.4} [Better PVP Mod] (BetterPvP_1.11.4_Forge_1.10.2.jar) 
	UCHIJA	betterquesting{2.3.217} [Better Questing] (BetterQuesting-2.3.217.jar) 
	UCHIJA	Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
	UCHIJA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJA	JEI{3.14.7.417} [Just Enough Items] (jei_1.10.2-3.14.7.417.jar) 
	UCHIJA	MineTweaker3{3.0.20} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(17mar17).jar) 
	UCHIJA	CustomStuff3{0.11.7} [Custom Stuff 3] (CustomStuff3-1.10.2-0.11.7 .jar) 
	UCHIJA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (Light-Level-Overlay-Reloaded-Mod-1.10.2.jar) 
	UCHIJA	FEI{1.0.17.2} [Forever Enough Items] (ForeverEnoughItems-1.0.17.2-1.10.2.jar) 
	UCHIJA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UCHIJA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.5.1.jar) 
	UCHIJA	gemcraft{1.2.5} [Gem Craft] (gemcraft-1.10.2-1.2.5.jar) 
	UCHIJA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJA	justenoughdimensions{1.3.6} [Just Enough Dimensions] (justenoughdimensions-1.10.2-1.3.6.jar) 
	UCHIJA	levelup{${version}} [Level Up!] (LevelUp!-0.12.9-1.10.2.jar) 
	UCHIJA	mdecore{1.10.2-1.5.1} [MattDahEpic Core] (mdecore-1.10.2-1.5.1.jar) 
	UCHIJA	mtrm{1.2.1.20} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar) 
	UCHIJA	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCHIJA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJA	bq_npc_integration{2.3.19} [NPC Integration] (NPCIntegration-2.3.19.jar) 
	UCHIJA	progression{0.6.9} [Progression] (Progression-1.10.2-0.6.9.jar) 
	UCHIJA	recallstones{0.6.3} [Recall Stones] (RecallStones-1.10.2-0.6.3.jar) 
	UCHIJA	bq_rf{2.3.24} [RF Expansion] (RFExpansion-2.3.24.jar) 
	UCHIJA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCHIJA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJA	spartanshields{1.1b} [Spartan Shields] (SpartanShields-1.10.2-1.1b.jar) 
	UCHIJA	bq_standard{2.3.124} [Standard Expansion] (StandardExpansion-2.3.124.jar) 
	UCHIJA	surge{1.1.0.1} [Surge] (Surge-1.10.2-1.1.0.70.jar) 
	UCHIJA	tellme{0.5.3} [Tell Me] (tellme-1.10.2-0.5.3.jar) 
	UCHIJA	beneath{1.2.0} [The Beneath] (The Beneath-1.10.2-1.2.0.jar) 
	UCHIJA	ToughAsNails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.jar) 
	UCHIJA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	UCHIJA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJA	worldutils{0.2.2} [World Utils] (worldutils-1.10.2-0.2.2.jar) 
	UCHIJA	examplemod{1.0} [examplemod] (WTF-Expedition_1.10.2_v1.5Beta1.jar) 
	UCHIJA	wtfcore{1.10.2_v1.5} [WTFs-Expedition] (WTF-Expedition_1.10.2_v1.5Beta1.jar) 
	UD	mdecore-core{1.0} [MDE Core - ASM Tweaks] (minecraft.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (CustomStuff3-1.10.2-0.11.7 .jar)
  cubex2.cs3.asm.CoreModTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
MDECore-Core (mdecore-1.10.2-1.5.1.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
ServerPropertiesLAN (ServerPropertiesLAN-2.4.jar)
  JaideepSinghHeer.Minecraft.mod.SPLANtransformerPort
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
ProgressionTransformer (Progression-1.10.2-0.6.9.jar)
  joshie.progression.asm.ProgressionTransformer
SurgeLoadingPlugin (Surge-1.10.2-1.1.0.70.jar)
  org.epoxide.surge.asm.SurgeTransformerManager
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor 
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.53
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Funwayguy** [comment]
That has to do with the factions expansion. I have a bunch of things I need to fix with that after Noppes made some changes with how the databases work clientside

**Comment by jordanasch** [comment]
Thanks for the update. Is there anyway I can work around this for now? Is it just the button it self or will it crash if the player tries to claim the reward as well?
