### ISSUE TITLE
Connection Issues with Server

### ISSUE THREAD

**Issue by MaelstromPhx** [Funwayguy/BetterQuesting#2]
Whenever I try to connect to the server I have running with this mod, I get a connection error with this log from the console.

http://pastebin.com/cyTRPcri

**Comment by Funwayguy** [comment]
Seems the last few changes to packet handling before release may have broken the initial serverside sync. I'll have this fixed within the next day or so, thanks for letting me know.

**Comment by Funwayguy** [comment]
This should be fixed as of the last update.
