### ISSUE TITLE
Suggestions: Partys

### ISSUE THREAD

**Issue by EverNife** [Funwayguy/BetterQuesting#201]
Some + configs:

--> Limit the members in partys
--> Disable support of partys in specific quests (like tutorial ones for exemple, or some like acchivements)
--> Entirely disable partys in the server.

**Comment by EverNife** [comment]
I have already asked for this but i felt it was necessary explicit the importance of this config.

In some modpack, quests are an important factor in the server, having a lot of rewards.
In offline mode-servers players can just enter with another account, join a party and have double of all reward.

(can be easily reproduced on online-mode servers too, as there are hundreads of sites that give out free minecraft accounts, https://mcleaks.net/ for exemple)

**Comment by samprit-ghosh** [comment]
Great solve
