### ISSUE TITLE
Rewards not saving all nbt

### ISSUE THREAD

**Issue by EverNife** [Funwayguy/BetterQuesting#202]
The lore of my items doesnt save (just the first line) 

![2017-05-30_22 23 23](https://cloud.githubusercontent.com/assets/11357801/26611773/d8189844-4586-11e7-9360-b9592bf7f520.png)

![2017-05-30_22 23 29](https://cloud.githubusercontent.com/assets/11357801/26611775/dc0296f8-4586-11e7-9bd3-aed8a63d3029.png)

![2017-05-30_22 23 33](https://cloud.githubusercontent.com/assets/11357801/26611777/df49090a-4586-11e7-8f9a-babd55fff21c.png)

Them, when i come back to recheck it:

![2017-05-30_22 23 26](https://cloud.githubusercontent.com/assets/11357801/26611786/f29dea84-4586-11e7-8948-7b14226d871b.png)

**Comment by TheQKnight** [comment]
still having this issue in the latest release. Is a fix coming out any time soon? This issue started like 8 months ago...
