### ISSUE TITLE
Packet Sending - Performance

### ISSUE THREAD

**Issue by Sir-Will** [Funwayguy/BetterQuesting#206]
hey,
can the performance of this be improved?
![](http://i.imgur.com/U52MP7g.jpg)

**Comment by EverNife** [comment]
Just for notice, how many players are online at the same time ?

**Comment by Sir-Will** [comment]
15-25

**Comment by EverNife** [comment]
another question, is this 1.7.10 or 1.10 ?

**Comment by Sir-Will** [comment]
1.10, BetterQuesting-2.3.225

**Comment by EverNife** [comment]
Ha ok. i use 1.7.10 and i didn't see this on my WarmRoast reports. That's the why of the question : V

**Comment by Funwayguy** [comment]
Considering that specific method is what syncs the WHOLE quest database with players, I'd expect it to be pretty costly computationally. That said, I'm not calling it every tick, only when quest states changes. Yes VisualVM is going to say its a costly method but in comparison to the processing time as a whole it isn't affecting the overall stability of the game.

EDIT: On average the amount of data sent is `num_players * database_size` once every 20 ticks

**Comment by Sir-Will** [comment]
Now its already at 7,2% with 10 players online and it shows up every time I'm profiling the server.

What do you mean with quest database? The quest progress or the quests in the quest book?

**Comment by DNx5** [comment]
I noticed this problem make the client use more bandwith (about 400-500kB/s), it just like streaming live video, and the server become not responding for me because my internet can't handle more than that.
here is the packet log I took using Sampler mod
[packets.txt](https://github.com/Funwayguy/BetterQuesting/files/1326268/packets.txt)
