### ISSUE TITLE
Suggestion - Track tamable mobs

### ISSUE THREAD

**Issue by Gamerbolts** [Funwayguy/BetterQuesting#208]
Hi, I was talking with one of my modpack testers and he is writing me a questline for Necromancy. He had asked me about something that isn't in BQ but think it might be good, just not sure if it will work. He was wondering if it were possible to track tamable mobs. As in you give them the item to tame them and it completes the quest. btw I'm using the 1.7.10 version of your mod. Is that at all possible?

**Comment by Funwayguy** [comment]
Closest I can think of is a _Meeting Task_ with the entity of your choice but set the NBT filter to look for the Owner's UUID. Only problem with this is that you can't make that search dynamically match each player UUID. You could try with other NBT filters but it's far from idea for this kind of use.

Currently I'm rewriting BQ for major update 3 so any major features added now would be redundant once it's done. That said, the major update will take some time to complete so don't expect it any time soon

**Comment by Gamerbolts** [comment]
I could attempt that and see how it works. btw I am really enjoying your mod. I have a questline modpack im building with around 80-90 quests. I have like 60 completed so far. Can't wait for the update. Any hints on what is coming in the update?

**Comment by Funwayguy** [comment]
Hints on the new version? Hmm...

- As promised the god awful GUIs are getting ripped up and redone from the ground up. (the ground work is about half done at the moment)
- Tasks/Rewards are most likely being deprecated in favour of a new drag and drop scripting system for almost limitless potential (I might have to invent a scripting language for this... I may be a little crazy)
- Going to be moving away from the whole _HQM Quest Line_ layout, design still pending but may not include the fancy icons with lines between them.
- Possible support for on screen gizmos like active quests, party information, quest markers, etc.

*Note:* Backwards compatibility isn't guaranteed but I'll see if I can make an importer. Also the name of the mod may change

**Comment by Gamerbolts** [comment]
That all sounds really cool. If you can't make it backwards compatible that's fine i'll stick with this version, no way in hell I am redoing all those questlines :) lol Thanks for the news!
