### ISSUE TITLE
NBT tag casting error.

### ISSUE THREAD

**Issue by ArmandAgopian** [Funwayguy/BetterQuesting#21]
There seems to be an issue with the mod though, with comparing the NBT tag of a crafted item and trying to cast it to the list of appropriate NBT tags for that specific quest.

Here is the crash log: https://gist.github.com/AGithub457/443823b7ba4469f9d575f7426e8f6ec9

This happens for the Project Ozone modpack with the Autonomous Activators quest.

**Comment by Funwayguy** [comment]
_facepalm_ I missed a spot it seems. Will be fixed next update

**Comment by Funwayguy** [comment]
This should be fixed in versions 1.0.76 and later
