### ISSUE TITLE
Mobhunt quest, mobs really large

### ISSUE THREAD

**Issue by Gamerbolts** [Funwayguy/BetterQuesting#210]
I am making a quest for divinerpg and orespawn and the mobs are quite on the large side. when I put them in it does this http://imgur.com/a/2S2Eo

**Comment by Gamerbolts** [comment]
Also I was wondering if there was a way to upload pictures to quests? doubt it but thought i'd ask, like showing how to build a multiblock structure.

**Comment by EverNife** [comment]
The default minecraft mob, Ghast itself, do this to the page T.T

**Comment by Gamerbolts** [comment]
Ah, so that means no fix :) lol thats fine

**Comment by EverNife** [comment]
No. there are some workrounds that can be made, like a "size bar" to chage the size of the Mob.

Anyway, i think we will need to wait for this one to be done https://github.com/Funwayguy/BetterQuesting/issues/163

**Comment by Gamerbolts** [comment]
ah yeah. true. I didn't think the GUIs were that terrible though. But looking forward to his next release, just hope its backwards compatible

**Comment by EverNife** [comment]
Me too, as i only use 1.7.10

Else, i dont think that of the GUIs, for me they are good enough
 :D
