### ISSUE TITLE
Party quest issue

### ISSUE THREAD

**Issue by roboapple** [Funwayguy/BetterQuesting#213]
Me and my friend are in a party and we had the throwing knife quest open to the both of us.  He was offline, I finished the quest.  He comes online, and it says the quest is completed for him, but when he opened the quest, it showed some steps as unfinished and would not let him claim the rewards, nor allow him to complete the unfinished steps.

**Comment by EverNife** [comment]
I make a few tests here and it seems to be only a visual error, for me it was showing completed and i could not take the reward.

But then, i tried to detect the item again, and now i could take the reward...
Bug life :D
