### ISSUE TITLE
All quests dones on first join

### ISSUE THREAD

**Issue by EverNife** [Funwayguy/BetterQuesting#216]
It seems that sometimes, some players, on their frist join, get inside an random party.

This means that this random player gets all his quests dones in the first login!

Server Information:

-- Thermos 1.7.10

**Comment by EverNife** [comment]
Its a bit worst than i thought.

To have this bug you just need to invite someone, the quest progress is shared even if the player does not have accepted the party-invitation !

**Comment by Funwayguy** [comment]
Being able to get in a random party isn't entirely a bug. Normal players shouldn't have that happen but operators can add themselves as party admins without invite.

The progress sharing during invite however is a bug. Any particular task type you were testing with?

PS: Normally I would be on top of bug fixing but modding has taken a back bench to other things lately hence the slow replies.

**Comment by EverNife** [comment]
They are almost all Retrieval tasks, with this set of parameters:
![image](https://user-images.githubusercontent.com/11357801/28750662-d6b27b9e-74c7-11e7-9a3e-3ad05b296d96.png)

I i cant say exatly what causes the issue. But if happens again (i reseted all the progress of my players) i will tell ^^

**Comment by EverNife** [comment]
@Funwayguy i got to see that that the  Party Share lives was "true" on the party that was bugging everyone
![image](https://user-images.githubusercontent.com/11357801/29245608-91e57964-7fb5-11e7-8de2-2ae6fef85741.png)

Dont know if it was really related, but was the only party with that enabled... maybe just coincidence :D
