### ISSUE TITLE
SMP Issue Thread (Project Ozone)

### ISSUE THREAD

**Issue by BakermanLP** [Funwayguy/BetterQuesting#22]
Hello (again),
I am playing the modpack ProjectOzone on a server. Last Update (Beta) includes BetterQuesting and there is my problem. After updating to the latest versions I can't claim rewards. I tried the following versions:
- BetterQuesting-1.0.79.jar
- questbook-1.0.1.jar
- StandardExpansion-1.0.48.jar

I can select the additional reward, this ist also shown in the small space. After selecting the additional reward the "Claim Button" seems pressable, but nothing happens.

In single player this works.

Can you help?

Thanks in advance

Michael (aka BakermanLP)

**Comment by Funwayguy** [comment]
I screwed up the choice rewards again it seems. I've sent out a new Standard Expansion build to fix this.

**Comment by BakermanLP** [comment]
Sorry to tell you, but this is only partly done. We are a step further, but not at the end :)  Now, when I claim the reward I got an error on the server and the client disconnects with "A fatal error ...". 

Server error: http://pastebin.com/raw/E21mqPZx

After logging in again and again trying to claim the reward the only two lines in the server log are now:
[08:08:44] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.ArrayIndexOutOfBoundsException
[08:08:44] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel BQ_NET_CHAN
java.lang.ArrayIndexOutOfBoundsException

Used versions in this modpack:
- forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
- fastcraft-1.23.jar
- BetterQuesting-1.0.79.jar
- questbook-1.0.1.jar
- StandardExpansion-1.0.52.jar

**Comment by Funwayguy** [comment]
_cries a little inside_

I wonder why my dev workspace didn't pickup on this. I'll take another look

**Comment by Funwayguy** [comment]
New build pushed to curse
_fingers crossed_

I'll leave this thread open for now knowing my luck recently

**Comment by BakermanLP** [comment]
Finger crossing seems to work :)
First test works just great on server, we will test team questing hopefully today. You'll get feedback from us!

One little message in the server log look ugly:
"Unable to get random loot group! Reason: Total weights <= 0"

Is that a config issue?

**Comment by Funwayguy** [comment]
That's just saying that there are no custom loot groups setup for the chests. I'll change it later to be more descriptive to non-technical users.

Thanks for the testing and bug reports though. With my Uni course in full swing it's difficult to thoroughly test things so this helps heaps. I'm also open to feature suggestions if you or your team think of something potentially handy

**Comment by BakermanLP** [comment]
OK, some issues about server play, do you want a new issue for that?

**Comment by Funwayguy** [comment]
Same thread is fine, I'll just rename it

**Comment by BakermanLP** [comment]
OK, then here are our problems:
- Quest progress is not shared between Party Members
  This seems to be a problem in saving the progress, because in the JSON files on the server the progress is also not saved. We couldn't test the "Shared rewards", because of that issue
- invited party members display in questbook and JSON file
  The members that I have invited, are showing up in the questbook, but only under there uid, not name. The uid to member "array" isn't filled up on the server
- Initial quest sync to party members
  I haven't seen any code, that initial syncs the quest progress to new party members. Also our test showed the same problem. I think, that it would be necessary to do that. In my opinion there are two ways to sync the progress:
- All progress is synced from the party creater to the new party member
- All progress from party creater and new party members are merged

I hope you understand my "problems". English is not my native language.

Michael (aka BakermanLP)

**Comment by Funwayguy** [comment]
Task progress is not currently shared between party members but the completion status should be shared reward claims if enabled (I'll double check this hasn't broken). Due to the dynamic nature of expansions, it will be up to their developers to implement party progression support however I will be updating my expansions to support it soon.

I'll look into the UUID issue with party invites. I haven't done extensive testing in that area due to only being one person but it shouldn't be too difficult to fix this up regardless.

Because party progress sharing has yet to be implemented syncing wasn't implemented either. I plan to have this set up in a way that is balanced and prevent players abusing it to slingshot their progress by leaching off another team.

PS: Don't worry about your English. It's actually better than most native English comments I see on the internet.

**Comment by BakermanLP** [comment]
And don't missunterstand me, that are only the things, what we have tested so long. I knew, that SMP testing is ... how would I say that ... complicated :) We only want to help you out with our observations.

The mod ist, btw, removed from Project Ozone, but I am planing to implement it in a new modpack.

**Comment by Funwayguy** [comment]
After a pretty large update, shared progression should be supported both with questing parties and global quests

PS: There is also a participation cut off option

**Comment by Funwayguy** [comment]
Closing this issue as many of these issues were resolved with the progression split updates
