### ISSUE TITLE
[Question] BQ3

### ISSUE THREAD

**Issue by NielsPilgaard** [Funwayguy/BetterQuesting#229]
Hey!

Will BQ3 be compatible with BQ2? 
I'd like to know if I can start making quests for BQ2, and move them to BQ3 when it's ready.

**Comment by Funwayguy** [comment]
Directly no it won't be. So much has been ripped out and replaced for BQ3 it will practically be a new mod. That said I'm probably going to make some sort of importer for those wishing to transfer over.

**Comment by NielsPilgaard** [comment]
Alright, thank you.
