### ISSUE TITLE
Putting an Ars Magica 2 spell as a reward causes issues

### ISSUE THREAD

**Issue by Not-February** [Funwayguy/BetterQuesting#23]
Disappointing, as custom spell rewards from AM2 were one of my fave things to do with quest mod stuff.

Using the 1.7.10 version, since AM2 currently runs on that.

https://paste.ee/p/HS3Xv

**Comment by Funwayguy** [comment]
I know this is a really late response but I just wanted to clarify the reason for this crash. The JSON format that BetterQuesting currently uses can't easily determine the difference between byte arrays and integer arrays (both are numbers). I still haven't thought of a good way to distinguish the difference without breaking the editors but as soon as I do this problem will be fixed.

**Comment by Funwayguy** [comment]
I think I've finally finish all the necessary changes to NBT save/loading to make this work now.

**Comment by Not-February** [comment]
Sorry to not get back to you before now, I didn't have the chance to test it; however I tried to make a choice reward with two spells just now from AM2 using the most recent 1.7.10 version of BQ, attempting to mouse over them in the interface causes the game to crash.

https://paste.ee/p/fwtgJ
