### ISSUE TITLE
[Question] Loot Chests

### ISSUE THREAD

**Issue by NielsPilgaard** [Funwayguy/BetterQuesting#233]
Hey!

I've been searching around for a while, but I've been unable to find where Loot Chest data is stored, I was hoping you could help me out. If it's stored in JSON format, I'd like to edit the JSON instead of using the Edit Loot Chest.

Minecraft 1.12.1

**Comment by Funwayguy** [comment]
It should be stored in the same directory as the other quest related files (`world_name/betterquesting/`) under the name `QuestLoot.json` however the defaults for new worlds will be loaded from `config/betterquesting/DefaultLoot.json`

**Comment by NielsPilgaard** [comment]
Alright, thank you.

When creating loot chests, is there a certain way to save them? 
`/bq_admin default save`  didn't produce any other files than `DefaultQuests.json`, although I had imported a lot of HQM Loot Bags.

**Comment by NielsPilgaard** [comment]
I found /bqs_loot default save.
