### ISSUE TITLE
Scrolling Glitch

### ISSUE THREAD

**Issue by TyHen** [Funwayguy/BetterQuesting#234]
I have found a glitch that happens to me randomly, but once it happens I can not get it to go away. And to top it off I do not know what has caused it. But the problem is I can not scroll on anything in my quest books. I scroll down and it immediately pushes me back to the top. I can't access any quests that are further than whats on the screen. Would attach somthing, but a picture doesnt help, and no recording software.

**Comment by Funwayguy** [comment]
This usually has to do with repeatable quests and OSS blocks constantly refreshing the quest databases causing weird issues with the GUIs. It's a known bug but unfortunately due to the way the GUIs are structured there is no easy solution, sorry. This is one of the many things I'm rewriting for BQ3

**Comment by hron84** [comment]
@Funwayguy Is there any workaround for this? On Simple Life, I have hard times to reach lower quest lines.
