### ISSUE TITLE
[1.12.1 | 2.5.236] Item rewards not retaining all NBT data. 

### ISSUE THREAD

**Issue by DrSquidMD** [Funwayguy/BetterQuesting#235]
Anytime I put an item with an inventory in as a reward for a quest, when the reward is handed out, everything in the inventory is missing except the last item.

For example, I have a spice of life lunchbag with three different items in it as a quest reward, when I receive it, only the item in the last slot is actually in the bag.

**Comment by EverNife** [comment]
Already reported https://github.com/Funwayguy/BetterQuesting/issues/202

**Comment by Blaxxun75** [comment]
The command /bq_admin edit ends in "unknown command" in my multiplayer map. Single Player works fine.
