### ISSUE TITLE
[1.12.1 | 2.5.236] Commands dont work on multiplayer map

### ISSUE THREAD

**Issue by Blaxxun75** [Funwayguy/BetterQuesting#236]
/bq_admin edit = unknown command in Multiplayer map. But works in Singleplayer.

**Comment by Funwayguy** [comment]
Does the server have the mod installed? Is the server using Sponge (unsupported)?

Either way, the 1.12 version of BQ isn't one I intend to do support for and I did mention that in the release notes.

**Comment by Blaxxun75** [comment]
Hi and thanks for your reply, sorry im not familiar with github so i did not see any release notes.
I run the latest bukkit server.
On the client i have "BetterQuesting-1.12.1.jar" and the "StandardExpansion-2.4.134.jar" in the mods folder.
I use the latest Forge with MC 1.12.1
On the Server side i was not able to find any Better Questing plugins.
Where can i find this server side plugins?
Thank you!

**Comment by Funwayguy** [comment]
Release notes were on CurseForge where the mod is hosted.

The mod is for both Server and Client... I don't think Forge has needed separate client/server mod builds for years.

I should also remind you that this is a Forge mod not built for Bukkit. If that causes issues then there isn't anything I can do for you

**Comment by Blaxxun75** [comment]
So you say i need the BQ mod files only on the server side and the server must be a Forge server?
Thats kinda frustrating, i just switched from forge to bukkit server to be able to use citizens and sentinel...
I guess there is no way then to use citizens with BQ then.

**Comment by Blaxxun75** [comment]
I just read my last comment and it reads somehow weird.
I meant its frustrating that i can not use Better Questing with Citizens and Sentinel because of the different server mods.
Is there a way to combine BQ with Citizens or is there a similar NPC mod that works with BQ?
Thanks!

**Comment by EverNife** [comment]
@Blaxxun75 Suggestion:

Use the mod CustomNPCs

**Comment by Blaxxun75** [comment]
Thanks for the tip, works well with Custom NPCs.
Also the BQ Mod seems to work now on client and server.
Now iam just trying to find out how to start or get a newly made quest. 
How can a player choose a quest and play it???

**Comment by EverNife** [comment]
You need to build your own quests!

Use the command "bq_admin edit" and just create quests for other players to play!

If you wanna pre-made quests, google some famous modpack and copy their quests.
I have made myself about 190 quests, so, its up to you to work a bit ^^

**Comment by Blaxxun75** [comment]
Hi evernife,
I made a simple kill some spiders quest, but i did not know how to start it.
I saw a message "No quests selected"when i looked in the inventory but that was from the Custom NPC mod and not related to BQ.
As i found out now i had to exit bq_admin_edit and then the quest started automatically.
Thanks for your help.
