### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by SirEdvin** [Funwayguy/BetterQuesting#24]
Sorry about this question, but can I upload you mods to my maven repository?
Or, can you create maven repository for mods? 
For example, on https://bintray.com/

**Comment by Funwayguy** [comment]
You can use the deobfuscated jar in your build setup. As long as you're not intentionally distributing the release builds I don't really mind.

PS: I believe that there is a gradle plugin you can use if you want to reference github dependencies
