### ISSUE TITLE
[1.12.1 | 2.5.236] Items with multiple enchantments

### ISSUE THREAD

**Issue by Blaxxun75** [Funwayguy/BetterQuesting#240]
When i give a reward weapon or item with multiple enchantments only the last enchantment stays.
Is this a bug or is this a limitation of the game / better questing mod ?

Thanks!

**Comment by EverNife** [comment]
already report https://github.com/Funwayguy/BetterQuesting/issues/202

**Comment by Blaxxun75** [comment]
Oh sorry.
