### ISSUE TITLE
[Suggestion] remove editmode being stored in questfile

### ISSUE THREAD

**Issue by Thyriel** [Funwayguy/BetterQuesting#248]
Although i'm sure this has been brought up already in all the time the mod is out:
What's the point of editmode true/false being stored inside the quest json (and even worse copied over to DefaultQuests.json with /bq_admin default save) ?
Maybe i'm overseeing something but imho it just adds the risk of forgetting to disable it on delivering a modpack for the little benefit of not having to type /bq_admin edit after starting the game when you're working on quests.
And what's even strange (bug ?) is that when you accidentatly deliver a modpack with editmode still being enabled players in singleplayer worlds without cheat mode enabled neither have editmode in questbook visible nor do they get quest updates as it seems to be internally enabled.

Anyway, i think there would be quite better solutions then the current one, e.g:
- store editmode true / false in betterquesting.cfg. This way it could at least be removed with a bat file or so (guess i'm not the only modpack maker that uses bat files to clean releases for client/server)
- don't store editmode at all. Only downside i see would be that you have to type a command on every restart.

**Comment by ghost** [comment]
I'm also going to vouch for this. Not saving the edit mode in a file would probably be the best solution. typing "bq_admin edit" doesn't take that much effort, and would save all the trouble of forgetting to turn it off and accidentally shipping with it on >.>
