### ISSUE TITLE
Rendering screen crash

### ISSUE THREAD

**Issue by mobehun** [Funwayguy/BetterQuesting#25]
I have been getting these Rendering screen crashes every now and then when I try to add a few new quests. I've already made like 50 other quests.
Crash log: http://pastebin.com/JT8mWZXb
Better Questing 1.1.80
Standard Expansion 1.1.57

**Comment by Funwayguy** [comment]
After doing a major refactoring of base mod's code, this should hopefully not happen now. As of right now I still need to update the Standard Expansion to support some parts of the new system but it may run okay with the old unless you attempt to import anything (old expansion importers are known to crash with 1.x.84+).

**Comment by mobehun** [comment]
I've been doing some "tests" here and there and I've noticed that the crash happens when I do a search in quest. Like I search for new quest and then add one. This might help.

**Comment by Funwayguy** [comment]
It actually has more to do with how I'm accessing/editing the quest database in a lot of places and not so much the UI itself. I've seen it happen in a lot of places such as importing large quest lines in one go

**Comment by mobehun** [comment]
Ah I see, good to know.

**Comment by Funwayguy** [comment]
The newer builds should have this fixed from now onward
