### ISSUE TITLE
Joining a party with quest progress resets quest rewards

### ISSUE THREAD

**Issue by Thyriel** [Funwayguy/BetterQuesting#250]
[1.12.2]
When joining a questparty that has already done quests and claimed the rewards the quest progress is shared with the new party member (which is good) but the quest rewards for all previous party members become reset so they all can claim all the rewards again.

**Comment by Funwayguy** [comment]
Party questing has always had issues with BQ and it's something I need to rip up and redo. Unfortunately there are no short term fixes for this at the moment, sorry.

**Comment by EverNife** [comment]
@Funwayguy can't you add a way to disable partys?

I tried to erase some part of the code but that didnt work well T.T

Just an option ti disable partys will help to prevent these things for now :D
