### ISSUE TITLE
[Suggestion] Add an option to make all quest connection lines appear under the quest symbol, so that we can opt to not have lines on top of quests, which makes stuff rather ugly at times.

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#252]

**Comment by 99Blocks** [comment]
I have just finished up a new chapter in my pack and would love to see this implemented :)
If there is currently a way to do it that I am missing then please let me know!
Excellent work on the mod BTW, enjoying using it for my packs. (Sorry for the post hijack kraft2004, I came here to open the exact same suggestion as you and didn't want to clone issues on github!)

**Comment by Funwayguy** [comment]
See I would but I'm rewriting everything anyway and I'm not even 100% sure if I want to keep that screen and instead opt for something more traditional.
