### ISSUE TITLE
[CurseForge] Not marked as 1.12.2 compatible

### ISSUE THREAD

**Issue by Discomanco** [Funwayguy/BetterQuesting#253]
The mod (and Standard Expansion) is currently not marked as 1.12.2 compatible, which means it doesn't show up in the Twitch app, despite working just fine.

**Comment by AllInMods** [comment]
Check here : https://minecraft.curseforge.com/projects/better-questing/files 

On the Twitch App, choose the version specific to the 1.12.2.
