### ISSUE TITLE
Tasks List is empty!

### ISSUE THREAD

**Issue by rishi-khiroya** [Funwayguy/BetterQuesting#259]
Whenever I try to make a quest on any version, there are no task lists! It worked in a ready-made quest book but not when i make my own

**Comment by KelleyEngineering** [comment]
Silly question. Is Better Questing - Standard expansion installed?

**Comment by rishi-khiroya** [comment]
Ummmmm... Didn't know that was a thing? How do I install it? Is it like a normal mod?

**Comment by EverNife** [comment]
https://minecraft.curseforge.com/projects/better-questing-standard-expansion/files

Choose a Release (Not beta), put into mod's folder and be happy!
