### ISSUE TITLE
Crash during HQM Import

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#26]
A Quest Book user reported issues with his game crashing (Drethic/QuestBook#8).  While reviewing his log file (https://gist.github.com/Dream-Master/6076e110aad8a5527dd8e0ee1d078a9c) I saw several references to PacketQuesting.java which I don't currently leverage.  Based on user response and what the logs (snippets: http://pastebin.com/9hjBWeLb) say the error seems to happen during HQM Imports.

They are using the following mods:
Better Questing 1.0.79
StandardExpansion-1.0.56
questbook-1.1.0
RFExpansion-1.0.5.jar
NPCIntegration-1.0.6.jar
bq_themed-1.0.0.jar

**Comment by Dream-Master** [comment]
I can give your more info if you need some.

**Comment by Dream-Master** [comment]
https://github.com/Drethic/QuestBook/issues/8

**Comment by Funwayguy** [comment]
As of the latest builds, this has been fixed.
