### ISSUE TITLE
Malformed_ QuestProgress.json

### ISSUE THREAD

**Issue by wyndman** [Funwayguy/BetterQuesting#261]
While running a Project Ozone 2.3.0 server, Better Questing version 2.0.230 we've been having a lot of issues with the Quest Progress corrupting and resetting everyone's progress.

It seems that the quest progress file gets to large, then turns into Malformed_QuestProgress.json

**Comment by KelleyEngineering** [comment]
What portion of the file makes you think the file corrupts when it's too big? The QuestProgress file will update itself to match what QuestIDs are in the QuestDatabase.

**Comment by wyndman** [comment]
There actually isn't a section in the malformed quest progress that says
quest_quest settings.  It goes from questProgress right into the quests
themselves. This is Line 2-through 15

 "questProgress": [
    {
      "completed": [
        {
          "uuid": "812e3500-d750-46c8-953e-4414d819274e",
          "timestamp": 494952031,
          "claimed": true
        },
        {
          "uuid": "3ccad429-c9df-43a0-9939-8361c6054b20",
          "timestamp": 494970337,
          "claimed": true
        },
        {
          "uuid": "96340128-e68c-4958-8870-023aa43d8899",
          "timestamp": 498236282,
          "claimed": true

The entire file is 785,343 Lines

**Comment by KelleyEngineering** [comment]
I apologize to you, I misread your original post as Malformed_ QuestDATABASE.json and didn't correct it in time.

My edited question still applies, What error are you seeing in the Malformed Quest Progress file that leads you to believe the file has gotten too large?

**Comment by wyndman** [comment]
It's just a guess, I've kept a few of the older files where it went pear shaped, and seems about the time the file doubles in size it turns into a malformed one. At 5k, then 10k, 19k, then again at 22k there may be other others, those are just the ones I have kept track of.  I thought if this as something like the old HQM issue where it hits too many book open and closes then it just gives up.

**Comment by blackthijs0** [comment]
I am having the exact same issue.
Has a fix for this been found yet?

I tried just completing all the quests with the "/bq_admin complete <quest_id>" command.
However, I realized I had to do more than 400 quests that way it feels like a lot of effort even with commands.

**Comment by ipv2007** [comment]
This problem fixed?

2Funwayguy - fix please!
