### ISSUE TITLE
hidden quest lines [feature request]

### ISSUE THREAD

**Issue by mvdhoning** [Funwayguy/BetterQuesting#263]
It would be nice to be able to hide entire quest lines and only make them visible via an reward.

**Comment by Darkmega18** [comment]
you can actually do this by setting quest "show" setting to hidden or complete. hidden makes it stay hidden even if it's accidentally completed. While complete setting will make the quest appear once the quest is done in order for someone to read the resulting quest description and grab the reward. 

Chain also works in that the quest will only appear when it's requirement quests are appeared. Same with unlocked, which makes it appear anytime the quest is open and ready to be done.
