### ISSUE TITLE
make command block rewards realy hidden [feature request]

### ISSUE THREAD

**Issue by mvdhoning** [Funwayguy/BetterQuesting#264]
Setting a command line reward to be hidden does indeed hide the command line tekst in the 'quest book' for an player.
Somehow i expected it not to even show the command block reward at all. Would that be a possible feature?
E.g. when i auto reward an player an item and announce that via a command block reward it does not make sense in my opinion to show the command block reward as an reward.

**Comment by TheQKnight** [comment]
I would like to see this too.
