### ISSUE TITLE
Crash With BQ and Forestry

### ISSUE THREAD

**Issue by Andvee** [Funwayguy/BetterQuesting#267]
Attempting to make a multiple choice reward, using Forestry Princess bees as reward, and then clicking "done" results in crash.

https://gist.github.com/Andvee/00158410d2fdec0bffebdda6b277ccb6

**Comment by Gamerbolts** [comment]
Same thing is happening with me, any help? 

https://pastebin.com/6CxJf27M

**Comment by Andvee** [comment]
as a work around since giving bees as a reward makes it crash I substituted hives since one can just break the hive open for a princess.

**Comment by Gamerbolts** [comment]
oh yeah that would work. Thanks for the suggestion

**Comment by yujukitten** [comment]
I have the same Issue except I did not even get to hit Done. It also happens with Binnie's Germlings

[crash-2018-01-09_16.52.18-client.txt](https://github.com/Funwayguy/BetterQuesting/files/1617127/crash-2018-01-09_16.52.18-client.txt)
[crash-2018-01-09_17.34.43-client.txt](https://github.com/Funwayguy/BetterQuesting/files/1617128/crash-2018-01-09_17.34.43-client.txt)
