### ISSUE TITLE
Config Title Texture does not accept capital letters

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#27]
I received a report that a user could not use a custom image for their quest GUI (Drethic/QuestBook#9).  After setting everything up how the Wiki (https://github.com/Funwayguy/BetterQuesting/wiki/Resources) says to the image cannot be found.  After some troubleshooting using any capital letters in the folders or image name will cause it to not be found.
Example: S:"Title Texture"=drethic:textures/gui/bq_title.png works, but Drethic:textures/gui/bq_title.png or drethic:textures/gui/BQ_title.png does not work.

**Comment by Funwayguy** [comment]
I'll enable it next update but I'm pretty sure you shouldn't be using caps in a resource path in the first place

**Comment by Drethic** [comment]
I agree with you, maybe just updating the Wiki Example and add a warning that everything needs to be lowercase would be easier.

**Comment by Funwayguy** [comment]
Just went over the resource loader code and it seems lowercase enforcement on the domain name is vanilla and not something I can easily change. I will put a warning up on the wiki page about it

**Comment by Dream-Master** [comment]
ok.
