### ISSUE TITLE
Nei support BQ 2.0 for MC 1.7.10

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#270]
I updated my Pack with Better Questing Mod and addon mods to 2.0 for MC 1.7.10 and can't see any recipes from Inside the Book anymore?
Is this disabled or somewehere hidden?
Is Nei not supported longer?

I am playing GTNH
MC 1.7.10
Forge 1614
Better Questing 2.0.233
Standard Expansion 2.0.130
Questbook 2.1.0
Bloody Quest 1.2.0
and Mods:
https://github.com/GTNewHorizons/NewHorizons

**Comment by alphaest** [comment]
He's talking about this:
https://github.com/Funwayguy/StandardQuestingPack/commit/448ecdb48eb92cd7518acdbd5eb441a22cb349c9

`codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui("item", stacks.get(arg0).stack.getBaseStack());`

**Comment by Dream-Master** [comment]
@Funwayguy

**Comment by richardhendricks** [comment]
Maybe an emergency fix based on code in drawForeground is possible
drawForeground:
https://github.com/Funwayguy/StandardQuestingPack/blob/1.7.10/src/main/java/bq_standard/client/gui/GuiScrollingItemsSmall.java#L144
old NEI support:
https://github.com/Funwayguy/StandardQuestingPack/blob/448ecdb48eb92cd7518acdbd5eb441a22cb349c9/src/main/java/bq_standard/client/gui/GuiScrollingItems.java#L123

**Comment by mitchej123** [comment]
I'm looking through for a proper fix; hoping to have something this evening.

**Comment by richardhendricks** [comment]
okay, will remove from my list.
