### ISSUE TITLE
1.12.2 Tinker's tool's nbt data doesn't save when using in game editor

### ISSUE THREAD

**Issue by TheQKnight** [Funwayguy/BetterQuesting#271]
When I make a tinker's tool and set it as an item requirement to complete a quest in-game, it does not save the nbt data on it. The color of the tip of the tool is white  and it does not have the properties I put on it. It just says "Pickaxe" not the actual name I gave it.

**Comment by tyler489** [comment]
I got around this by using the better questing commands and just /give through console.
