### ISSUE TITLE
Quest book cannot scroll down!!!!PLS HELP

### ISSUE THREAD

**Issue by kokorosss** [Funwayguy/BetterQuesting#274]
HI!

I have some issues in scrolling down with the quest book,

it just keep going up and don't let me click the quest in the bottom,

I just find a lot of site, and can't find any way to fix it.

HELP ME PLS!!!!

**Comment by tomascryogen** [comment]
Hello,
I am having the same issue in Modern Skyblock 2.
The modpack dev closed 2 issues with the reason that its a mod bug.
Please tell me if there is a log I can attach.

**Comment by kokorosss** [comment]
I just turn my gui from large to normal size.......
It fix the bug but it make my gui very small.....
