### ISSUE TITLE
[Question] Hiding quests in a chain

### ISSUE THREAD

**Issue by xXJamieXx** [Funwayguy/BetterQuesting#277]
Hi there!

Just wondered, as I can't find any documentation about it, whether or not you can hide a quest that is in a chain until the previous quest has been completed?

Thanks!

**Comment by Darkmega18** [comment]
I know this one (if you haven't already figured it out). Just set "Show" button to CHAIN or UNLOCKED. then it'll only appear when it's actually open after being reached from a previous quest. you can make it just never show up just as a quest that will complete out of nowhere if someone does certain things with HIDDEN, and you can make it only appear in a similar fashion when it's inadvertently completed using COMPLETED.

**Comment by bashduude** [comment]
doesnt work for me, for some reason :(
