### ISSUE TITLE
[Feature Request] Quest lines and quest available based on permissions nodes

### ISSUE THREAD

**Issue by LJack2k** [Funwayguy/BetterQuesting#278]
I have idea's on making quest lines and quests that are only available to players with certain permission nodes. This would make it possible for servers to create unique quest(lines) for players with different ranks for example. This could be a property of a quest itself or a quest task requirement.

What are your thoughts about this?

**Comment by Steve505** [comment]
Yes, permissions are basic thing on a server. We're actually doing technic server, and this impossibility is limiting us.
Not talking about author's ignorance of this request...

**Comment by Funwayguy** [comment]
I'm not adding support for another mod's permission system. BQ already supports the built in vanilla scoreboards which could be used for this purpose.

People are welcome to create their own integration mods to add more functionality to BQ but I'm not going to be doing that myself. I have more pressing things to manage.
