### ISSUE TITLE
Why when whe add a tinkers item from inventory (NBT) they are not counted in the quest reward ?

### ISSUE THREAD

**Issue by AllInMods** [Funwayguy/BetterQuesting#281]
I Want to have this item in reward in a quest : 
<tconstruct:broadsword>.withTag({StatsOriginal: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 5.0 as float, FreeModifiers: 3, Durability: 236, HarvestLevel: 1, Attack: 3.9 as float}, Stats: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 5

When i add it by clicking it in my inventory, it add a broadsword in iron with a couple of enchantements. (NO NBT)...

How to fix this ?

**Comment by tyler489** [comment]
Duplicate of #271
