### ISSUE TITLE
Entire config file and all quest progress completly deleted.

### ISSUE THREAD

**Issue by TheBillsProject** [Funwayguy/BetterQuesting#282]
Me and my friends are playing Project Ozone Lite and I tend to leave the server on over night. I check the quest book this morning and the entire database for better questing is deleted. This is the 2nd time its happended and Its a pain in the ass recompleteing them via commands as I have to enter over like 120 ids. I would like to know if anyone else is having this issue where your quest data gets deleted. Also would love to know if there is a fix for this anoying problem. 

![image](https://user-images.githubusercontent.com/26034374/34916123-b318e06e-f92a-11e7-806f-bc4005dbd39a.png)

**Comment by Funwayguy** [comment]
Can't remember the name of it off the top of my head but there's an add-on mod that keeps reloading the quests to "keep them up to date" but has issues like this where it fails wiping the whole database and progression with it. Check if something like that is installed

**Comment by Funwayguy** [comment]
Can't remember the name of it off the top of my head but there's an add-on mod that keeps reloading the quests to "keep them up to date" but has issues like this where it fails wiping the whole database and progression with it. Check if something like that is installed
