### ISSUE TITLE
Tasks Don't Show Up In Edit Or Normal Mode!

### ISSUE THREAD

**Issue by tazzanmc** [Funwayguy/BetterQuesting#286]
In the 1.12.2 version of Better Questing, the tasks in edit and normal mode just don't show up!
![2018-01-24_19 07 00](https://user-images.githubusercontent.com/35785712/35363818-00efcd72-013a-11e8-938d-2cf7fa74680d.png)

**Comment by Funwayguy** [comment]
Do you have a compatible Standard Expansion installed? Better Questing by itself is just the base code that all task/reward/theme expansions run on. You need a mod such as Standard Expansion to give you a starter set of content to work with.
