### ISSUE TITLE
[1.12] [BQ3] Retrieval Tasks are worse

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#288]
It seems that in BQ3, retrieval tasks have a better chance of not detecting items without opening the page beforehand than in BQ2. This should be improved.

**Comment by Funwayguy** [comment]
That's odd considering I haven't actually started upgrading that code yet. Edit mode temporarily disables auto detection but even when not in edit mode, the task only updates on set intervals (every 3s if I remember right)

**Comment by TheLimePixel** [comment]
Ok, it seems like this is only an issue when using the old JSON format with BQ3, otherwise it even seems better.
