### ISSUE TITLE
OSS doesn't accept items in 1.12.2 version

### ISSUE THREAD

**Issue by smcnabb** [Funwayguy/BetterQuesting#289]
I noticed that the OSS doesn't seem to be accepting items in the 1.12.2 version.

I was testing with the OSS, a chest of dirt and ExtraUtils transfer pipes. I went back to the 1.7.10 and 1.10.2 versions and the setup works fine there, just in 1.12.2 it no longer works. In the older versions you can see the items go in to the OSS and get consumed but they just don't go in to it in the 1.12.2 version.

I also checked other transfer methods like Thermal Foundation itemducts but none of them worked. I made sure I wasn't in edit mode when testing.

Below is some of the info from my testing. I also tried BetterQuesting-3.5.238.jar in 1.12.2 with the same version of StandardExpansion 2.4.134 but it crashed when I tried to create a retrieval task. I'll file another bug report for that with details.

Minecraft: 1.12.2 - Doesn't work - https://imgur.com/a/QopXV
```
Forge: 14.23.1.2604
Mods:
BetterQuesting-2.5.236.jar
extrautils2-1.12-1.7.3.jar
FTBLib-4.2.5.jar
FTBUtilities-4.2.4.jar
jei_1.12.2-4.8.5.138.jar
StandardExpansion-2.4.134.jar
```

Minecraft: 1.10.2 - Works - https://imgur.com/a/oN9ML
```
Forge: 12.18.3.2511
Mods:
BetterQuesting-2.3.234.jar
compatlayer-1.10-0.3.0.jar
extrautils2-1.10.2-1.7.3.jar
FTBLib-1.1x-3.6.5.jar
FTBUtilities-1.1x-3.6.5.jar
jei_1.10.2-3.14.7.420.jar
StandardExpansion-2.3.131.jar
```

Minecraft: 1.7.10 - Works - https://imgur.com/a/aRhij
```
Forge: 10.13.4.1614
Mods:
BetterQuesting-2.0.233.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
extrautilities-1.2.12.jar
FTBLib-1.7.10-1.0.18.3.jar
FTBUtilities-1.7.10-1.0.18.3.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
StandardExpansion-2.0.130.jar
```

**Comment by Funwayguy** [comment]
Again, you can't use 2.x.x expansions with 3.x.x builds. Please update Standard Expansion before trying again.

**Comment by Funwayguy** [comment]
I don't do support for 2.x.x builds anymore. I've replied to your other issue with why your BQ3 install crashed and how to resolve that. If your issue still persists after updating Standard Expansion to the correct version I'll reopen the issue.

**Comment by smcnabb** [comment]
Ahh I didn't even notice they were two different builds. Ok, I tested with the following and it doesn't work in the latest 3.x.x builds either.

Minecraft: 1.12.2 - 3.x.x builds - Doesn't work  - https://imgur.com/a/wAgup
```
BetterQuesting-3.5.238.jar
extrautils2-1.12-1.7.3.jar
FTBLib-4.2.5.jar
FTBUtilities-4.2.4.jar
jei_1.12.2-4.8.5.138.jar
StandardExpansion-3.4.136.jar
```

**Comment by Funwayguy** [comment]
Are you in edit mode? OSS input is disabled in edit mode to prevent them constantly updating the quest data.

**Comment by smcnabb** [comment]
Nope, I'm not in edit mode. I went back and triple checked.

I also went back to the 1.10.2 test I have and if it's in edit mode the OSS accepts items in to it's inventory slot just doesn't consume them. In 1.12.2 if I switch to edit mode it doesn't even do that. So it's like the OSS isn't being treated as a valid inventory in the 1.12.2 3.x.x version.

**Comment by Funwayguy** [comment]
Very odd. I did test this earlier and it worked fine. Can you post the JSON for the task you're testing with this?

**Comment by smcnabb** [comment]
Hmm that's odd. I can't think of anything I'm doing wrong but it's not out of the question.

Sure: https://gist.github.com/anonymous/cb5fe721818c9d236ed90c25033ec3ae
