### ISSUE TITLE
`Crash 1.9 importing HQM json file

### ISSUE THREAD

**Issue by cauliflower69** [Funwayguy/BetterQuesting#29]
http://pastebin.com/di2426MV

Quest file in question is http://requiemofapickaxe.com/modpack/Aura%20Cascade.json

**Comment by Funwayguy** [comment]
Yes the old importers (not just HQM) don't work with the new changes. I'm working on updating them already

**Comment by cauliflower69** [comment]
Perfect, thanks again

**Comment by Funwayguy** [comment]
The importers should be working again in the newer builds

**Comment by cauliflower69** [comment]
Thanks
