### ISSUE TITLE
Crash when creating a retrieval task with 1.12.2 version

### ISSUE THREAD

**Issue by smcnabb** [Funwayguy/BetterQuesting#290]
When I try to create a retrieval task in the latest 1.12.2 version the game crashes.

It happens when clicking this button: https://imgur.com/a/84FWz

Here's the crash report:  https://gist.github.com/anonymous/487bc2f3be2e845dc27df1ee665a2039

Here's some relevant info:

```
Minecraft: 1.12.2
Forge: 14.23.1.2604
BetterQuesting-3.5.238.jar
extrautils2-1.12-1.7.3.jar
FTBLib-4.2.5.jar
FTBUtilities-4.2.4.jar
jei_1.12.2-4.8.5.138.jar
StandardExpansion-2.4.134.jar
```

I tried with StandardExpansion-3.4.136.jar as well and it doesn't crash but the UI is broken (https://imgur.com/a/HGrSN) which I expected anyway due to your note about that version being for BQ3.

**Comment by Funwayguy** [comment]
You can't use 2.x.x expansions with 3.x.x builds. There is a newer compatible version for [Standard Expansion up on CurseForge](https://minecraft.curseforge.com/projects/better-questing-standard-expansion/files/2523520)

**Comment by smcnabb** [comment]
Ahh cool. Yup, it's fine in 3.x.x, just the UI  isn't right (https://imgur.com/a/HGrSN) but I assume that's because you're mid-dev on 3.x.x and it's easy enough to work around.

**Comment by Funwayguy** [comment]
Yea, booleans are read bytes in the new format and the editors haven't been updated to fully support it just yet but they are planned to be done in the near future. They should still function fine though despite the minor visual difference.
