### ISSUE TITLE
[1.12.2] [BQ3] Randomly Resetting Options

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#294]
So basically I set groupDetect to off on every quests in the JSON. However, whenever I go to the tasks on a quest they sometimes display as 1 and sometimes as 0 without me changing anything. One time even when saving they reverted to 1 again.

**Comment by TheLimePixel** [comment]
If the changelog is correct, I'm guessing that this is fixed now.

**Comment by TheLimePixel** [comment]
Actually, after testing, it seems that it still occurs.

**Comment by Funwayguy** [comment]
Any specific value or the same as the first?

**Comment by TheLimePixel** [comment]
It's the same as the first. The first time I go to edit a task in a quest,  groupDetect is 0, the second time it's 1. And it's not just visual as when I save it, it's 1 in the JSON.
