### ISSUE TITLE
Please support "inventory closed" and/or the better questing keybind for closing the window

### ISSUE THREAD

**Issue by cpw** [Funwayguy/BetterQuesting#296]
https://github.com/Funwayguy/BetterQuesting/blob/8739f6471f65281d8b45110d18dd23b2e0230b20/src/main/java/betterquesting/api/client/gui/GuiScreenThemed.java#L175

Only having escape as an option to close the window is very annoying for left handed players who have rebound everything to the right side of the keyboard.

GuiContainer uses this:
        if (keyCode == 1 || this.mc.gameSettings.keyBindInventory.isActiveAndMatches(keyCode))

You could probably also add in support for the better questing keybind as well:
        if (keyCode == 1 || this.mc.gameSettings.keyBindInventory.isActiveAndMatches(keyCode) || BQ_Keybindings.openQuests.isActiveAndMatches(keyCode))

This would dramatically improve left handed interaction with the book and GUI as a remapped key appropriate for lefty use would work to close the GUI at a specific "saved" place, rather than clicking through to exit.

**Comment by Funwayguy** [comment]
I'll add this to the list of things to do while rewriting BQ3. The GUI class you referenced has actually been deprecated to some extend already so at least I can start making this change early in the replacements.

Here's the new GUI base for reference:
https://github.com/Funwayguy/BetterQuesting/blob/1.12/src/main/java/betterquesting/api2/client/gui/GuiScreenCanvas.java

(the code is quite a mess of new and legacy code at the moment so feel free to judge)
