### ISSUE TITLE
[1.12.2] [BQ3] Randomly Breaking Quests

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#297]
So I thought that this issue was fixed in BQ3, but I was wrong. Basically, there's a chance for quests breaking when using Better Questing commands or when joining a world. The more quests there are, the more often it happens. In my case, I have 1.05k quests and it happens quite often which can be really annoying for people playing the pack.

**Comment by Funwayguy** [comment]
To be fair the current BQ3 builds are a WIP and still runs on a lot of legacy code that still breaks like this. My current focus is the GUIs but I will be replacing the Quest Database code to hopefully something way more stable once that's done. I can only do so much so fast though, I wish I could get it done sooner.
