### ISSUE TITLE
[1.12.2] [BQ3] Quest data still persists in .json file after deleting

### ISSUE THREAD

**Issue by dr3ams** [Funwayguy/BetterQuesting#298]
I imported some quest lines, then deleted couple and noticed that after deleting quests in GUI it doesn't delete it's data from .json file. My .json file is already 8 mb with only 3 quest lines(as I can see in GUI).
I understand that mod is still WIP and just wanted to know is this intended.

**Comment by Funwayguy** [comment]
Sounds like you 'removed' them from the quest line rather than completely deleting them. There are other editors outside the designer where you can find and delete them.
