### ISSUE TITLE
Quest not Notifying when Complete

### ISSUE THREAD

**Issue by Nashonic** [Funwayguy/BetterQuesting#299]
Hello, i currently made a quest book full of quests. I went into a single player world and once i would retrieve the materials needed for a quest it doesn't notify me like it does in project ozone lite. i have to click detect myself then select the rewards or claim reward. In project ozone lite you do not have to detect every quest once you get the items. All you have to do it select the rewards. It auto detects. Why is mine not auto detecting is my question.

**Comment by Funwayguy** [comment]
Are you still in edit mode?

**Comment by Nashonic** [comment]
Does it not take it out of edit mode when you create a new world and make it survival? I make the quests in a separate creative world then i go to a survival world to test them. If that is the case then i guess i just need to take it out of edit.
