### ISSUE TITLE
Incomplete documentation (finish detailed wiki)

### ISSUE THREAD

**Issue by planetguy32** [Funwayguy/BetterQuesting#3]
Much as I'd love to use this mod, I've been unable to find the information I need to do so. How do I open the quest editing GUI? What add-ons are available? Is there some stable API if I want to make an add-on myself? 

Your forum thread and CurseForge page list all the features, but don't seem to say how to use them, and you don't have a Github wiki - have I missed the documentation, or is there not any?

**Comment by Funwayguy** [comment]
The mod is less than a week old. I'm still writing all the documentation and guides

**Comment by planetguy32** [comment]
I'm glad to hear that you're working on it, and thank you for making this mod.

**Comment by Funwayguy** [comment]
Although the mod now has an in game starter guide I'm going to keep this issue thread as a reminder to continue making the more detailed wiki pages.

**Comment by wshadow** [comment]
Is there any documentation on the json format for those of us who like to use an external editor?
Edit: Maybe add a [json-schema](http://json-schema.org/example1.html)?
