### ISSUE TITLE
Updating Screen Event Crash

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#30]
With the newest Version of Better Questing 1.0.8.3 i get this crash when i click on items in NEI.

https://gist.github.com/Dream-Master/aabe7f55df97205deb59da7cab527dd8

**Comment by Dream-Master** [comment]
http://openeye.openmods.info/crashes/ab3dcc8a64bc633c610c5fd5ae5e4fe6

Open eyes says it is standard expansion.

Btw i add all the Quests from my Pack manually maybe that's the reason why it crash. As you said Standard Expansion needs to be updated too.

**Comment by Funwayguy** [comment]
Yes this is a problem with the old expansion in the new version.

**Comment by kindlich** [comment]
Is there a fix in sight or should we downgrade for the time being?

**Comment by Funwayguy** [comment]
I would suggest downgrading for the time being. Someone pointed out a missing set of functions in the last release anyway so I have to do a bunch more work before I can begin to fix this.

**Comment by Dream-Master** [comment]
@Funwayguy 
Any Guess how long you need for an update? I want to say my People on the Server something.
Thanks

**Comment by Funwayguy** [comment]
I was hoping for today but I ran into some unexpected problems which could take some time to resolve. I'm hoping to be done by Monday at the latest.

**Comment by Dream-Master** [comment]
This sounds very good. Thanks for Info.

**Comment by itskun** [comment]
Same problem, waiting for update \o/

**Comment by Funwayguy** [comment]
The base mod update is pretty much done but I might have to release a partial update for SE afterward just to resolve this bug for the time being while I implement new features

**Comment by Funwayguy** [comment]
New build should have this fixed now
