### ISSUE TITLE
[1.12] [BQ3] Parties not Syncing correctly on Bungeecord servers

### ISSUE THREAD

**Issue by EnderCorpsAlpha** [Funwayguy/BetterQuesting#300]
Ok, This is pretty self explanatory in the title, But I might as well explain it:

When we have bungeecord on our Modern skyblock 3 server - which is required as part of our architecture due to us being a large modded network - Party creation isn't saved correctly to the relevant JSON file - So it isn't saving who the owner is or the name - So anyone can join said party and just kick anyone - Which means we can't currently run the pack because of this issue - So basically what I'm asking is if there's a way to get the mod to check for offline UUIDs instead of Online ones? since that could well be a cause

**Comment by Funwayguy** [comment]
Can't really do that. Better Questing actually used offline UUIDs at one point and things broke regularly when they swapped back and forth. There's actually a second file called NameCache which keeps track of names and their associated UUIDs if that has any effect on what your setup.

Might want to double check part of that bug with a non-admin player. Admins actually are _supposed_ to have permissions to join any party and kick users as a means of moderation. On another note, I have plans on changing the way parties work in future to be more MMO esque in how they function.

**Comment by MokahTGS** [comment]
This is not limited to Bungeecord stuff.

We are running a Forge LAN world and parties are not saving correctly as well.  Party Names don't work and it doesn't seem to be saving players to the right place when they go back into the party UI.
