### ISSUE TITLE
[1.12.2] [BQ3] Quest book bookmark option not working when using keybind

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#301]
The bookmark option of the quest book is not working when using the keybind. It always puts me at the "main" page with the logo. Works fine when using the actual quest book item

Hello, I am playing Modern Skyblock 3 (using BetterQuesting-3.5.238.jar) and have this issue. I first assumed it was an issue with the pack (special config or whatever) but it appears not. 
Now I am wondering, is this a feature or a bug of Better Questing 3?

**Comment by Funwayguy** [comment]
Seems when I replaced the homescreen with the new BQ3 code I forgot to include the bookmark shortcut functionality

**Comment by thinkpad4** [comment]
Is there a fix in the works?

**Comment by Funwayguy** [comment]
Yes but the code isn't currently in a releasable state. The quest line screen, or at least components of it, are being rewritten at the moment. There's a couple of other minor fixes I've made so I'm considering restoring the old legacy screen and pushing back the new replacement for another update.

**Comment by thinkpad4** [comment]
Awesome, thanks!

**Comment by Funwayguy** [comment]
Should be fixed as of build 3.5.239

**Comment by predakanga** [comment]
Can confirm, bug is fixed in 3.5.239 (included in Modern Skyblock 3 v3.1.3.4)
