### ISSUE TITLE
Background and texts

### ISSUE THREAD

**Issue by Esmerald1no** [Funwayguy/BetterQuesting#303]
It depends on the modpack, but most of the time I notice that the background is the same color as the font text.But when I went to see a youtuber or a streamer the same modpack, their background isn't the same color as the text.
Is it something that my computer is doing wrong or is it something that I need to change on my mod configs/client?
Thankful For your time,
Esmerald1no

For reference (the first two are from a video and the other two are my game) currently playing "Modern Skyblock 3" :

![1](https://user-images.githubusercontent.com/36509739/36264322-925916a4-1253-11e8-9d1f-f0860cc04f96.jpg)

![2](https://user-images.githubusercontent.com/36509739/36264327-96e7ad7a-1253-11e8-8caf-a3dc29597a9e.jpg)

![2018-02-15_13 38 00](https://user-images.githubusercontent.com/36509739/36265132-b0287b8c-1255-11e8-8a20-1ea6c5b23467.png)

![2018-02-15_13 38 05](https://user-images.githubusercontent.com/36509739/36265258-fca8401e-1255-11e8-9875-943b3de9b03c.png)

**Comment by Funwayguy** [comment]
Strange. Has this been happening all the time? I ask in case some other item, block or gui renderer is leaking.

**Comment by Esmerald1no** [comment]
No, it seems that the issue only occurs while inside the book, but I did notice that in the page to select the themes the preview from the left was normal not the right wasn’t, it was black with “example “ centered in the page

**Comment by Funwayguy** [comment]
That should be the new themes screen and less likely to break. Do you have a screenshot of that too for reference?

**Comment by Esmerald1no** [comment]
sure thing, here it is:
![2018-02-18_22 19 39](https://user-images.githubusercontent.com/36509739/36359470-72bab6dc-14fa-11e8-8c27-69aceb617eba.png)

**Comment by Funwayguy** [comment]
Oh that part is fine and intentional actually. The new BQ3 themes coming later have support for more textured panels so I added a new section to preview one of those, specifically dark themed with white text. Unfortunately BQ2 themes can't use them yet so it's one the few places you can see it.

**Comment by Esmerald1no** [comment]
So there isn’t anything I can do to change the background? Not that is impossible to play that way, it’s just a little bit harder

**Comment by Funwayguy** [comment]
Unfortunately render leaking is fairly difficult to debug partly due to being cause by inter-mod conflicts. These are also the old BQ2 screens that are scheduled to be replaced anyway. Judging by the theme select screen it doesn't affect the new ones anyway so fixing the old ones would be a a waste of time.

**Comment by Esmerald1no** [comment]
Thanks for the help and attention anyway
