### ISSUE TITLE
[1.12.2] [BQ3] [Feature]

### ISSUE THREAD

**Issue by bashduude** [Funwayguy/BetterQuesting#304]
Hi!
I wish there was a possibility to make requirements for quests, but not show any red lines.
Once bunch of quests are unlocked the screen  looks some what messy, because of all visible red lines.

**Comment by Funwayguy** [comment]
Lines are part of the theme system and will eventually be customisable per-quest. Still a long way off from having that functionality in a released build in BQ3 though so don't expect to be able to do so any time soon. BQ3 also has much better control over line rendering and how they actually look so a theme could make them look much more tidy with some effort (textured even).
