### ISSUE TITLE
request: please add shortcut for 'done'

### ISSUE THREAD

**Issue by Spongman** [Funwayguy/BetterQuesting#306]
can you please add a shortcut for 'done'?

in hqm this was right click, and i keep doing this to return up the UI tree.

**Comment by Funwayguy** [comment]
What exactly do you mean by "done"?

**Comment by Spongman** [comment]
![image](https://user-images.githubusercontent.com/1088194/36494917-6785e1a2-16e8-11e8-8903-4a1385069113.png)
