### ISSUE TITLE
[1.12.2] [BQ3] [Requested feature] Can you make it possible for the Quest Link tool can make branches, like on the button image?

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#309]
[Like this](https://i.imgur.com/9TMNLek.png). It could be even cooler if you could just put the corners wherever you wanted, so you could make the lines wrap around other quests instead of going through them [like this](https://i.imgur.com/cVlEQQ1.png). Apologies for the bad MS Paint drawings.

**Comment by aaronhowser1** [comment]
Unrelated, but is there a way for Retrieval quests to complete without having to click the detect button? Right now I have to open the quest, hit the detect button, exit the GUI, then reopen the quest for the quest to update as completed.

**Comment by Funwayguy** [comment]
Custom line renders are already a thing as part of themes but the old BQ2 versions aren't the easiest to write them for:
![javaw_2017-01-02_14-20-06](https://user-images.githubusercontent.com/6048596/36929735-ed87196a-1ee0-11e8-9ad8-cc363f92e159.png)

They can even be animated if someone's willing to put the work in:
![2017-01-12_22-17-36](https://user-images.githubusercontent.com/6048596/36929749-15b9040c-1ee1-11e8-9fdb-d7bb8eed4af2.gif)

Retrieval quests should auto-complete just fine (as long as they aren't set to consume). Just be sure you're not in edit mode before testing that. If it's still not auto-completing let me know.
