### ISSUE TITLE
Forming a party causes an exception on the server and boots the player

### ISSUE THREAD

**Issue by ProsperCraft** [Funwayguy/BetterQuesting#31]
http://pastebin.com/uYFviNiA

Here is a copy of the exception from the console.

The player sees nothing, they just get kicked.

This is on the New Horizons modpack with the latest update that includes this mod.

**Comment by Dream-Master** [comment]
Better Questing Version 1.0.92
Expansion 1.0.65
Quest Book 1.1.0
RF Expansion 1.0.7
Themed 1.0.0

**Comment by Funwayguy** [comment]
Just pushed a new build which should resolve this bug (turns out it also occurred for global tasks)
