### ISSUE TITLE
[Question] Rewards Unclaimed After Update

### ISSUE THREAD

**Issue by TheDistur** [Funwayguy/BetterQuesting#310]
Hi. A pack I'm playing updated from 2 to 3, but now all my rewards are unclaimed again. Is there a quick way to fix that? It's quite a few quests to go through the menus to remove the rewards. Thanks.

**Comment by Funwayguy** [comment]
Having the rewards unclaimed after the upgrade isn't a necessarily a bug. If you go into edit mode and open the quest line designer you can use the force complete tool to click on the quests you've already done.

**Comment by TheDistur** [comment]
Hm okay I wasn't aware of the designer. But now that I've tried that, clicking on the quests with that tool doesn't change anything? They're still blue not green. My quests were still complete after the upgrade, just the rewards came back. Also it's fine if it's not a bug, I just don't know where else to ask. Thanks again.

**Comment by Funwayguy** [comment]
Oh I thought they were completely reset. Odd considering the claim data is stored in the same place as the completion state. That probably is a minor conversion bug. I can try putting in extra functionality in the next BQ3 build for the force complete tool to have a secondary function of removing the pending claim state when clicked a second time.

**Comment by TheDistur** [comment]
Ah. Okay. Thanks!

**Comment by Funwayguy** [comment]
Just sent up build 3.5.240 to Curse Forge for approval. Should have that new functionality in there for you

**Comment by TheDistur** [comment]
Very cool. My quest book is much easier to look at again! Thank you!
