### ISSUE TITLE
Unable to see all quests in tab

### ISSUE THREAD

**Issue by Super5wan** [Funwayguy/BetterQuesting#312]
I have looked for ages trying to find out if there is a post for this issue, and I can't find anything.
When I open a tab in the quest book, I am unable to see all the quests and when I click and drag the window, I can see the end of the quest line, but nothing before it.
I am using the Forever Stranded Lost Souls modpack.
I tried /bq_admin default load, updating Java /bq_admin edit, uninstalling and re-installing, but the problem persists.

Also, I'm getting the bouncy scroll issue that seems to be quite common. Still unaware of a fix,

Edit: Here is a screen shot of all I can see on the "Survival" tab:
![2018-03-04_22 00 31](https://user-images.githubusercontent.com/37051322/36951156-26d521f4-1ff8-11e8-9d44-26d80e0b63db.png)

**Comment by GWSheridan** [comment]
@Super5wan update Better questing to latest version this might help with the GUI scaling for you. It will be updated in the latest version of the pack as well.

Also @Funwayguy Noticed with the newest version of BQ 3.5.240 no matter where I place the quests it will be in the bottom right of the GUI. Does make me scroll out to see must quest but can see the starting quests. Where can I find a GUI theme like on issue https://github.com/Funwayguy/BetterQuesting/issues/309 it looks amazing

**Comment by Funwayguy** [comment]
I'll see what I can do about where the GUI scales to by default next build.

That theme is a WIP custom them being made specifically for TolkienCraft. I haven't even updated it for BQ3 yet.

**Comment by GWSheridan** [comment]
Thanks funwayguy. Ah okay well looks epic done a real good job of the theme
