### ISSUE TITLE
Request: Please add a way to change defualt settings client side.

### ISSUE THREAD

**Issue by owen-pi** [Funwayguy/BetterQuesting#315]
So, its really annoying every time I want to add a retrieval task that I have to change all of the settings like this: 
![x](https://user-images.githubusercontent.com/36006987/37105943-14ef0a5e-21f6-11e8-957f-2ead715ffbda.PNG)
To this:
![x](https://user-images.githubusercontent.com/36006987/37105987-3293d5ee-21f6-11e8-9116-202130f199ec.PNG)
 
So what I mean is, have a way to make those settings automatically like the second image, probably by changing the Better Questing config file. That would shave like 10 secs off of each quest I make, which doesn't seem like much unless you are making like 50 quests a day. Thanks!

**Comment by Funwayguy** [comment]
...or you could just make a template quest and use the copy/paste tool in the designer toolbox
