### ISSUE TITLE
[BQ3] [1.12.2] All quest pages are always open

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#318]
So I wanted to ask whether it's intended that in the new versions of BQ3 every quest page is unlocked from the start, without having an unlocked quest in them. If it's so, is there a way to enable the way it worked in the past?

**Comment by Funwayguy** [comment]
Currently intended because I had some design ideas I wanted to try later. I'll probably change it back in the mean time it's really that big of an issue

**Comment by TheLimePixel** [comment]
Well, many people dislike it and some even thought it was a bug.

**Comment by armuell** [comment]
This still seems to be occurring in v.3.5.244, not a major problem in my opinion but I do prefer a questline to be locked if there are no completable/unlocked quests within it. Also I am using a quest database that was converted from BQ2 if that makes a difference. Screenshots: https://imgur.com/a/j7Tu6

**Comment by Funwayguy** [comment]
@armuell I don't think that case is actually a bug. Quest line button activation functions off what is _visible_ not necessarily unlocked. I believe this was also how it functioned in BQ2 as well.

**Comment by TheLimePixel** [comment]
Nope, all quest pages are unlocked without having anything visible in them. In the previous version it did work as you said, but in the latest version it doesn't.

**Comment by Funwayguy** [comment]
Ooooh I see it now. Yea I screwed up the NULL check in the last update on this line:
https://github.com/Funwayguy/BetterQuesting/blob/1.12/src/main/java/betterquesting/client/gui2/GuiQuestLines.java#L112

(skips the visibility check if the quest exists... which it always should)
