### ISSUE TITLE
[BQ3] {1.12.2] The Scroll Bar Is Broken

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#319]
After the GUI changes, dragging the scroll bar with your cursor does nothing. However you can still use the scroll wheel.

**Comment by Funwayguy** [comment]
Care to actually explain which scrollbar this is?

**Comment by TheLimePixel** [comment]
The one for the quest pages. The ones for the descriptions and tasks seem to be fine

**Comment by Funwayguy** [comment]
Works just fine in testing. Do you even have enough quest lines to make the scrollbar have any 
effect? If you still think it to be a bug can you send a screenshot of what the issue looks like for you.

**Comment by TheLimePixel** [comment]
So I opened the book and selected the second quest page:
![image](https://user-images.githubusercontent.com/25333164/37242705-619b15da-246e-11e8-9103-f34d1d7a2a15.png)
I used the cursor to move the bar down and it's still at the same part of the page list:
![image](https://user-images.githubusercontent.com/25333164/37242715-794cae82-246e-11e8-84e2-8e3b38bf48bd.png)
Even selecting another page doesn't fix it:
![image](https://user-images.githubusercontent.com/25333164/37242718-8aa2921e-246e-11e8-8f69-5b622d886d3d.png)
But using the scroll wheel for a bit does fix it:
![image](https://user-images.githubusercontent.com/25333164/37242736-c03adcce-246e-11e8-8994-1be1f6d6c6c3.png)
For reference, I have 40 quest pages.

**Comment by TheLimePixel** [comment]
Actually, even using the scroll wheel while the cursor is hovering over the grey bar doesn't work. It only works when it's hovering over the quest pages' names.

**Comment by TheLimePixel** [comment]
Ok, it seems to only happen when using the Questbook from the Questbook addon. So should I should probably move this issue there.

**Comment by TheLimePixel** [comment]
Wait... now it doesn't work when using the GUI with the hotkey.... weird....

**Comment by Funwayguy** [comment]
Questbook is probably opening the old legacy GUIs from BQ2. That's why they behave differently.

I'll double check the scroll bar in depth tomorrow.

By the way, can you please just edit your posts as necessary instead of making new ones. You're spamming me with notifications here

**Comment by Drethic** [comment]
I think I found the issue on the Questbook side for opening the legacy GUI, I was still referencing the old GUI for bookmarks. [Source](https://github.com/Drethic/QuestBook/blob/1.12/src/main/java/drethic/questbook/item/ItemQuestBook.java#L48-L53)
I'll get that updated and tested shortly.

**Comment by TheLimePixel** [comment]
Yup, that wasn't it. It's probably a BQ issue, but I hope it at least fixed something else.

**Comment by Funwayguy** [comment]
Recreated it... not particular sure why it worked before but at least its fixed for next release.
