### ISSUE TITLE
Player data storage location, please move it to the world folder.

### ISSUE THREAD

**Issue by ProsperCraft** [Funwayguy/BetterQuesting#32]
From what I understand the player data is stored in the config folder mixed in with the default quest data.

I am begging you from a server owner standpoint to move all data that relates to players to the world folder, I love that it stores in json format, but even HQM had it right where it stored its data in the world folder so it would get backed up with the world backups and be in sync with it.

The most important reason for this is when you update a server you move the configs and mods folder out of the way and replace them with the new configs and mods folder, it isn't supposed to contain any data about the world or players.

**Comment by Funwayguy** [comment]
Your observations are incorrect. The file you're looking at is the global default file for newly created worlds. Existing worlds store all their questing data and progression in the world folder within QuestDatabase.json

If you update the configs with new default quests, the existing worlds and the progress player's have made should not be affected (you will even still have the old quest lines).

**Comment by ProsperCraft** [comment]
Thank you.
