### ISSUE TITLE
[BQ3] [1.12.2] groupDetect is always on on servers

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#321]
So it seems that in the newer versions of BQ3, qroupDetect is always on without it being set to 1 on both of the server and clients. I don't understand why this would start occurring now, when supposedly only GUI changes were made. In every JSON file on the server and the config on the client it's set to 0, yet it's on.

**Comment by Funwayguy** [comment]
Looked into this and it turns out that this bug is specifically to do with that value and isn't what you might think it is. The value inverts itself everytime the quest loads or is edited. Yes it is as dumb as it sounds.

**Comment by TheLimePixel** [comment]
But in the QuestDatabade in the server"s world file it is 0....

**Comment by TheLimePixel** [comment]
Yup, it sure is inverted for servers. Weird...

**Comment by Funwayguy** [comment]
It's not a server specific issue and I've already fixed it in dev but I'm checking if there is anything else that needs fixed first

**Comment by TheLimePixel** [comment]
What about my 2 other new issues? ;)
