### ISSUE TITLE
Invalid Id Error

### ISSUE THREAD

**Issue by MFaik** [Funwayguy/BetterQuesting#325]
whenever I or my friend tries to create a party server replies 
`Recieved a packetbserver side with an invalid ID: betterquesting:party_action` 
and we cant claim rewards either(modpack:GT new horizons)

**Comment by Funwayguy** [comment]
I'm currently only doing support for the BQ3 builds in 1.12.2. GT New Horizons was developed on the older BQ2 code in 1.7.10 so this will likely not get fixed any time soon, sorry.
