### ISSUE TITLE
Quest lines can be opened even if every quest in them is locked

### ISSUE THREAD

**Issue by Insane96** [Funwayguy/BetterQuesting#326]
Before unlocking the right quest
![2018-03-19_11 25 05](https://user-images.githubusercontent.com/7185104/37590334-42892212-2b68-11e8-975e-3e2640927779.png)

After unlocking the right quest
![2018-03-19_11 25 17](https://user-images.githubusercontent.com/7185104/37590350-49344e3e-2b68-11e8-92aa-f79da1dd7c48.png)

**Comment by BrewingCoder** [comment]
this bug was resolved in .243 but I can confirm it has re-appeared in .244 :/

**Comment by Funwayguy** [comment]
I explained why that happened here: https://github.com/Funwayguy/BetterQuesting/issues/318#issuecomment-373988104

I've already fixed it again in dev for the next build but I'm finishing up other code before that goes live.
