### ISSUE TITLE
BQ3 GUI Tooltips Stuck Off Screen

### ISSUE THREAD

**Issue by MokahTGS** [Funwayguy/BetterQuesting#328]
Trying to read the tool tips in the BQ3 GUI when you mouse over them pops up a window that is off screen so you can't see the whole tip.  This is in normal GUI scale mode.

https://www.dropbox.com/s/gtj93m3ckr8cu9g/2018-03-20_14.25.57.png?dl=0

**Comment by Funwayguy** [comment]
This has been reported before. That specific screen has yet to be replaced with a BQ3 GUI and is still running on the old BQ2 code.
