### ISSUE TITLE
Botania slabs spawning when breaking agricraft crop sticks.

### ISSUE THREAD

**Issue by Wigalot** [Funwayguy/BetterQuesting#335]
As title says I'm getting Bosnia slabs spawn when I break agricraft crop sticks in the needle 3.2 patch.

**Comment by Funwayguy** [comment]
Are you sure this is the right mod to report this to? This doesn't sound like it has anything to do with Better Questing

**Comment by Wigalot** [comment]
Uhm, delete/close please. 6am wasnt best time to attempt to report this lol.
