### ISSUE TITLE
Chapter descriptions have scrollwheel even when left empty

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#339]
[Image](https://i.imgur.com/qkTcbvS.png)
[Proof it's empty](https://i.imgur.com/4MoHS6n.png)

**Comment by Funwayguy** [comment]
Not actually a bug. The newer screen panels don't auto-hide their scrollbars any more. I could maybe consider re-adding it if it's that big of a deal to people

**Comment by aaronhowser1** [comment]
I think that would be a good idea, it looks kind of out of place when it's not needed
