### ISSUE TITLE
Update Quest file and default load command reset Players progressions

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#34]
Update Quest file on my Server (in the config folder) and default load command (bq_admin default load) reset Players progressions.

What i can do that this not happend?

**Comment by Funwayguy** [comment]
Better Questing has no way of knowing if the progression data for any particular quest is still valid when you load a new/old database and therefore opts to use only the data from the new quest database, which is usually none, so it can be 100% sure it's valid. I may add in a progression importer (or build it into the command) at a later date that could attempt to merge the two databases together but it would be making a lot of assumptions about which progress belongs to which quest and this can still result in data loss.

Another difficult obstacle is that progression data is stored by the tasks themselves however they see fit and is impossible for Better Questing to know the difference between task settings and user progression data. Before I even attempt to start merging old and new databases I'd need to setup a new set of calls to differentiate settings and progression requiring every existing expansion to update to use.

**Comment by Dream-Master** [comment]
So what is then the best Update strategy. Copy the Quests manually into the existing json file ?

**Comment by McFrugal** [comment]
Isn't the progress still tied to quest ID?  From what I've seen of the structure, each quest has its own section in the file and all progress is contained inside that section.  I don't know how your json interpreter works, but it doesn't sound too difficult to me to retain progress on quests that are unchanged between the two databases.  Quests that are changed and _do_ have progress could still work if the changes aren't significant.  Like, say, if only the text in the quest was changed.  If the tasks are changed I could see that causing problems, but in that case losing progress on that quest is to be expected, isn't it?

**Comment by Funwayguy** [comment]
@McFrugal Yes I was thinking of attempt to merge old task data using the quest IDs and task IDs but there isn't anything to differentiate the progression data and the option data within a task, potentially resulting in the merge changing what the task is supposed to be. The solution I've chosen to go with was what I mentioned at the end of my last comment but it will be a long ways off.

**Comment by Funwayguy** [comment]
I've had some discussions with a pack developer about this problem and we're going to get a system released sometime soon for this with handlers to convert the data over and keep backwards compatibility.

**Comment by Dream-Master** [comment]
Nice.

**Comment by Dream-Master** [comment]
@Funwayguy 
Any idea how long this will takes? Maybe i wait this update before i add thigs manually.

**Comment by Funwayguy** [comment]
First part of this change has been released with backward compatibility included (you should still have a backup just in case) however the Expansions will need to be updated one by one to separate their progression data to support the new system.

Merging of updated quest lines should also be taken care of automatically now but depending on how you change a quest could determine whether or not the progression data will be reset.
