### ISSUE TITLE
Hitting R/U while the cursor is off to the right side (where JEI would be in the inventory) while any BQ GUI is open opens up the JEI recipe GUI

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#340]
For instance, if the cursor is [where the typing indicator is at the top right after the "or"](https://i.imgur.com/xqlVsTE.png) and I hit R or U, it opens up the JEI recipe GUI. Maybe BQ GUIs act like an inventory GUI which opens JEI, but hidden under the book?

**Comment by Funwayguy** [comment]
This sounds like an issue with JEI not BQ. I don't control how JEI handles its keyboard inputs nor what its definitions of an inventory screen is (if that is even a requirement)
