### ISSUE TITLE
[Suggestion] Support/Integration for the Gamestages API for the Loot Chests

### ISSUE THREAD

**Issue by Mad-Gnome** [Funwayguy/BetterQuesting#341]
Allowing us to have an option for different Loot Chest Drops to become available when a player has entered certain game stages would allow pack makers additional customization so the players could not get certain "overpowered/high tech" loot to early on their progress.

**Comment by Funwayguy** [comment]
I've mentioned this to a few people about compatability with `x` mod. I don't add explicit support for other mods but I provide APIs for other people to add it themselves. I have a LOT of code to manage already across the base mod and 3 expansions, I can't support everything.

In terms of restricting Loot Chest content, they already have support for weighted rarity based on their metadata. If you put the rare stuff in the upper range but only provide lower rarity chests until a particular point in the quest line that corresponds to the loot you want, would that not suffice? Or are you specifically wanting separate "rare" loot unlocked per stage?

**Comment by Mad-Gnome** [comment]
Totally understandable with maintaining and updating code with multiple expansions and still supporting different mods; I can only imagine the hours that takes.

I suppose I was looking for a way in a progression pack where I could have 'appropriate' common-rare loot rewards for where they are along the quest line.  Perhaps a condition to see if a particular quest was completed in conjunction with the weight value.

**Comment by Funwayguy** [comment]
I might think about adding NBT tags and allow for chests to pull from set loot categories. This is an idea for way later though when I'm mostly done with the BQ3 rewite.
