### ISSUE TITLE
Default text color is white no matter what theme

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#345]
[This is the quest in 3.5.244 in the Standard Light theme](https://i.imgur.com/kfPd4xt.png), and [in Standard Dark](https://i.imgur.com/6JmQeY4.png). 

[This is the same quest in 3.5.245 in the Standard Light theme](https://i.imgur.com/KEEc30k.png), and [in Standard Dark](https://i.imgur.com/OL5YHnT.png).

[This is what the text editor screen for that quest looks like](https://i.imgur.com/F1X00Mg.png), I even used the reset button to return it to the default font and color.

**Comment by Funwayguy** [comment]
Looks like I forgot to set the theme colour on the text description. I'll send out a build later to fix it
