### ISSUE TITLE
[1.12.2] [BQ3] Weird Page Displaying

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#346]
When clicking on pages that aren't unlocked and then on another page that is, they will be displayed as unlocked. I believe the issue here is that the player shouldn't even be able to click on pages that aren't unlocked.
Here is an explanation with images:
1. Now I'm on the first page. As you can see, everything below it is locked
![image](https://user-images.githubusercontent.com/25333164/38171811-fd1205bc-35a0-11e8-8383-50481c558e1c.png)
2. However, I can click on the second page, of course, with no quests being there.
![image](https://user-images.githubusercontent.com/25333164/38171820-16b80dfe-35a1-11e8-81bf-fc20cc661b8b.png)
3. And then when I go back to the first page, the second one displays as unlocked
![image](https://user-images.githubusercontent.com/25333164/38171824-31c8a7ac-35a1-11e8-83a6-9c8340f29e72.png)
4. When I reopen the book, it's back to normal
![image](https://user-images.githubusercontent.com/25333164/38171828-42adebfe-35a1-11e8-8e2e-9aaff8189d2c.png)

**Comment by Funwayguy** [comment]
Fudge cakes. Seems I broke buttons and the "disabled" ones still work. You can even open locked quests you shouldn't be able to access among other things. I'll try and get a fix out ASAP
