### ISSUE TITLE
Quests rearranged themselves

### ISSUE THREAD

**Issue by McFrugal** [Funwayguy/BetterQuesting#35]
http://i.imgur.com/AYONrnP.png

This is not how these quests were arranged before.  I was not in edit mode or anything.  I completed one of the quests, then came back to the questbook and suddenly it was all rearranged like this.  Only this chapter was affected.

A few minutes before this I tried to click on a quest and some kind of green line showed up attached to my cursor, like it was trying to let me link the quest to another one.

Could it have something to do with double-clicking at the wrong time?  My mouse is dying so it sometimes double-clicks on a single click.

**Comment by Funwayguy** [comment]
It appears you managed to click on the UI editor controls and auto-arrange the quest line. Not sure how because those controls should be locked out from users not in edit mode.

**Comment by Dream-Master** [comment]
Yes i got this error to today too. Click on a quest in a non edit mode and it rearraged all Quests from one chapter.

**Comment by McFrugal** [comment]
I figured out why this happens.  Yes, the buttons are invisible... but you can still click them.

**Comment by Funwayguy** [comment]
Yep, found that too. I have it fixed in my dev environment for next release.
