### ISSUE TITLE
[1.12.2][BQ3] isMain doesn't save properly

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#350]
When you have main quests, do /bq_admin default save and then /bq_admin default load, they aren't main anymore. I'm guessing it doesn't save properly.

**Comment by Funwayguy** [comment]
One day I'll get booleans to stop breaking... one day.

Currently 11pm here so I can't test this till tomorrow. Feel free to dig around in the `DefaultQuests.json` in the mean time if you want to check the variables there

**Comment by TheLimePixel** [comment]
Well, it broke in the latest version, so you technically had fixed them, but they are broken again.

**Comment by Funwayguy** [comment]
I'm not sure if this makes me feel better or worse...

I guess it's par for the course with this old code. Fix one thing, break another somehow.

I have an idea of where this could be happening though so it's not all bad news, at least not yet.

**Comment by TheLimePixel** [comment]
Actually, it's for everything. Everything gets set to 0 when loading >_< In the file everything looks fine though.

**Comment by Funwayguy** [comment]
Didn't even have to test it and I found where it broke in the code. Going to send an update out to fix it but oh boy this could get messy depending on how many people saved files with the old version.

The last fix solved the boolean corruption on the loading side however this corruption is on the saving side and also wouldn't have happened until the previous fix was made making the edge case a possibility here too. Worse still, it's not specific to the saving of defaults either. Everything is screwed when reloading the world. I'm going to get so many complaints now... Thanks for the report though, at least it's contained to one build.

**Comment by TheLimePixel** [comment]
Yeah, redoing ignoreNBT is gonna be fun... (by redoing I mean replacing everywhere that it's 0 to 1 and then going over the quests that need it to be 0).

**Comment by Funwayguy** [comment]
Do you have a backup by chance? Contemplating whether it's worth forcing backups when version numbers change.

**Comment by TheLimePixel** [comment]
Well technically it's the last version of the pack on CF, but I've made too many changes to go back.

**Comment by Funwayguy** [comment]
Fixed build is now up on Curse Forge pending review. I hope that this is the last of the issues with the major data corruption issues. A total of 1,870 people were affected by the previous build which isn't great but it could have been so much worse if it were a mainstream build.

Note: I like how it was almost like I knew this was coming with my earlier comment "it's not all bad news, at least not yet".

**Comment by Funwayguy** [comment]
Actually I'm going to archive build 249 for a bit until I'm sure it works properly. There are a couple of edge cases I need to test.

EDIT: Sent out build 250 last night because I found another possible edge case to fix
