### ISSUE TITLE
Mob Hunt Quests broken

### ISSUE THREAD

**Issue by Awec4** [Funwayguy/BetterQuesting#351]
So yeah Mob Hunt quests don't detect you killing mobs any more. Every other quest detects fine as far as I can tell.
Also I've checked and this has still happened even after I made new mob hunt quests, saved the questbook and turned edit mode off.

**Comment by Awec4** [comment]
Also NBT tags don't save properly as every time I save and load any quest I have that refers to the Mob Charms added by Reliquary revert to the Zombie charm.
And lastly, I just loaded a saved game and it seems it didn't save which quests I had claimed rewards for.

**Comment by asphaltbuffet** [comment]
Any information on this? Mine seem to be hit or miss. Zombie kills only register a quarter of the time.

**Comment by remclave** [comment]
I would like to add my input to this issue as well in order to follow up. This issue is still not working. 

I am using jar version 274.

**Comment by asphaltbuffet** [comment]
Was this resolved by a fix or just closed?

**Comment by Funwayguy** [comment]
This was just an old issue I closed but I have tested in more recent builds and can't find anything immediately broken with the hunt task's setup or kill tracking.
