### ISSUE TITLE
"Hold SHIFT for advanced info" missing

### ISSUE THREAD

**Issue by MirrorImageQS** [Funwayguy/BetterQuesting#352]
As of v240 (released on 3/4/18 on Twitch App - BetterQuesting-3.5.240.jar), the "Hold SHIFT for advanced info" message and the advanced info preview when hovering over a quest is missing. This complicates the ability to use the "/bg_admin complete" command since there is no other apparent way in-game to view the quest ID.

Also confirmed that this is still an issue as of v248.

**Comment by Funwayguy** [comment]
I moved it to be part of Minecraft's built in advanced tooltips. You can turn that on with F3+H

**Comment by MirrorImageQS** [comment]
Aha! And so they are. I wasn't aware of that functionality. Thanks

**Comment by Funwayguy** [comment]
There are a bunch of small changes I'm making here and there to consolidate the editing process but I'll try documenting it after I'm done witg BQ3.

Minecraft's built in tooltips themselves are pretty useful to the point where I usually have them on during normal gameplay so I can see precise durability numbers among other misc stats.
