### ISSUE TITLE
QuestID not showing

### ISSUE THREAD

**Issue by GreatestFool** [Funwayguy/BetterQuesting#353]
I'm not sure if this is something that can change or not, but at least in the previous version I played with it was possible to have extended information while holding shift, showing the quest ID and such. Now I can't see it. Is there a command or config option I have to change?

**Comment by Funwayguy** [comment]
Refer to issue #352 for what I changed, why I changed it and how to make these tooltips show again.

**Comment by GreatestFool** [comment]
Oh, sorry for the annoyance then. Thanks for answering.
