### ISSUE TITLE
Quest progress reset

### ISSUE THREAD

**Issue by GreatestFool** [Funwayguy/BetterQuesting#354]
This might just be something else entirely, In the pack I'm playing in, this was updated from BQ 3.5.239 and BQ:SE 3.4.138 to BQ 3.5.248 and BQ:SE 3.4.141. When the update was completed I noticed my progress was reset. The quests were still completed, but the loot wasn't claimed. I searched around for a bit but I couldn't find a fix that worked for me.

How does one fix this? Is there a way other than manually completing quests using questid?

**Comment by Funwayguy** [comment]
Oh no... I have some bad news.

You may notice that build 248 isn't on Curse Forge anymore. That's because it had a major data corruption issue (worse than the one it was meant to fix). Sorry to tell you but all the `true/false` property states in both the quest line and progression have all been reset to `false`. You may want to load a backup if you have one. Build 250 is the fixed version which I've tested thoroughly.

PS: Loving that account icon

**Comment by GreatestFool** [comment]
Oh man, the more you know. Well that explains it! Thanks for the help. Also, there doesn't happen to be a way to claim quests with a command? It's pretty easy to just claim them and dump the loot in in lava when stuff like progress reset happens, but it would be nice.

You have a pretty cool account icon yourself! May I ask where it is from?

**Comment by Funwayguy** [comment]
In edit mode if you open up the quest line designer screen you can use the force complete tool to reset the claim state by clicking a second time. This however wont fix the other damage 248 causes. My suggestion would be to manually replace your `QuestDatabase.json` with the default in the configs, keeping the progression file the same. Then go back and fix the claim states from there. Backup before trying this though.

My account icon is Ernesti Echevalier from Knights & Magic. It's an isekai anime with a programmer main character (Ernesti) obsessed with building mechs.

**Comment by GreatestFool** [comment]
So even if everything _seems_ to be in working order, it might not be? I've deleted the `QuestDatabase.json`. Everything seems to be working, and my friend and I haven't noticed any problems since we've updated. Eh, hopefully it'll continue to work.

The anime sounds cool, I'll make sure to check it out. Thanks.

Thank you for all the help though, I really appreciate it!

**Comment by Funwayguy** [comment]
No problem. If you run into more issues, or just want to talk anime, you can message me on Discord at `Funwayguy#1405`. Quicker and easier to respond than GitHub.

**Comment by Bircko** [comment]
if you want to set everything on claimed just go in QuestProgress.json and search for "claimed:1": 0 and replace it with "claimed:1": 1

**Comment by Funwayguy** [comment]
@bircko I'd rather people who are not familiar with JSON formating use ingame methods for setting this. It also allows people to leave the legitimate unclaimed states untouched.
