### ISSUE TITLE
Loot Chest Weighting Understanding

### ISSUE THREAD

**Issue by D3nnis3n** [Funwayguy/BetterQuesting#356]
Hello together,
seems i do not quite get how the weighting works.

I got five groups:
- Common (40)
- Uncommon (30)
- Rare (15)
- Epic (7)
- Legendary (1)

I want the five different chests to include
- 0%: Only Common
- 25%: Common and Uncommon (But Common should be a little bit less rare than Uncommon)
- 50%: Uncommon and Rare (But Uncommon should be less rare than Rare)
- 75%: Rare and Epic (But Rare should be quite less rare than Epic)
- 100%: Epic and Legendary (But Epic should be much less rare than Legendary)

I cannot seem to get this to work. Maybe someone has an idea how i can achieve what i want or if it is possible at all? When i managed to get things much rarer than the other things, they suddenly appear in chests where they should not, because they fall out of the rarity bracket or get into it. E.g. when legendary is 1% and epic 10%, but rare is 20% it will also be in the 100% chest, which it shouldnt.

**Comment by Funwayguy** [comment]
You can think of weighting as tickets in a raffle. The chance of a category being chosen at random is
`own weight / all weights`
So for your set of weights your legendary category has a chance of `1 / 93 = ~1.08%` chance of being chosen at true random.

The chests however have their own weighting bias (unless you do use the true random chest) with about 25% random range. So if you had an even 100 tickets (representing the category weights ordered from common to rare) where 100 is the rarest and 1 is the most common. The lowest tier of chest would only be able to draw tickets `0-25` where the legendary chests would be able to always pull `75` or higher.

Random weighting, especially with bias, is a little hard to explain so I might need to include an info graphic to the editor sometime in the future.

**Comment by MrsRatbag** [comment]
I'm Having the same issue, no matter what i can't seem to get the rarity to be what i want. Instead of selecting the weight wouldn't it be better to just choose the rarity of each loot set so that it goes into the chest we want it to go into?
