### ISSUE TITLE
Quests buttons do not fill container width

### ISSUE THREAD

**Issue by Insane96** [Funwayguy/BetterQuesting#357]
![2018-04-09_09 01 39](https://user-images.githubusercontent.com/7185104/38483901-dfdc01de-3bd4-11e8-8a8e-abee09c413fb.png)

**Comment by Funwayguy** [comment]
That's just where the scrollbar shows up when needed... which someone else requested to hide when not required.

**Comment by Insane96** [comment]
Wouldn't be possible to increase the whole container size? In the latest updates, buttons feel so small.
