### ISSUE TITLE
Format errors on quest descriptions

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#359]
My quest's description has "[Format error:](https://i.imgur.com/cvYqYNi.png)" at the start and I don't know why. [This](https://i.imgur.com/vvgv77K.png) is what the Text Editor looks like, and this is what the description line is in the DefaultQuests.json:

`          "desc:8": "Dark Matter makes up approximately 80% of the known universe. You would think it would suck everything into it like a black hole, but apparently not.\n\nDark Matter is a major crafting component in ProjectE items and blocks. The Charcoal Logs are found on the Lava world."`

I assume that the "\n"s are new lines, but I don't see what would give a format error. The whole quest in the json is this:

```
"179:10": {
      "questID:3": 179,
      "preRequisites:11": [
        168
      ],
      "properties:10": {
        "betterquesting:10": {
          "issilent:1": 0,
          "snd_complete:8": "minecraft:entity.player.levelup",
          "lockedprogress:1": 0,
          "tasklogic:8": "AND",
          "repeattime:3": -1,
          "visibility:8": "ALWAYS",
          "simultaneous:1": 0,
          "icon:10": {
            "id:8": "projecte:item.pe_matter",
            "Count:3": 1,
            "Damage:2": 0,
            "OreDict:8": ""
          },
          "globalshare:1": 0,
          "questlogic:8": "AND",
          "partysinglereward:1": 0,
          "snd_update:8": "minecraft:entity.player.levelup",
          "autoclaim:1": 0,
          "ismain:1": 0,
          "name:8": "Oddly Squishy",
          "desc:8": "Dark Matter makes up approximately 80% of the known universe. You would think it would suck everything into it like a black hole, but apparently not.\n\nDark Matter is a major crafting component in ProjectE items and blocks. The Charcoal Logs are found on the Lava world."
        }
      },
      "tasks:9": {
        "0:10": {
          "partialMatch:1": 1,
          "autoConsume:1": 0,
          "groupDetect:1": 0,
          "ignoreNBT:1": 1,
          "index:3": 0,
          "consume:1": 0,
          "requiredItems:9": {
            "0:10": {
              "id:8": "projecte:item.pe_matter",
              "Count:3": 1,
              "OreDict:8": "",
              "Damage:3": 0
            }
          },
          "taskID:8": "bq_standard:retrieval"
        }
      },
      "rewards:9": {}
    },
```

**Comment by Funwayguy** [comment]
The format error isn't actually something that Better Questing does directly. Minecraft's localisation function doesn't take kindly to `%` symbols unless I manually check for valid translations before hand. If I forget to check, this happens and it modifies the text rather than returning the original text as it normally would and of course all of this is done silently without throwing an error. Thankfully this is only a visual bug and won't affect the database files at all so no worries there. I'll try and get a fix out sometime soon but I'm still in the middle of replacing another GUI screen so I make no ETA on that.

**Comment by aaronhowser1** [comment]
Oh I never would have guessed that it was the % sign doing it. I'll just replace it with the word "percent" instead, thanks

**Comment by WesCook** [comment]
See #105 for another workaround (and this can probably be closed as a dupe).

**Comment by Funwayguy** [comment]
_looks at age of issue_

Wow... I really need to do some clean up on this repo's issue threads.
