### ISSUE TITLE
No Quest Access If Locked

### ISSUE THREAD

**Issue by Boolyman** [Funwayguy/BetterQuesting#362]
The changelog on curse hasn't been edited in the last half dozen or so updates, so I'm not sure if this has been tweaked or addressed, but it used to be that quests and quest pages which had requirements which were not met yet, could not be viewed or clicked on.  Nowadays everyone can click and seemingly complete any quest, in any order, and it's becoming quite confusing for some users.  Any plans on reverting this to the original format?

**Comment by Funwayguy** [comment]
I fixed this a few versions ago, build 247 to be exact. Just tested it in build 252 and it _still_ doesn't happen.

Oh and yes, this was in the change logs:
![](https://puu.sh/A7Eyx/1f085a7fa2.png)

**Comment by Boolyman** [comment]
The changelog on curseforge _still_ hasn't reflected any changes.,. which is what curse launcher shows when users click on the changelog.  Just offering a heads up.

**Comment by Funwayguy** [comment]
Unfortunately there isn't anything I can do about that. I don't entirely control which changelogs Curse does and doesn't show on the launcher. This probably has to do with all 1.12.2 builds being marked as beta.

Either way, bug was already fixed.
