### ISSUE TITLE
Repeatable quests with choice rewards are borked

### ISSUE THREAD

**Issue by Landstryder** [Funwayguy/BetterQuesting#363]
I have a number of repeatable quests I'm trying to use in my pack Atom Smasher as part of an economic system, but I'm having a number of issues with them....

- Once they are initial unlocked and turned in once they will continuously ding and notify on the screen there completion status even if you only turned them in once and don't have the material to turn them in again (I've disable the notification to alleviate the annoyance but it's only a band-aid on the underlying issue)
- When you try to turn them in the claim button flashes for just a moment when making a selection but by the time you move the mouse to the button it has greyed out and no longer clickable (if your SUPER fast you can actually claim the reward but it literally milia seconds)
- When selecting a reward in the repeatable quests the icon does not show in the selection box at all

I've also had issue with all the quest progress resetting every time the server goes through a restart, I think this maybe due to having updated to v248 at one point... I would really hate to have to rebuild my quests... is there a way to maybe fix them by editing the .json (not a big issue for me I've gotten use to editing .json files now if there is some easy way to clean up the DefaultQuest.json)

Thanks in advance for any help with these issues and keep up the good works

**Comment by Funwayguy** [comment]
If you saved any quest edits with build v248, especially in the `DefaultQuests.json` there is very little I can do to undo the garbage data. Normally if you have an intact `DefaultQuests.json` from _before_ v248 you can at least reload from there and manually fix the completion states after updating to v250 or newer.

If you encounter this issue after updating to v252 and with a known working `QuestDatabase.json` then let me know and I'll look into it further.

**Comment by Landstryder** [comment]
Just to clarify the repeatable quest were doing that in version 245 and are still doing that even after deleting them and remaking them in 253

It was only the progress resets that I was asking about from v248
