### ISSUE TITLE
Game crashes when choosing a task

### ISSUE THREAD

**Issue by EmpLife** [Funwayguy/BetterQuesting#365]
Hi, My game always keeps crashing whenever i try choosing a task, is there any way to fix this?
Crash report:

> The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.AbstractMethodError: bq_standard.tasks.TaskCrafting.writeToJson(Lcom/google/gson/JsonElement;Lbetterquesting/api/enums/EnumSaveType;)Lcom/google/gson/JsonElement;

**Comment by Funwayguy** [comment]
Do you have the _full_ crash log?

Just a guess but are you using the right expansion version for the BQ base mod? (3.x.x builds are only compatible with 3.x.x expansions)

**Comment by EmpLife** [comment]
I do, actually. But i did remove some mods that i felt were pretty lackluster and it kinda fixed it.
