### ISSUE TITLE
crafting quests dont work at all

### ISSUE THREAD

**Issue by redgoblin88** [Funwayguy/BetterQuesting#367]
any and all quests that i make that are crafting related (logs into planks, tinkers construct stations, vanilla crafting table, vanilla furnace, modded 2x2 axe recipe e.c.t.) are not working what so ever regardless of partial match and/or NBT detection.

forge version: 14.23.2.2654
better questing version: 3.5.251

quest database (where all the questing data is stored):
https://pastebin.com/6S87CGgM

note that i HAVE tried the latest version of 3.5.253 but for some reason that is crashing me:
https://pastebin.com/Ku7mnJNg

**Comment by Bullorg74** [comment]
Are you in edit mode? Wont work in edit mode you need to got bq_admin edit false to test your quests.

**Comment by redgoblin88** [comment]
i am in edit mode but wont that be counter-productive switching back and forth from edit mode to "playing" and how does that work? why specifically for crafting detection? others such as checkbox and retrieval works perfectly fine?

**Comment by Bullorg74** [comment]
No clue to why it is like that but it is. So make your crafting detection stuff. Go out of edit to test them. Thats how the mod works.

**Comment by Funwayguy** [comment]
It's like that because having quests running and changing their states and data mid edit causes more issues than it's worth.

That crash you got is a new one. Don't think I've seen that before so I'll see what caused that

**Comment by Funwayguy** [comment]
Turns out that crash is caused by double right clicking while using the scaling tool. Forgot to reset an ID value of the selected quest when cancelling the selection (right click) and it has a panic attack when it attempts to cancel it a second time.

**Comment by redgoblin88** [comment]
yeah regarding that crash, i saw that single clicking shrinks them but was confused how to make them bigger so i tried all sorts of ways in a fast paced way,i ncluding doubble clicking
