### ISSUE TITLE
Can't change the name of a party and can't have multiple parties on a server

### ISSUE THREAD

**Issue by Dhrekkin** [Funwayguy/BetterQuesting#369]
I was hoping to use this as a cornerstone mod on my server, but during playtesting we discovered that it seems to lack the ability to have multiple parties on a server.  I, as the op, can add people to *my* party, but no one else can form a party.  I also seem to lack the ability to rename the party after I invite someone.  Is there some kind of config or permission I'm just overlooking?

**Comment by Funwayguy** [comment]
Hosting multiple parties seems to work fine as of build 254:
![](https://puu.sh/Af8Jm/7d7cdabe3e.png)

Same goes for inviting and renaming:
![](https://puu.sh/Af8KZ/ca75b19cef.png)

What version of Better Questing are you using?
