### ISSUE TITLE
Quarter hearts stack into full hearts

### ISSUE THREAD

**Issue by McFrugal** [Funwayguy/BetterQuesting#37]
If you have a full heart "Extra Life" in a chest, then shift-click a quarter heart into it, it stacks with the full heart.  So it turns the quarter heart into a full heart.  This also happens if you give yourself more quarter hearts via NEI- they stack with any full hearts present in your inventory.

**Comment by Funwayguy** [comment]
Seems I made an oversight (which isn't present in 1.8.9 or 1.9 builds). Will have this fixed next update
