### ISSUE TITLE
When text takes up a whole page and needs a scroll bar, the text disappears 

### ISSUE THREAD

**Issue by TheQKnight** [Funwayguy/BetterQuesting#370]
Like the subject says, on the latest version the text in descriptions will disappear if it is longer than the page its on and has a scroll bar next to it.

**Comment by Funwayguy** [comment]
This happens when a there's an error in the line numbers (the console log is probably filling with errors). I know this issue exists but I haven't been able to reproduce it in development. Do you have the raw JSON of the description breaking it?

**Comment by TheQKnight** [comment]
Yeah, but its long. Won't even let me pastebin it. The only version it works with is 251

**Comment by Funwayguy** [comment]
I only need the text description, not the whole database file. (if that's still somehow too big kist zip it and send it as a file)

**Comment by TheQKnight** [comment]
here is the file.
[Quests.zip](https://github.com/Funwayguy/BetterQuesting/files/1959773/Quests.zip)

**Comment by TheQKnight** [comment]
if you load up a world with it and look at the first lore quest, the text does not show. You can verify there is text there by editing it.

**Comment by Funwayguy** [comment]
Thanks, I'll take a look at it later today and run some debug tests on it.

**Comment by Funwayguy** [comment]
Just confirming I can recreate it with these quests. Thanks. Should help getting this bug narrowed down andfixed as soon as possible.

**Comment by Funwayguy** [comment]
Closing issue. Fixed as of build 254
