### ISSUE TITLE
While edit mode is enabled, we should be able to open locked quests directly instead of having to go into the edit window

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#371]
By that I mean we should be able to open quests from [here](https://i.imgur.com/8Hx6gJi.png) instead of having to go through [here](https://i.imgur.com/2oKWEyz.png). It would also be much nicer if we still go back to the last quest we opened even if its locked.

**Comment by Funwayguy** [comment]
What version of Better Questing are you using? That was fixed in build 252

**Comment by aaronhowser1** [comment]
I was using BetterQuesting-3.5.252. I updated to BetterQuesting-3.5.254 just now and it works now
