### ISSUE TITLE
[BQ3] [1.12.2] The large textbox is unusable

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#375]
I'm not sure whether this is a bug or simply not implemented yet, but the large textbox doesn't display the text from the description although there is an amount of space equivalent to that of the text from it. Adding or removing letters (although they aren't displayed) doesn't affect the actual description either.
![image](https://user-images.githubusercontent.com/25333164/39575856-586ad066-4edc-11e8-91ac-870f5f3c3475.png)
![image](https://user-images.githubusercontent.com/25333164/39575860-5da1bca2-4edc-11e8-96db-8f4453d32653.png)
![image](https://user-images.githubusercontent.com/25333164/39575934-91bdc36e-4edc-11e8-9130-66981b1eef04.png)

**Comment by Funwayguy** [comment]
Are there any errors about line count mismatches in the error logs?

**Comment by TheLimePixel** [comment]
Nope

**Comment by Funwayguy** [comment]
Found it. It was a incorrect theming of the text colours. I normally test in dark theme so I didn't notice until I switched. Fixed in build 256
