### ISSUE TITLE
Repeatable Quests Timer Broke

### ISSUE THREAD

**Issue by FoxBotGames** [Funwayguy/BetterQuesting#376]
MC Version: 1.12.2
Better Questing Version: Issue Discovered in 255 but Issue tracked down to version 238

GrimCo Made the Modpack Wasted, I am the 'lead developer' for the Quests for the modpack and we just recently discovered this issue, dating back into testing. 

(Repeatable Quest with a single choice, multiple option reward)

Repeatable quests can be claimed and a reward can be selected and retrieved, however the timer for the quest never seems to reach '0' to reset the quest, the timer just goes over to anything from-5 to -59 after which the timer so gladly resets itself.
Because the issue can't be fixed without a clean default quests file (See issue #363 ) this means I would have to rewrite the entire questbook that I would rather not do. For now I will have to find a workaround which I am fine with.
![39535959-dcce20d4-4dfa-11e8-85b9-c32da4b69217](https://user-images.githubusercontent.com/33973064/39676184-506e14f6-5123-11e8-8217-11ff9623ced4.png)

**Comment by Funwayguy** [comment]
Are you sure you're not in edit mode? I know the screenshot doesn't show the edit buttons but non-ops on servers can't see those even if edit mode _is_ on.

I've been testing in single player and can only recreate it if edit mode is on in which case this behaviour is intended so it doesn't reset itself mid edit.

**Comment by FoxBotGames** [comment]
The Screenshot was taken on a SingleplayerWorld however my recreations of it were because I didn't know of the edit mode. That seems to have fixed the issue for servers. 

Is there any chance of being in edit mode when saving the defaults could cause this for the SP instances?
(Edit mode was saved to on however cheating has been disabled, so cause issue?)
Or at somepoint as setting somewhere was saved to EditMode ON?

**Comment by FoxBotGames** [comment]
Yah it was a setting on a config... Issue Resolved THANNNKKKSSSS
