### ISSUE TITLE
Repeatable quests, when the cooldown ends, display as "complete" and "unclaimed reward"

### ISSUE THREAD

**Issue by McFrugal** [Funwayguy/BetterQuesting#38]
I did claim the reward the first time, and I can't claim it again yet (because I need to finish the task again first).

**Comment by Funwayguy** [comment]
This design choice was intentional. I could add a more accurate tooltip but the overall appearance of repeatable quest icons will likely not change. Technically the quest is in fact 'complete' so you can move on to the next set of dependent quests and only need to return to claim the rewards again.
