### ISSUE TITLE
1.12.2 - Custom home image (default_title.png) not working

### ISSUE THREAD

**Issue by Songberry** [Funwayguy/BetterQuesting#380]
Hi Funwayguy, thank you so much for BetterQuesting :)

I'm having absolutely no luck at all getting my custom home screen tile to work. I've followed the instructions here to the letter - https://github.com/Funwayguy/BetterQuesting/wiki/Resources - but I just keep getting big purple and black squares.

Here's what I have in my advanced settings which I accessed from the config wheel icon in the top left screen:

![image](https://user-images.githubusercontent.com/39237232/39966851-d1782104-56f5-11e8-8350-bed0e60f3904.png)

Here's my file structure (I copied the image straight out of the BetterQuesting jar to make sure it wasn't a problem with my own file):

![image](https://user-images.githubusercontent.com/39237232/39966875-0c86f004-56f6-11e8-9187-a92d15710382.png)

And here's what happens:

![image](https://user-images.githubusercontent.com/39237232/39966860-f40abd6c-56f5-11e8-97c9-964edb2fbaa9.png)

Am I doing something wrong?

Thank you again,
Songberry

**Comment by Songberry** [comment]
*bump* Is anyone able to please help me figure this out?

**Comment by Funwayguy** [comment]
I haven't really been able to reproduce this in a recent BQ3 build:

![](https://puu.sh/AtFpS/671e0f9654.png)
![](https://puu.sh/AtFID/4c9eed01a8.png)

Are there any extra spaces on the end of the image name or any errors in the logs?
