### ISSUE TITLE
Allow us to change the order of tasks

### ISSUE THREAD

**Issue by aaronhowser1** [Funwayguy/BetterQuesting#382]
![image](https://user-images.githubusercontent.com/15698722/39969755-735ebeba-56a6-11e8-9f89-6aaf176d142c.png)
This is the screen I mean. Let us rearrange the tasks on the left here. Also, it'd be cool if we could differentiate which task has which without having to open them and look at the requiredItems list too, but that's less important.

**Comment by Funwayguy** [comment]
The ordering actually has more to do with how they're indexed within the internal database. I'd need to change a few things with how the tasks are formatted on file to make that work. I'll add a sort of property container to tasks/rewards which can hopefully deal with both of these issues but it'll need to be part of the new databases.

In the short term I don't really have any solutions for you besides manually shifting them in the raw JSON file but I wouldn't recommend that considering the potential for accidentally breaking the formatting.
