### ISSUE TITLE
[3.5.256/277] serverhang watchdog

### ISSUE THREAD

**Issue by kreezxil** [Funwayguy/BetterQuesting#384]
https://gist.github.com/kreezxil/5dfcd11084c838f4992e56a4f051870f

My dedicated server had this crash report. I don't know what the player was doing. I imagine they were updating a quest. Yes, I have my tick threshold set really high as there are misbehaving mods in my pack, for instance Ice and Fire, the very mod that World of Dragons (my pack) is based on is one such mod that needs a high tick time else it becomes unuseable.

**Comment by Funwayguy** [comment]
Oh my... 484.88 seconds isn't even remotely safe for a server to run at. How many quests are you running? From what I can see in the log, the tick timed out midway through syncing the quest database with a player joining the server. I've seen seen users with almost 1000 quests and although there have been complaints about network usage, none have ever timed out, especially not at almost 500 seconds.

Note: I'm interested to take a look at this "Ice and Fire" mod to see just what could be causing such an exorbitant tick requirement.

**Comment by Funwayguy** [comment]
Actually, if you're familiar with Java profiling it might be worth running some tests with [VisualVM](https://visualvm.github.io/) to get a better idea of what exactly in code is eating all the tick time. The crash may be only showing what was processing last, not necessarily what contributed to the root of the problem.

I can try running some of my own tests but considering I've never seen someone timeout using Better Questing before it'd prove difficult to recreate in my dev environment.

**Comment by Funwayguy** [comment]
_looks at Ice and Fire code with a large amount of concern_

I have a bad feeling I know what that profiling report is going to point to... but let's wait and see before I start pointing fingers.

EDIT: Sent a friend request on Discord. Things might get messy here and it'd be easier to discuss there.

**Comment by kreezxil** [comment]
I've been pointing fingers at Ice and Fire since I got the brilliant idea
to build a pack around it.

**Comment by kreezxil** [comment]
@Funwayguy with the latest update I'm getting high ticks reliably on better questing 1.12.2 3.5.277 

http://paste.ubuntu.com/p/RTKZyHr3Zq/

I've since reduced my max ticks to 60,000 which is default to encourage more crashing.
