### ISSUE TITLE
[Suggestion] smaller Icons on the Task side or resize option

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#39]
Is it possible to resize the Icons on the Task side. I have some Quests have 10 or more items you need to retrieve and it shows only two and you have to scroll allot. Maybe resize this icons or give us a option to resize it when creating Quests.

![image](https://cloud.githubusercontent.com/assets/2970688/15403527/b00843be-1df9-11e6-9c4a-6112b284c71b.png)

**Comment by Funwayguy** [comment]
The icons are scaled that way to match the rows of related text to the right of them. You are also on the largest UI scale for Minecraft. If you want to see more icons in the list the choose a smaller UI scale in Minecraft's options menu.
