### ISSUE TITLE
A Task is required for a reward to be claimable

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#391]
Since the second to last update, if a quest doesn't have a task, the reward isn't claimable. While this might be intended, it messes with 2 systems of mine:
-Giving people stages for completed quests, so they have to complete other quests to unlock the stage. That was easily fixable by adding a checkbox to the quests
-Using hidden quests to make the entire progression line viewable. You see, as my pack has multiple modes, I don't want the stage progression lines to be viewable from the start, so I need to have it displayed after the quest for said mode is completed.

**Comment by Funwayguy** [comment]
I think I've got this fixed for the next build. Having no tasks is a weird edge case for the quest cache and updating loops.
