### ISSUE TITLE
Please assist if possible.

### ISSUE THREAD

**Issue by Kuktar** [Funwayguy/BetterQuesting#393]
On the modpack FTB Continuum playing it with vivecraft, I get the following. I am working with the vivecraft team but they are not sure it's on there end. 

https://imgur.com/a/8N8Hu55

if needed here is the vivecraft post. https://github.com/jrbudda/Vivecraft_112/issues/51

I also tried versions
BetterQuesting-3.5.239.jar

BetterQuesting-3.5.256.jar <this is the one that comes with the modpack>

BetterQuesting-3.5.258.jar

**Comment by Funwayguy** [comment]
That's interesting. Someone had a similar issue #307 but updating to BQ3 fixed that. Haven't touched those new GUIs much since then. I don't have a vive to debug this but I'll take a look later today at the render code and see what changed since then to cause this. 

EDIT: Are you sure that's 3.5.258? Some of those screenshots look odd and outdated.

**Comment by Funwayguy** [comment]
Just adding this here but it doesn't look like a ViveCraft specific issue. Got this report from Twitter today:
![](https://i.gyazo.com/e8f724cf172c434143d1794ac9b19975.png)

Something is very wrong with the GL scissor coordinates and I'm not entirely sure why yet.

**Comment by Kuktar** [comment]
Yes 3.5.258 is the version for the screenshots I took that were messed up in vivecraft. 

The non messed up screenshots might be old. I got them from a 2 week old YouTube video from YouTuber Kraken when he played continuum alpha.

**Comment by Kuktar** [comment]
Also thank you so much for your assistance. You make a ton of cool mods, I had no idea you also made esm its ones of my favorite mods ever made!

**Comment by Funwayguy** [comment]
Weeeeee...

I'm having too much fun fixing this. (don't have Vive to test so I'm improvising)

![2018-05-30_17-57-13](https://user-images.githubusercontent.com/6048596/40708234-48635ee4-6436-11e8-98ff-2f38e3e17b9c.gif)


In all seriousness I think I've narrowed down where this is happening and can probably fix it soon-ish. This might be hard to do but do you have a clip of the GUI moving so I can compare.

EDIT: My initial attempts aren't working as well as I hoped. Might have to talk to the ViveCraft devs about how to go about fixing this.

**Comment by Funwayguy** [comment]
Getting closer...

![2018-05-31_19-30-25](https://user-images.githubusercontent.com/6048596/40774817-f197f3ac-6509-11e8-8cf1-c689728720b3.gif)

**Comment by Kuktar** [comment]
Its exciting to see you work on this. Would you like me to send you an oculus? Do you have any bestbuy nearby

**Comment by Funwayguy** [comment]
I'm very grateful for the offer but I'm in Australia so there is no BestBuy here. Also for game development reasons outside of modding, I'm specifically saving up for a HTC Vive ($880 AUD at the moment) so I can do full room tracking. Depending on how expenses go, I should be fine to buy one myself by about mid August.

**Comment by Kuktar** [comment]
Well then let me send you something to your PayPal! You make great mods and
I appreciate it.

**Comment by Funwayguy** [comment]
I'm not going to force you but if you really want to donate, my PayPal email is:
FunwayguyEmail@gmail.com

Thanks heaps. Means a lot to me that people appreciate the mods I make even if they don't always look the greatest on the surface.

**Comment by Funwayguy** [comment]
I think this is done now. Just got to fix up some stuff elsewhere, clean up the code and prep it for release.

![2018-06-01_11-13-59](https://user-images.githubusercontent.com/6048596/40816119-6ba58090-658e-11e8-9e75-4af9b933373c.gif)

I mentioned this on Twitter already but this new code might actually be capable of supporting proper 3D VR themes in future. It would need a bit more work and the finished rewrite but it's not out of the question.

**Comment by Kuktar** [comment]
So I came across a band-aid fix for what i personal experienced. Its insane that custom main menu could have this effect. 

PS: thank you for your hard work :P

https://www.youtube.com/watch?v=C1NntHxjL60&feature=youtu.be

in the video i demonstrate what i have seen. If i removed custommainmenu then betterquesting works fine.

if i remove the resource folder then betterquesting works fine. it seems with vivecraft somehow they dont like eachother. this issue does not happen when i am using 2d minecraft.

**Comment by Funwayguy** [comment]
That is very interesting. To be fair there _were_ issues with how I was cropping things in the GUI but that seems to indicate there's something more too it. I'll jump in the ViveCraft Discord too if that makes things easier. I want to send you a preview build of what I've got so far so you can give it a test drive on actual hardware before I send it out to the public.

**Comment by Kuktar** [comment]
I would love that. Just let me know and I will be online

**Comment by Funwayguy** [comment]
Not sure if you've seen it or not but I did ping you with a new build yesterday on the Vivecraft Discord support channel. Alternatively you can just DM me on Discord if you want me to send it more directly to you.

**Comment by Funwayguy** [comment]
Decided to just go ahead and publish build 259. Let me know if that fixes everything up on your end.

**Comment by Kuktar** [comment]
I will test this today. Sorry some life stuff happened lol.
