### ISSUE TITLE
Scoreboard tasks do not read from the scoreboard, and always display 0

### ISSUE THREAD

**Issue by AranaiRa** [Funwayguy/BetterQuesting#395]
Title. I have checked to make sure the scoreboard is being updated correctly with console commands. I am using BQ 3.5.258 and Standard expansion 3.4.143.

In summary:
Scoreboard REWARDS work correctly, and increment the board.
Scoreboard TASKS always think your score is 0

**Comment by AranaiRa** [comment]
Followup, it does read the board when hitting detect/submit, but this is somewhat unintuitive if you don't already know what to do.

**Comment by Funwayguy** [comment]
Closed? Didn't even get to test it yet. I'm going to assume you were just in edit mode (where things don't auto-update)

**Comment by AranaiRa** [comment]
That is exactly what was going on. I apologize for the frivolous issue post.
