### ISSUE TITLE
All Players Quest Restarted 

### ISSUE THREAD

**Issue by Dpatau** [Funwayguy/BetterQuesting#396]
Hello, one of my admins did the command 
/bq_admin reset all 

and reset everyone's quest instead of just his, I have tried to revert the better questing folder in the world folder but still nothing,

i was wondering if anyone knew how to fix this

**Comment by Funwayguy** [comment]
If you correctly reverted the progression file to before the command was run and restart the server, it should be reload all the old data. If this is not the case double check your backup to see if it actually contains the progression data you wish to restore. Beyond that I cannot help restore deleted data, sorry.
