### ISSUE TITLE
Cannot create party.

### ISSUE THREAD

**Issue by athalia117** [Funwayguy/BetterQuesting#398]
Whenever I try to click on create party, the page hangs and I can't click on back nor create party. I also cannot click on the name for the party. Same problems happen.
I am running an Enigmatica 2 server.
Is there anything I can do about this?

**Comment by NielsPilgaard** [comment]
Spamming the button works occasionally.

**Comment by athalia117** [comment]
Solved it by looking at another server's configuration file and manually typing in the things. It still doesn't allow me to change anything in game regarding parties.
