### ISSUE TITLE
[1.12.2][BQ3] Block icons go over text when zoomed in too far

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#400]
I'll let this screenshot talk for itself:
![image](https://user-images.githubusercontent.com/25333164/41294319-0aa3d58a-6e58-11e8-9f2a-7e67eb34571b.png)

**Comment by Funwayguy** [comment]
Had a feeling this would happen but was hoping that I left enough z depth in the VR changes to avoid it. I have a fix in mind but I'n not sure when I'll get around to it.

**Comment by Numorphan** [comment]
On a similar vein, it causes everything to basically ignore the containers they are supposed to be contained in (flooding text, icons, etc). Downgrading to 3.5.258 fixes it for now.

https://github.com/Discomanco/Enigmatica2ExpertSkyblock/issues/58

**Comment by Funwayguy** [comment]
That's not actually the same issue and has to do with OpenGL stencil buffers but I did just fix that less than 24hrs ago in development (OpenGL can be a right P.I.T.A. sometimes).

**Comment by Numorphan** [comment]
Ah, my mistake. Very nice to see that you've already taken care of it though! =D
