### ISSUE TITLE
Auto detection of quest not working

### ISSUE THREAD

**Issue by CrosseyedKiwi** [Funwayguy/BetterQuesting#403]
Issue with new modpack development as quests are not auto detecting for completion so not notification of being done.  Have to manually click on "Detect" to complete quest. Better QuestingVersion 3.5.2596

Was working working in previous version as modpack has been in development since December 2017 and was working until recent update.  Have done reset and refresh and added new quests to test but still not working.

**Comment by CrosseyedKiwi** [comment]
Seems to be intermittent.  Screenshots attached of one working and one not withing same questbook.
![auto completed cobblestone](https://user-images.githubusercontent.com/40310909/41495674-a2af03d8-7180-11e8-9fbb-fd1d37765ee8.jpg)
![not auto completed woodlogs](https://user-images.githubusercontent.com/40310909/41495675-a2da4e62-7180-11e8-8daf-5f02830eaa90.jpg)

Any feedback or information appreciated.

**Comment by Funwayguy** [comment]
Have you double checked you aren't in edit mode?

**Comment by CrosseyedKiwi** [comment]
I have double checked that I am not in edit mode while testing.  Just tested again in case it was me but alas still do not auto detect.

**Comment by CrosseyedKiwi** [comment]
Would it be affected by having cheats on?  I didn't think it would be as you need to be in cheat to edit.  As rule of thumb I turn edit off before saving as default when edits are completed.

**Comment by Funwayguy** [comment]
Cheat mode is fine. Would be kind of frustrating to test anything if you had to keep changing that or change worlds.

Can you send me the settings of the tasks themselves? Usually it depends on those whether the quest is cached for autocomplete.

**Comment by CrosseyedKiwi** [comment]
![auto completed task cobblestone](https://user-images.githubusercontent.com/40310909/41495839-fcd3d420-7184-11e8-9517-10b31d1c027f.jpg)
![not auto completed task woodlogs](https://user-images.githubusercontent.com/40310909/41495840-fcfcbd22-7184-11e8-97d6-cf5b179c17b6.jpg)

These are the task files the cobblestone one did auto complete but the woodlog did not.  The others in my pack have not auto detected and completed and have to be done manually.

**Comment by CrosseyedKiwi** [comment]
I can send you the config file of that helps.  I'm totally confused as they look identical.

**Comment by CrosseyedKiwi** [comment]
[BetterQuesting Config.docx](https://github.com/Funwayguy/BetterQuesting/files/2107879/BetterQuesting.Config.docx)


Not sure it the helps.  Obviously still work in progress and I'm hoping it is something I am doing wrong :) 

Your mod is awesome.

**Comment by Funwayguy** [comment]
I can't really import a word document into BQ to test. The hidden formatting messes things up a bit. Can you upload it as a txt or json file?

**Comment by CrosseyedKiwi** [comment]
[BQ Config.txt](https://github.com/Funwayguy/BetterQuesting/files/2107935/BQ.Config.txt)

**Comment by CrosseyedKiwi** [comment]
Addition information that may be relevant?  I have notice that the line groupDetect is missing from crafting Tasks but is present in the Retrieval Tasks.  The retrieval tasks autodetect and notify on completion but Crafting Tasks do not.
![crafting task](https://user-images.githubusercontent.com/40310909/41813948-dc8f2960-7794-11e8-8294-4adf11a3bcd8.jpg)
![retrieval task](https://user-images.githubusercontent.com/40310909/41813949-dcbae46a-7794-11e8-86aa-0a33715649af.jpg)
