### ISSUE TITLE
Object Submission Station Not Working

### ISSUE THREAD

**Issue by mxnmnm** [Funwayguy/BetterQuesting#408]
I was making quests and realized that I should test the object submission station.  I made sure to turn off edit mode and for the first quest (a stack of obsidian) I was able to put the obsidian in the station but I couldn't pipe it in (I tried thermal dynamics and ender io pipes) (hoppers did work but I'd prefer a faster way of doing quests).  Then I tried with a more complex quest (an ore quintupling one for mekanism) but the station wouldn't even let me select the quest.

forge 1.12.2-14.23.4.27055

(here are all of the mods and configs I'm using)
https://drive.google.com/open?id=1dATFGX2hXVsr-8Qc0ZjlWogWlbGqeImN

If you need any other info let me know.

edit: adding another part to that quest line fixed it but you should still probably look into it also allowing item ducts to work would also be very nice

**Comment by rgtexa** [comment]
I'm also experiencing issues with the OSS not functioning with liquids or items.

I'm using Forge 14.23.4.2705 and BQ 3.5.260 along with BQ Standard Expansion 3.4.143.

The OSS allows me to select the appropriate quest, but will not accept items piped in with Mekanism logistical pipes, and will not accept fluids pumped in with Mekanism or Immersive Engineering fluid pipes.

I'm using the [Automaton](https://minecraft.curseforge.com/projects/automaton) modpack for reference.
