### ISSUE TITLE
[Question] Server Default reload with Player progression Data won't work

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#41]
I try to reload Quests on my Server (to get new Quests ) with Player progression Data in the Json file and it won't update. If I clear all player data I can reload it and get new Quests. Is this international too and I guess you fix will solve this problem?

**Comment by Funwayguy** [comment]
How exactly did you try and 'reload' quests.

**Comment by Dream-Master** [comment]
is there a other option to refresh Quests. (i add new Quests inside the json via dei ingame editor and copy all Player progression Data into that file and try to reload it but this dont work)

**Comment by Funwayguy** [comment]
That isn't how that file is meant to be used. If you want to move data from the current QuestDatabase file to the default one you should be using "/bq_admin default save". Even then this shouldn't normally be used to 'update' the quest lines. Like I've mentioned in the other issue thread, I will be making a dedicated way of doing this with progression merging.

**Comment by Dream-Master** [comment]
Ok i will try this.

**Comment by Dream-Master** [comment]
So i save the data but new Quests are not shown. Progression not lost.

**Comment by Dream-Master** [comment]
@Funwayguy Ok in the new Better Questing Update 1.0.98 i can now updating the Questfile and not loosing progression any more but i get all the rewards again.

**Comment by Dream-Master** [comment]
@Funwayguy I hear from the Prosper Craft server which play my Modpack GTNewHorizons too that they can't reloading the Quest file with Better Questing Version 101. The new and updated Quests are shown but if People try to complete Quests it won't work.

**Comment by Funwayguy** [comment]
I believe after splitting all the progression in the last few updates this should no longer be a problem if done right (edit > save > load).

**Comment by Dream-Master** [comment]
After i make the update with the new file i will test it and report to you.

**Comment by Dream-Master** [comment]
OK try now to loading the changed Quests with Version 118  and it reset my player data again.
If I default load it give me the new Quests but rest all Progression data
If I try default save it save the old file over the new one so the Quests not updated but Progression still there.
If I do edit then save then load it doesn't work also. I can only save progression data manually reload the defaults shut down the Server copy Progression data back and restart the server. I hope i did something wrong and there is a more easy way.

**Comment by Funwayguy** [comment]
Seems I forgot to add progression preservation handling to the default load command. Last update should resolve that part at least.

**Comment by Dream-Master** [comment]
Ok thanks will test it when I came back from work. 
I see chain quests are changed too. How they have to work normally?

**Comment by Dream-Master** [comment]
So far  can say the progression date is not reseted any more if i reload default Quest data.
