### ISSUE TITLE
[1.12.2][BQ3] Crash as soon as I enter a world

### ISSUE THREAD

**Issue by bluepython508** [Funwayguy/BetterQuesting#414]
Crashlog: [Crashlog](https://paste.ee/p/idoxX)
As soon as I entered a world that had been created before I installed BQ (this was the second or third time I'd loaded the world, first with BQ) I got a crash. I also tried a new world. Same problem.
I'm plying the modpack foregoing.

**Comment by Funwayguy** [comment]
Wrong version of Standard Expansion for the base mod. Use one that starts with 3.x.x

**Comment by bluepython508** [comment]
Thanks
