### ISSUE TITLE
No way to add required items

### ISSUE THREAD

**Issue by silverfur64** [Funwayguy/BetterQuesting#417]
Updated to 3.5.261 and went to add new quests. Created the quest fine, went to edit it just fine, added a retrieval task, went to edit it (I liked the new true/false buttons) and clicked on the list button to add required items and it pulled up an empty page. Not the page I was use to where there was a + and you added items and such to the list, but a page with nothing but a back button at the bottom of the page. How are items to be added now? Or is this a bug?

**Comment by Golrith** [comment]
Update to BetterQuesting-3.5.262 and this should be fixed.
