### ISSUE TITLE
Unable to invite players to party

### ISSUE THREAD

**Issue by ProsperCraft** [Funwayguy/BetterQuesting#42]
I made a quest party, but the other player on the server doesn't show up in the boxes when I click invite.

**Comment by Dream-Master** [comment]
Using version 101 from Better Questing.

**Comment by Dream-Master** [comment]
Ok Prospercraft and my server have the same problem in post one with Version 118 and standart expansion Version 81.

**Comment by ProsperCraft** [comment]
BetterQuesting-1.0.118

Still unable to invite anyone to my quest party.

**Comment by Funwayguy** [comment]
Just tested with the latest versions on 1.7.10 and 1.9.4 and couldn't recreate this. How many other players are on the server when you try to invite?

**Comment by Nenluen** [comment]
I'm also on the Prospercraft server.

There are usually 4-6 people on.

With me standing pretty close to a fellow in my town, and a party made, this is the window i see when i hit 'invite players'

![2016-06-06_15 28 21](https://cloud.githubusercontent.com/assets/10765948/15836694/940c321e-2bfb-11e6-91ad-450773c614eb.png)

**Comment by Funwayguy** [comment]
That's very odd. Those buttons shouldn't be showing up at all if they're blank. Is there any console errors being printed client side when opening that screen?

EDIT: Actually the code says they should NEVER be blank even when invisible/disabled. This is extremely puzzling. Do you have mods that would be tampering with the player listing when holding the tab key?

**Comment by Nenluen** [comment]
The console shows nothing when i open the book, party or invite lists.

There is no mods that I'm aware of, however being a network of servers our tab screen looks like this:
![2016-06-10_09 11 00](https://cloud.githubusercontent.com/assets/10765948/15967042/671ca688-2eeb-11e6-8d69-a6d08ef4818d.png)

I assume this is due to a plugin of some kind, but ProsperCraft would be the one to fully answer this.

**Comment by Nenluen** [comment]
I went and opened this into a new test world, and sure enough, it appears to work as intended, so maybe there's a plugin conflict with our playerlist

![2016-06-10_09 54 53](https://cloud.githubusercontent.com/assets/10765948/15968418/788e9128-2ef1-11e6-8894-32270ae1382e.png)

**Comment by ProsperCraft** [comment]
If you added a feature to add players by name this might help?

**Comment by ProsperCraft** [comment]
our playerlist is changed with a bungee plugin that shows players from each server.

Bungeecord is a proxy for minecraft that allows players to connect to one place then connect over to another server from there, it centralizes chat and such.

**Comment by Funwayguy** [comment]
Well it's tampering with the client side player listing in a destructive manner instead of replacing the UI. I will add in a manual invite method in a later version but you should contact the developer of BungeeCord and ask for them to stop tampering with the client side player data.
