### ISSUE TITLE
New world with quest

### ISSUE THREAD

**Issue by Seba244c** [Funwayguy/BetterQuesting#420]
Hello

I am the creator of an modpack. I plan too use this mod in it. I made some quest, but! When i created a new world they were gone! How do you make it so every time you make a new world, it loads the questes i made?

Best regards
Sebastian

**Comment by seba244c** [comment]
<emebd src="https://minecraft.curseforge.com/projects/most-mods">

**Comment by Funwayguy** [comment]
The command you are looking for is "/bq_admin default save"

**Comment by Seba244c** [comment]
You seved me thanks!
