### ISSUE TITLE
Request-about server

### ISSUE THREAD

**Issue by OldKingisdie** [Funwayguy/BetterQuesting#423]
Could join the function of using Mysql for synchronization tasks like some plugins, it will be very useful in bungeecord server

Bungeecrod：https://www.spigotmc.org/wiki/bungeecord/

**Comment by Funwayguy** [comment]
Not likely to happen anytime soon for 4 reasons.

1) BQ3 isn't even done being rewritten yet and I won't be adding any major new features untill it is.
2) I only just rewrote the internal database to be faster and thread safe. I'm not going to rip up so much work so soon.
3) I don't do support for Non-Forge servers.
4) Even of I did make all of this work with MySQL. It would break backwards compatibility and make everyone start over.

**Comment by OldKingisdie** [comment]
It's a forge server and Just use bungee to connect a lot of sub servers .I use spongeforge server 
A very friendly server to the forge

sponge：https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

 Is it possible to set up a path option, such as allowing several server to use the same QuestDatabase.json file?

**Comment by Funwayguy** [comment]
Spongeforge has caused issues in the past with BetterQuesting so I wouldn't call it friendly. It messes with things that I can't test or fix in my development environment.

Pointing multiple servers to the same file would just result in read write conflicts and crashes.

Maybe in the far off future when BQ3 is feature complete and stable I'll reconsider dedicated multi-server support.

**Comment by OldKingisdie** [comment]
Well, Sponge has been very friendly compared to bukkit or spigot in high version of minecraft,  Anyway, BQ3 is really the best task mod I've ever used. Thank you very much for your help.
