### ISSUE TITLE
Pantalla negra

### ISSUE THREAD

**Issue by lmentrix2** [Funwayguy/BetterQuesting#424]
https://imgur.com/tjvQ35J 
Por favor ayudaaa

**Comment by Funwayguy** [comment]
This isn't a Better Questing bug. Vanilla Minecraft does this sometimes when you reisize the screen during loading.

**Comment by lmentrix2** [comment]
Entonces como la soluciono

**Comment by Funwayguy** [comment]
I am really not the person to be asking nor is this the place for it. Unless it is specifically caused by Better Questing, you would have a better chance of asking elsewhere in the general Minecraft community. I'm barely getting by as is with Google Translate here.
