### ISSUE TITLE
Issues with quests

### ISSUE THREAD

**Issue by RobinNightWing** [Funwayguy/BetterQuesting#427]
More specifically, Whenever I go in and out of edit mode, I see 2 completely different things.
![2018-08-17_12 41 18](https://user-images.githubusercontent.com/27363790/44278077-eb941500-a21a-11e8-843b-066f986b557a.png)
![2018-08-17_12 41 07](https://user-images.githubusercontent.com/27363790/44278078-ec2cab80-a21a-11e8-8547-f61df26c8a90.png)

In case you wanted to see the files I've created a zip file to access the modpack I've created with the files

https://www.dropbox.com/s/vp97ob8ep00fqar/Modpack%20for%20this.zip?dl=1

Better Questing-3.5.262
StandardExpansion-3.4.143

**Comment by Funwayguy** [comment]
...and this is an issue because?

By default only the first locked quest is shown to players after the current unlocked quest. This is intended. If you really wanted to show players all of the locked quests just change the visibility settings of the quests.
