### ISSUE TITLE
Fast gfx glitching in Submission Station

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#429]
not using OptiFine, BetterFps or Vanilla Fix

MC 1.12.2
Forge 2757
Better Questing 3.5.263
Better Questing - Standard Expansion 3.4.145

so place a Submission station down and chose a mob hunting quest from inside its gui and the animation for the mob flashes very fast

managed to get this screen shot, but happens all through the mob turning animation

https://1drv.ms/u/s!ArSGAcC04KWsjgkZBfMMNqDUZKUz

**Comment by Funwayguy** [comment]
I changed up a bunch of rendering for entities and items in GUIs and the submission station is one of the old legacy screens I haven't gotten around to fixing (it's actually the most complex of them all to replace). I'll look into making a temporary fix for this in a later update to make it usable in the mean time but at the end the day the whole thing needs rewriting anyway.
