### ISSUE TITLE
[bug] Can't edit Quests any more

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#43]
I try today the new Version Better Questing Version 108 and load my Quest file. This works fine but if i try to edit the Quests (/bq_admin edit) all Quests are gone.

**Comment by Dream-Master** [comment]
The same when i set the edit in the json file to true. I can edit files but if i go back all Quests are gone.

**Comment by Funwayguy** [comment]
I pulled the last two affected versions an uploaded a fixed replacement. Sorry for the inconvenience
