### ISSUE TITLE
Description disappears after scrolling down over 15 lines

### ISSUE THREAD

**Issue by luke-bravenboer** [Funwayguy/BetterQuesting#433]
You might already be aware of this as it's pretty easy to replicate, but I can't find a report for it yet so- the quest description box goes invisible if you scroll down too far.

Upon testing it seems to occur consistently if you scroll down further than approximately 15 lines of text- I've got some screenshots to demonstrate here:
https://imgur.com/a/ASzXGkp

***Versions:***
BetterQuesting: 3.5.263 / 264
Forge: 2738

**Comment by Gotolei** [comment]
I'm running into this too. Probably worth noting: it works properly when GUI scale is set to normal, but the issue starts happening on any larger setting.

In action: https://streamable.com/y9osj

BetterQuesting: 3.5.263
Forge: 2751

**Comment by Funwayguy** [comment]
Should be all fixed in 265. Because text boxes dynamically size themselves to fit the wrapped text I didn't account for that to break the new overdraw culling I added to the scrolling canvas panels.
