### ISSUE TITLE
the new update is causing a huge lag of some sort.

### ISSUE THREAD

**Issue by mattrix444** [Funwayguy/BetterQuesting#434]
i updated to the latest 1.12 version as of yesterday and when i'm making quests if i click on things like the icon editor or something my game completely freezes. it was fine on the last version.

**Comment by CrankySupertoonArchive** [comment]
I can second this

**Comment by Funwayguy** [comment]
Seems I may have found the cause. I assume you have a couple of thousand items in your pack. Despite keeping the search itself from taking too long I forgot to account for the time taken to composite the panels after the search completes which can take about 400ms per 1000 items.
