### ISSUE TITLE
3.5.264 hangs server

### ISSUE THREAD

**Issue by kreezxil** [Funwayguy/BetterQuesting#437]
My dedicated server is repeatedly being hung by the latest version. http://paste.ubuntu.com/p/ZTtCkjHcKh/

**Comment by Funwayguy** [comment]
Ffffffudge. Forgot that's a client only function. I just uploaded a new build too >_>

I'll try and get this fixed ASAP

**Comment by ProsperCraft** [comment]
Same here - https://gist.github.com/ProsperCraft/60047a8c73b9534b2991101e0533b1bc

**Comment by ProsperCraft** [comment]
Is it possible this player not being able to log in - see line 954 and on  be related to this issue?

https://gist.github.com/Thorandan/b1c82961856ce38e5071d88ae9032b83

**Comment by Funwayguy** [comment]
@ProsperCraft The second issue looks to be something to do with CreativeCore possibly tampering with packet handling, not BetterQuesting.

I've uploaded 266 with a fix to the sever crash so once Curse approves that you should be able to update to that.
