### ISSUE TITLE
[Suggestion] We need a hiding function for make Quests more secret

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#44]
Every time when I open the Quest book and start a new Game I can see minimum two Quests the one I have to make and the next one. I suggest give us a option to hiding Quests from shown in the book if not open.( let's show only the active Quests and not the previous one) It would be nice also for some secret Quests to give us some trigger mechanism which open a new Chapter/quest only if you unlock them with a another Quests, Item in Hand, Coordinates Dims you walk etc. Before this Quest have to be hidden.

Thanks.

**Comment by Funwayguy** [comment]
I will add some display options for quests but for now it's not high on my todo list.

Secret quests are already possible. Just don't add them to a quest line, they will still function but will be inaccessible.

**Comment by Dream-Master** [comment]
Ok but if you have a complete Secret Quest line and you want a special order this Quest have to be made then you have to link the Quests because Quest nr. 2 have to comes after Quest nr. 1.

**Comment by Funwayguy** [comment]
Had some free time after fixing a few bugs so I threw visibility options into the last update.

**Comment by Dream-Master** [comment]
@Funwayguy 
Ok I test it now but if a Quest is hidden it not shown any item if it is unlocked. I think hidden Quest have to been visible after unlock them not totally hidden.

**Comment by Dream-Master** [comment]
After you make the Quest you can't see what you done or claim a reward. So the hidden function how it is now not make sense for me.

**Comment by Dream-Master** [comment]
Maybe you can change the Hidden function to be hidden so long task X (which is secret) is done.

**Comment by Dream-Master** [comment]
Ok will open up a new issue for it.

**Comment by Funwayguy** [comment]
Please don't. I can see your responses here just fine. Not only that but I have additional options finished in debug builds already.

PS: I also would prefer it if you didn't jump in other people's issue threads unless you have additional information or a potential solution.

**Comment by Dream-Master** [comment]
Ah ok sorry don't want to rush you. I play with your hidden option yesterday and have two things I would really like to see in this Mod.
1. Hidden Quest Option with a Trigger be visible at a task x .
2. Give us the possibility to make tasks hidden so people can't see it (only in edit mode) so it is possible to build in secrets in your Quests.

@PS
I jump into other Issues because Prospercraft using My Pack and I want you to say which version we using. 

@Funwayguy You make a very good mod which I can work with very well, the things I suggestion are only small things to make this Mod perfect :)

**Comment by Dream-Master** [comment]
I got another idea. Is it possible to show up the Quests like on this picture?
https://farm6.staticflickr.com/5813/23685089491_e7fb7a92ae_z.jpg
With a Question mark. The icon have to change after the Quest is accessible to make Quests a bit more secret.

**Comment by Dream-Master** [comment]
@Funwayguy 
Ok new Options works well to hidding Quests. Thanks allot for it (Version 118)
The only Question i had is if you can make hidden tasks or set a Task as hidden?
