### ISSUE TITLE
1.12.2 Lag when entering when adding in icons

### ISSUE THREAD

**Issue by litjohn50** [Funwayguy/BetterQuesting#440]
When ever I want to add an icon to a quest it just freezes for a bit until it registers same with when I search for an item. 

Makes it really painful to make any quests.
I don't Believe it used to do this in previous versions.

https://gyazo.com/ac76a5aab1c51c6a75bd75c076b04d6e

**Comment by Funwayguy** [comment]
This was supposed to have been fixed in 3.5.265 and up. Which version are you using?

**Comment by litjohn50** [comment]
Hmm I'm using 3.5.264 I see it was updated recently, just didn't see anything significant in the changelog. Updating will let you know if its fixed on that.

**Comment by litjohn50** [comment]
Ok it seems fixed in the newest version. Sweet!
