### ISSUE TITLE
Crash when open item selection menu

### ISSUE THREAD

**Issue by DevTimur** [Funwayguy/BetterQuesting#445]
Forge 2725 and 2747, and others too. Still crash
BetterQuesting-3.5.263 and 3.5.266
https://pastebin.com/Ab0b4Dgq

Really not sure what happend, at some point it just begin crashing, i'm not even sure it's Better Quest's fault. Maybe you can look?

**Comment by Funwayguy** [comment]
Seems someone registered an invalid itemstack (empty, null, etc.) into the creative inventory and the Ore Dictionary part of the BQ's item search did not take kindly to that.

Edit:
The old GUI used to catch these errors and ignore them however these are game breaking bugs that the devs responsible should be fixing. Therefore I'm not ignoring the errors anymore in the new GUI. Looking at your error however there is no information provided on who is at fault so I'll add that next update so you know who to forward this crash report onto.

**Comment by Funwayguy** [comment]
Still haven't released a completed build with the extra crash info so I'll give you this temporary one to debug the items causing the crashing for now:


[BetterQuesting-3.5.267_UNFINISHED.jar.zip](https://github.com/Funwayguy/BetterQuesting/files/2390711/BetterQuesting-3.5.267_UNFINISHED.jar.zip)

**Comment by DevTimur** [comment]
Ok.... Just tested your build (267), and crash didn't happend.

For the last 7 days i added/removed/updated some mods, and changed Forge version, so i thought this bug randomly fixed itself.

But!..

I used version 266 again, and it crashed! https://pastebin.com/Hy9gBxJf
I guess you fixed this bug in your newer version unintentionally. ¯\ _(ツ)_/¯

**Comment by Funwayguy** [comment]
Hmm... there is one edge case that does occur in 266 but not in 267 involving the Ore Dictionary lookup (I moved some stuff around to fix a separate bug). I've included it in this one:

[BetterQuesting-3.5.267_UNFINISHED-2.jar.zip](https://github.com/Funwayguy/BetterQuesting/files/2391671/BetterQuesting-3.5.267_UNFINISHED-2.jar.zip)

Now if _this_ doesn't crash I'll be somewhat more surprised. Personally though I'm more interested in which mod(s) are at fault.

**Comment by DevTimur** [comment]
No surprise here. It crashed.
https://pastebin.com/yfvcKTPz

About this mod, causing crash. Player Storage.
There is some items you can disable in Configs, and i did disable some of them.

**Comment by Funwayguy** [comment]
I might just got take a look at the player storage code to see how they even managed to end up with an invalid item.

**Comment by Funwayguy** [comment]
I... I don't even... why?

_sigh_

https://github.com/MrRiegel/PlayerStorage/blob/1.12/src/main/java/mrriegel/playerstorage/registry/ItemRemote.java#L35

So apparently if you disable the remote it just empties the stack whenever one is created. Doesn't remove the registry entry though so you're stuck with broken item stacks. I bet BQ is not the only mod this breaks.

EDIT: Wonderful. They're doing this for all of their items so any one of them will crash the game if you disable them.

**Comment by DevTimur** [comment]
Well.... it works for him...
Anyone can trashcode sometimes. Probably he should recieve a feedback about this problem.

**Comment by Funwayguy** [comment]
Just because it works for one person doesn't mean it will work all the time for everyone. I get people write bad code starting out (BetterQuesting and EnviroMine are great examples). What I don't get is the reasoning behind needing to delete items completely, during runtime no less, rather than just inaccessible or inoperable like every other creative item devs make. I can think of a few of machines this could crash if a pack dev disabled one of these, potentially corrupting saves too.

I'll write up an issue report for it and explain why it's such a bad idea. I'll try not to be too harsh. Feel free to use 267 in the mean time and notify me of any other crashes other items cause.
