### ISSUE TITLE
[Question] Custom loot boxes are save specific?

### ISSUE THREAD

**Issue by wormzjl** [Funwayguy/BetterQuesting#446]
Maybe I've missed something important, I see that QuestLoot.json which contains custom loot bag info is in each save file's folder, which means if I configured them in one map it cannot be simply used elsewhere automatically.
From a modpack perspective, is there anyway I can have the same lootbags everywhere?

**Comment by Funwayguy** [comment]
There's a command `/bqs_loot default save` that will save it as the default for new worlds. It functions similar to the default quests. I'm eventually going to remove the ability to have different quest lines per save (it's causing more issues than it solves)

**Comment by wormzjl** [comment]
Ok thank you!
