### ISSUE TITLE
The New Nbt Gui Crashes

### ISSUE THREAD

**Issue by mxnmnm** [Funwayguy/BetterQuesting#454]
When I tried to add items to a choice reward quest this crash happened

https://pastebin.com/kv6HrAe6

This only happens on better questing 3.5.268

3.5.267 works just fine

If you need more info let me know!

**Comment by TheSnowyChickens** [comment]
Could this crash : https://paste.dimdev.org/emolulovoh.mccrash : be the same ?

(I only wanted to change a quest Icon)

**Comment by Funwayguy** [comment]
No that's a separate crash. Immersive Railroading has an invalid item stack (item_rolling_stock) which BQ doesn't take kindly to when looking up info about it.

**Comment by TheSnowyChickens** [comment]
Okay, should I open a issue at Railroadings Github or here at BQ Github ?

I think railroading, right ? :D

**Comment by Funwayguy** [comment]
Considering I can't do a lot from my side (besides outright ignoring invalid items which would likely crash something else eventually anyway) it would probably be a better idea to send this to Immersive Railroading's GitHub tracker. If necessary you can tag me in it so I can add additional information if needed.

**Comment by TheSnowyChickens** [comment]
Kk

Edit: done, the report is now open on the IR Github.

**Comment by mxnmnm** [comment]
Is my crash something you can fix?

**Comment by Funwayguy** [comment]
@TheSnowyChickens You might be interested in this almost identical crash report #460 

Went and had a look at IR's code and found their issue so I'll add that info to their issue tracker too.

As for the original issue, that was fixed in 269 so I'll close this issue.
