### ISSUE TITLE
\n\n don't create linebreaks

### ISSUE THREAD

**Issue by dredhorse** [Funwayguy/BetterQuesting#462]
Version 3.5.267

Trying to use \n\n to create a paragraph doesn't work, the book will just display \n\n

Are there any other ways to create line breaks?

**Comment by Funwayguy** [comment]
There's a full page text editor for doing multi-line descriptions. Use the "Aa" button to open that up and with that you can just use `Enter` as you normally would. Comes with some formatting options in a sidebar too.
