### ISSUE TITLE
[1.12][bug] auto-claim doesn't auto-claim

### ISSUE THREAD

**Issue by mensreaMC** [Funwayguy/BetterQuesting#464]
Unless I'm mistaken then auto-claim means you will not have to hit the "Claim" button to receive your reward for quests. This feature doesn't work, at least with quests that have scoreboard rewards. You still have to hit the "Claim" button.

**Comment by TheQKnight** [comment]
yep this happens to me too in the latest version 271

**Comment by Funwayguy** [comment]
Known working as of build 291. Closing issue
