### ISSUE TITLE
[Suggestion] Hidden tasks inside Quests

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#47]
Is it possible to make hidden tasks or set a Task as hidden? Now i can make hidden task only with hidden Quests which are completely invisible works as trigger(but you need to make the Quests extra). The better way is to put hidden tasks into the existing Quests to make some secret Quests.

**Comment by Funwayguy** [comment]
You can't make tasks specifically hidden but I think what you're looking for is Quest visibility 'completed' so that the quest may be active in the background but not visible until until it has been completed and ready to claim.

**Comment by Dream-Master** [comment]
I mean you have a Quest with a text and you see only the text but not the tasks (maybe some retrieval Task). After you found the Object X or craft it the Quests are completed. Now i have to make a hidden Quest as a trigger Quests which trigger the next (main) Quest and to not showing the Tasks behind it. I hope you understand what I mean my native Language is German.
I can show you later how I did it that you maybe understand what I mean.
And why you can’t implement a hidden Task. If I look at the Quests in edit mod I see the whole Questline and in quest mode it is hidden and shown when you making the Quests.

**Comment by Funwayguy** [comment]
I understand what you want but I think that would be better achieved through a hidden quest acting as a trigger for the actual quest. Here's an example:

In edit mode I've setup these 6 quests. The bottom row is the main set of quests but contain no tasks. The top row contain tasks but are completely hidden from the user. Note the prerequisite lines:
![](http://puu.sh/pnEje/e0295ae824.png)

And this is what a normal user will see:
![](http://puu.sh/pnEr2/1ad2f10cc9.png)

You could even extend this to unlock quests containing only rewards elsewhere if need be

**Comment by Dream-Master** [comment]
Ok sure this works too but it is much more work to creating new hidden Quests. We have already 500+ Quests and we want to add more.

**Comment by Funwayguy** [comment]
If you designed your entire quest lines on a niche feature that doesn't exist, I think you need to rethink some of your design choices really.
