### ISSUE TITLE
CraftingTasks dont work with Extenden Crafting Tables and Artisan Workshops.

### ISSUE THREAD

**Issue by Freebi85** [Funwayguy/BetterQuesting#471]

**Comment by Funwayguy** [comment]
Standard Expansion crafting tasks only listen to the Forge crafting event when fired and can only record data when a player is directly involved in said crafting. This means that if a mod does not fire these events for their crafting methods or the items are created automatically/anonymously through machines, I can't record it or who the progress should be attributed to.

...and no I do not intend to manually add support for ever mod's crafting methods.

**Comment by Freebi85** [comment]
Nevermind ;-) Thanks for your interest nevertheless.
