### ISSUE TITLE
[1.12.2] Quest ID always showing

### ISSUE THREAD

**Issue by ProspectPyxis** [Funwayguy/BetterQuesting#474]
I'm having an odd problem where the quest ID is always shown regardless of me holding shift while hovering. I've tried turning edit mode off, but that didn't fix it. This is happening for every quest.
![image](https://user-images.githubusercontent.com/25642180/47427887-e378c880-d7bb-11e8-87ce-fa2671e0267b.png)

**Comment by Funwayguy** [comment]
That would be because I moved it to Minecraft's built in advanced tooltips (`F3 + H`) in 3.x.x builds.

**Comment by ProspectPyxis** [comment]
Well, that explains it. Thank you.
