### ISSUE TITLE
[Question/Possible Bug] Icon Colors Only Change In Edit Mode

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#475]
So I've made my own BQ theme in my mod GregBlock Utilities, but I'm running into a slight issue. The custom icon and line colors I'm using in my theme only show up in edit mode.
![image](https://user-images.githubusercontent.com/25333164/47453509-3149fc80-d7cd-11e8-9c12-833489e99883.png)
![image](https://user-images.githubusercontent.com/25333164/47453528-3ad36480-d7cd-11e8-9460-ef99e183f5cf.png)
 Am I missing something or is this a bug? https://github.com/EmosewaPixel/GregBlockUtilities/blob/master/src/main/java/gregblockutils/BQ/ThemeRenderGB.java

**Comment by Funwayguy** [comment]
It is but also isn't a bug per-say. You just ran into one of the few places the new theming system doesn't support the formatting of the old ones. I might be able to temporarily add something to make it work for now.

If you're wondering if you could use the new format, sorry but it would break the legacy GUIs so I can't load them untill they're all gone. Currently old themes are just running through a wrapper to make them work on both.

**Comment by Funwayguy** [comment]
When Curse approves it, try build 272 and see how that goes. I've included a legacy wrapper for the line old line renderers so they should look the same in both new and old GUI screens.

**Comment by TheLimePixel** [comment]
What about the icons though? Also, even if you do make it work, I would really need #477 to be fixed, since  there'd be no point of it working if people can't play with it.

**Comment by Funwayguy** [comment]
Uploaded build 275 which should hopefully resolve the remainder of this issue and 477.

Just a reminder that you're working with legacy themes that will eventually be deprecated and removed. The new one should be much easier to work with though.

**Comment by TheLimePixel** [comment]
Thank you. Sounds great.
