### ISSUE TITLE
Ticking Player Crash

### ISSUE THREAD

**Issue by TheLimePixel** [Funwayguy/BetterQuesting#477]
So, it seems that on all the release versions, some time after creating a new world, a ticking player crash occurs. It does not happen on a fresh install of BQ, it just happens with the default quests in my pack. https://pastebin.com/z6rR4cQd
I don't get if there's something in my DefaultQuest file that shouldn't be there or there's something missing, but for now I'm pretty much stuck with using version 3.5.253 as it's the only one where I don't have the issue and the quest parties work. https://gist.github.com/EmosewaPixel/8dc262560fc6a9bd151d504f6b08ab4d

**Comment by Funwayguy** [comment]
I knew I forgot something important last update. I really need to set myself a reminder to look into this

**Comment by Funwayguy** [comment]
I've made a makeshift fix for this for next update but the actual issue is a side effect of the poor networking setup quests are using and have yet to be replaced.

**Comment by TheLimePixel** [comment]
So, would you be able to tell me whether the next update will be within a 24h period of this message or during the weekend? I'd just like to know so ik whether to wait a bit and release the next update of my pack or just release the first part of it after your reply.

**Comment by TheLimePixel** [comment]
So 3.5.274 still doesn't seem to have fixed it... (you also forgot the icon colors, though I think I should have pointed it out more so you didn't forget)
