### ISSUE TITLE
[3.5.272] Server Crash

### ISSUE THREAD

**Issue by Vitali8** [Funwayguy/BetterQuesting#478]
Crash occurred during server startup.
[Gist with crash.](https://gist.github.com/Vitali8/98bef2bb70d68970cb6f959be215e3c4)

**Comment by ProsperCraft** [comment]
Same crash on my server as well, single player is fine.

https://gist.github.com/ProsperCraft/d3a31d3a4c3143384c964f39d7ca706c

Forge 14.23.5.2772
No sponge in my setup, so we can eliminate that.

**Comment by Funwayguy** [comment]
Build 272 uploaded to fix this. Should be approved for download soon.
