### ISSUE TITLE
[Server Crash] Using Extra Life

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#48]
The whole server crash if i am try to using an extra life with no Hardcore Mode enabled.

Crash Log:
https://gist.github.com/Dream-Master/ac81934aca926e1508c7d787421ebf78

using in my Pack:

BetterQuestin Mod 1.0.121
Standart Expansion 1.0.81
RF Expansion 1.0.11
BQ Theme 1.0.0
Questboock 1.1.0

**Comment by Funwayguy** [comment]
This should be fixed as of the last version
