### ISSUE TITLE
red lines above quests should not exist

### ISSUE THREAD

**Issue by TheNimbleNinja** [Funwayguy/BetterQuesting#480]
can you please make each quest by default be above the red line  on all created quests as the red line is making my quest book look ugly

**Comment by Funwayguy** [comment]
Can you clarify what you mean by red line?

**Comment by remclave** [comment]
He's talking about the link line crossing over the quest icons WHILE IN EDIT MODE ONLY. If the line IS crossing over when not in edit mode then I would agree it would be "ugly".

I saw this occur while developing quest lines as well and thought it was inevitable. But when I exited edit mode, the quest linking lines all ran "beneath" the quest icons.

**Comment by Funwayguy** [comment]
Oh you mean in the designer. That's still built on the old legacy GUI code and doesn't support the proper layering that the new ones do. When the screen is eventally replaced the lines will render properly. Just keep in mind the slight visual inconsistencies between the two.

**Comment by TheNimbleNinja** [comment]
oh i ddint realize the lines didnt render below the quest icons on it edit mode
