### ISSUE TITLE
Standard Expansion scroll bar nonfunctional

### ISSUE THREAD

**Issue by remclave** [Funwayguy/BetterQuesting#482]
Version: 3.4.145
Forge Ver: 2772

Scroll bar doesn't work when using larger GUI Scales. 
(I use Large scale or everything is too small for me to see...)

**Comment by Funwayguy** [comment]
Can you give me an example of a specific GUI or task/reward panel where this happens?

**Comment by remclave** [comment]
When I'm in tomorrow morning (about 11 hours from now) I will take screenshots.

**Comment by remclave** [comment]
GUI SCALE: Normal View
![2018-11-06_10 23 46](https://user-images.githubusercontent.com/31051239/48078269-ae527a00-e1ae-11e8-8a48-1b9708418366.png)

GUI SCALE: Large View (best view option for me) and scroll bar is inactive.
![2018-11-06_10 24 55](https://user-images.githubusercontent.com/31051239/48078325-ce823900-e1ae-11e8-91c5-591ca6ed8162.png)

**Comment by remclave** [comment]
In the newest release for BetterQuesting and StandardExpansion, the scroll bars are working beautifully for all GUIs. Thank you for the fix!
