### ISSUE TITLE
Manage party/New party bug?

### ISSUE THREAD

**Issue by Sam90010** [Funwayguy/BetterQuesting#483]
Every time I try to make a party or join a party better questing is using my uuid instead of my player name. 
![betterquestingpartybug](https://user-images.githubusercontent.com/44726384/47952449-e99e4000-df45-11e8-9327-74bad9350495.jpg)
using BetterQuesting-3.5.271

**Comment by Sam90010** [comment]
This is the release version for stoneblock modpack. I tried deleting the game and reinstalling it though twitch. I've also tried deleting the minecraft folder and reinstalling and also deleted all the backup files. Nothing seems to work.

**Comment by Funwayguy** [comment]
Pretty sure I already fixed this. Can you make sure the BQ version installed is actually the latest first?

**Comment by Sam90010** [comment]
Updating to the newest version BetterQuesting-3.5.274 worked. Although I had to type bq_admin edit true to get it to update. Thank you.

**Comment by Funwayguy** [comment]
Not sure how the in game edit mode has anything to do with updating the JAR file but whatever works for you I guess...
