### ISSUE TITLE
getting this with the new update 05/11/2018

### ISSUE THREAD

**Issue by mattrix444** [Funwayguy/BetterQuesting#486]
https://pastebin.com/CRmn21Zc

**Comment by Funwayguy** [comment]
I don't think I've ever seen that kind of crash before. Not even sure where to start. Something odd happened to the filesystem while it was loading. Do you have any file restrictions that could be interfering with Minecraft's ability to read/write to those files? Does this still happen if you roll back and if not, which is the most recent version that worked?

**Comment by mattrix444** [comment]
since this last crash its not happened again.... typical it happens a bunch of times soon as i talk about it, it suddenly stops doing it haha. sorry to mess you around mate.

**Comment by Funwayguy** [comment]
That's fine. I'm sorta used to getting weird and wonderful errors as I'm rewriting BQ. If it does start happening again feel free to let me know.

**Comment by mattrix444** [comment]
no probs :) you can close this if you like since its not really an ongoing issue. thanks for the help
