### ISSUE TITLE
Backwards compatability failing in single player, possibly due to changed questbook?

### ISSUE THREAD

**Issue by McFrugal** [Funwayguy/BetterQuesting#49]
I have a QuestDatabase.json in a save file from before the quest progress was kept in a separate file.  Attempting to load that save wipes my questbook.

The DefaultQuests.json in the config directory has changed since that save file was made.  Will I need to manually update my QuestDatabase.json before the progress will be imported properly?
I'm attempting to upgrade to 1.0.124, though this also occurred in 1.0.121 and a couple of versions prior to that.  In Minecraft 1.7.10.

**Comment by Funwayguy** [comment]
Just to clarify but by wiping do you mean it deletes all the quests completely or just the progress and completion data associated with them?

**Comment by McFrugal** [comment]
The progress and completion data.
