### ISSUE TITLE
[1.12.2] Network Disconnect: A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by Column01** [Funwayguy/BetterQuesting#492]
A lot of our players have been having issues connecting to our servers, and the log always points to the BQM packets having an "unexpected changed in length." when the client attempts a connection with the server. [This](https://gist.github.com/Column01/75ce8d90086c0d55943ad99f7c8e430e) is an example of the log that the client gets after trying to connect to our server. As you can see, the stacktrace goes through the better questing packet handler, and spits out this error: 
>[21:28:55] [Netty Client IO 4/ERROR] [FML]: There was a critical exception handling a packet on channel BQ_NET_CHAN
>java.lang.RuntimeException: Unexpected change in BQ packet byte length: 4166 > 1832148

BQM Versions (that I know of): 
3.5.275 (StoneBlock modpack version: 1.0.26)
3.5.266 (FTB Continuum version: 1.5.2)
Both running triggerer version 1.0

It is a spongeforge server running quite a few plugins, but we do not have issues like this on any of our 1.12 servers except for the ones running BQM, and the logs all seem to tell the same story. The only fix we have come up with is to wipe the player's better questing data and that seems to fix the problem temporarily. Any help/insight is appreciated, and thanks for reading!

-Colin A.K.A. Column01

**Comment by Funwayguy** [comment]
Are you sure 275 has that issue because I specifically changed some code for that error in that build.

As for 266, not really much I can do to update a modpack to use newer builds. You'll have to ask the pack dev(s).

**Comment by Column01** [comment]
We have players that have had issues in that modpack but it updates frequently. Let me check the changelogs to see if it has been updated recently. I know that we will have to wait for continuum to update to a stable build, but I was just adding it as it is one of the main culprits (most reports come from it iirc)

**Comment by Column01** [comment]
Just checked, the mod has definitely been updated after these issues were reported so we can disregard for 275 then.  Thanks for your help, and I'll see if I can get on FTB's case to update the version for continuum.
