### ISSUE TITLE
[1.12][suggestion] merge flans mod+ changes with 1.12 build

### ISSUE THREAD

**Issue by mensreaMC** [Funwayguy/BetterQuesting#494]
Like the title says. The flans mod+ builds were basically third party modifications of flans that fixed a lot of features and added a lot more. I imagine a lot of it won't work, or won't work without basically rewriting it, but the flans mod+ builds have a lot of features and fixes that flans 1.12 is missing.

https://github.com/war-monger/Flan-s-Mod-Plus-War_Monger

https://github.com/Demitto/Flan-s-Mod-Plus

**Comment by Funwayguy** [comment]
Are you sure you're in the right place? This is the Better Questing issue tracker.

**Comment by mensreaMC** [comment]
Delete this lol.
