### ISSUE TITLE
Descriptions on quest pages / Your help book is empty

### ISSUE THREAD

**Issue by kindlich** [Funwayguy/BetterQuesting#5]
Hello!

I'ce tried adding some quests to a modpack of a friend to make the start easier. I got the Questline, Tasks and rewards shown as they should, however I can't make the description of the quests appear anywhere. I need them to explain the quests better, though...

I tried using your help book to find a command or something like that to make them appear on the quest page, but that book has only the register in it, the pages are empty....
I tried it on a MC build only using BQ and the BQ standart pack as well, still neither of the 2 things didn't worked...

Is there something I am mising?

**Comment by kindlich** [comment]
This is what I mean:

![helpbook](https://cloud.githubusercontent.com/assets/10351787/12070608/2d14ae02-b080-11e5-9538-153b3ce9b130.png)
![questbook](https://cloud.githubusercontent.com/assets/10351787/12070616/af44a3b4-b080-11e5-9dfd-4543c7e42f71.png)

**Comment by Funwayguy** [comment]
Seems like an odd rendering issue with scrolling text fields. I'll take a look at it but by the looks of it that weird bar on the left might have something to do with it. Perhaps its renderer is leaking onto other UIs. Any idea which mod it is from?

**Comment by kindlich** [comment]
It's from technomancy I think...
It doesnt work on a build with only BQ as well
I have no text on pages without scrollinf bar as well, just didnt upload a pic xD

**Comment by kindlich** [comment]
I just ported the Quest file on a build with only BQ + standart package installed, still the same

the 55 in the corner is the FPS tool added by overwolf, it's only overlay, doesnt do anything to the code

![vanilla](https://cloud.githubusercontent.com/assets/10351787/12071461/9772b4e6-b0ae-11e5-865d-cfb51826db5c.PNG)

**Comment by Funwayguy** [comment]
I'll play with the rendering of scrolling text and see if I can add some render leak counter measures. I'll also look into how technomancy is drawing that meter because they should never be rendered on top of other GUI screens.

**Comment by Funwayguy** [comment]
@kindlich Can you send me you QuestDatabase.json file. I can't seem to replicate this issue in order to debug it.

**Comment by kindlich** [comment]
I just posted both the QuestDatabase.json file as well as the EN_US.lang file from localizing it on pastebin.

Questdatabase.json:
http://pastebin.com/q7NmWEju

EN_US.lang:
http://pastebin.com/2hQDS2V9

**Comment by Funwayguy** [comment]
Using only Better Questing and the Standard Pack, descriptions loaded just fine:
http://puu.sh/ml3Cp/b67159ba3f.png

**Comment by kindlich** [comment]
Tried again, still the same, even if only forge BQ and the BQ standart pack are installed...
What Launcher/Version of Forge should are you using/developing for, maybe its because of that...

**Comment by Funwayguy** [comment]
@kindlich Better Questing is currently using 1448 in my dev workspace

**Comment by SvEgiiVEteR** [comment]
on 1.0.5 book is empty
and
http://hastebin.com/iyaqequtaq.avrasm
The error in the log.
every time I open a book.

**Comment by Funwayguy** [comment]
aww damn, I know why it works for me and nowhere else. Fix coming ASAP

**Comment by Funwayguy** [comment]
I've posted a fix for this in build 1.0.6, let me know how that works out.

**Comment by SvEgiiVEteR** [comment]
Now everything is OK, the text in place, thank you!)
Now I would have to understand how to use the mod ....)
