### ISSUE TITLE
Crash while editing description

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#508]
I ran into this crash while attempting to edit a quest line description. Other quest lines can be edited fine, and this one can be edited if I bring up the full text editor. I can't see anything obvious wrong, I've not done anything fancy.

https://paste.dimdev.org/asepewuxut.mccrash

![screenshot001154](https://user-images.githubusercontent.com/17183816/50046769-f6e73800-0076-11e9-8aff-259424ad2158.png)
I had to take a screenshot outside of the game as it appears that pressing any button that is mapped in keybindings triggers the crash, could be a clue.

Here's the quests file if it holds a clue:
[DefaultQuests.zip](https://github.com/Funwayguy/BetterQuesting/files/2683013/DefaultQuests.zip)

**Comment by Funwayguy** [comment]
Got it to crash in-dev and I think I know why. I forgot to specify the max text length in that specific box and it doesn't take kindly to trying to edit text larger than it should be (the code that failed was actually the failsafe meant to prevent this. How ironic)
