### ISSUE TITLE
Change Theme on Quest Completion?

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#51]
I just thought of this because at the beginning of my map, you get to choose between magic, tech, building, and adventure, and I was thinking it'd be cool if I was able to change the theme of the quest screen based on which of the four people choose. Is this already possible or a feature you'd be willing to implement?

**Comment by Funwayguy** [comment]
This is currently not possible but it could be implemented with a form of dynamic theme add-on without having to make any modifications to the base mod. I'm a little bit busy with other mods at the moment but if there are any modders willing to put one together I can let them know how to get such a feature working.

**Comment by ghost** [comment]
I could give it a shot. What do I need to do?
