### ISSUE TITLE
Suggestion: Option to auto-assign quest task and name when selecting icon

### ISSUE THREAD

**Issue by dr3ams** [Funwayguy/BetterQuesting#511]
It will save a lot of time. 
When you assigning an icon for quest it will take it name and assign it to the name of this quest. Perfectly it will assign retrieval quest with this item.

**Comment by Funwayguy** [comment]
Considering the retrieval task is part of the Standard Expansion and not the base mod and its editors, I'm going to say no.

This may also sound like a good idea for your use cases but for others I can see this being an annoyance. The tool is meant have one self contained purpose.
