### ISSUE TITLE
Client Crash - concurrent.ConcurrentHashMap

### ISSUE THREAD

**Issue by ProsperCraft** [Funwayguy/BetterQuesting#514]
I updated Ancient TownCraft and loaded in to a single player world to test the update and crashed within 15 seconds or so just walking around.

https://gist.github.com/ProsperCraft/6a30ae5449640b82aeb15dcae453d813

**Comment by ProsperCraft** [comment]
Repeated on making a new world and crashed in about 5 seconds.

https://paste.dimdev.org/madofoheqi.mccrash

**Comment by kreezxil** [comment]
confirmed on a dedicated server. I will roll down one version.

client crash report, server did not crash.

https://gist.github.com/kreezxil/275078d74d90c2edc7fda268e2a9414c

**Comment by Funwayguy** [comment]
Pretty sure this has long since been fixed in the release branch. Closing
