### ISSUE TITLE
Rolled back to 3.5.280 and getting client crashes when opening any quest.

### ISSUE THREAD

**Issue by ProsperCraft** [Funwayguy/BetterQuesting#515]
Happens in single player, and muli player - 

https://paste.dimdev.org/odinibuzen.mccrash

https://paste.dimdev.org/jexepexazo.mccrash

**Comment by ProsperCraft** [comment]
Well crud, it happens with 279 which used to work as well, could it be the forge update I had to do thanks to Astral Sorcery requiring a newer non-recommended forge?

https://paste.dimdev.org/poluzewepo.mccrash

**Comment by Funwayguy** [comment]
Seems you're still running the experimental version of the expansion

**Comment by ProsperCraft** [comment]
Yes, that was it thank you.
