### ISSUE TITLE
Option Server side to remove Auto Checking?

### ISSUE THREAD

**Issue by StoneLegion** [Funwayguy/BetterQuesting#517]
With a server of 15 People the game has become unplayable sadly because of BQ. We are using a large pack Enigmatica 2 Expert. I do understand nothing is perfect but I rather be able to disable all auto checking and have the users submit scans manually.

We would help train and warn users about this charge of course. At this point I'm going to have to limit the player count to say 6-7 people just because BQ is the leading cause the lag.

I also know lag goggles not perfect but this what it's showing with that many online now:
https://i.imgur.com/hjJOEzN.png

**Comment by Funwayguy** [comment]
You may be interested in trying the experimental builds. There's already a discussion on issue #509 to address a lot of this.

**Comment by StoneLegion** [comment]
Thanks @Funwayguy I'm actually using that build though I should consider updating to the 2nd build for the NPE issue. Were using with a server hit actually 16 today with a very large quest book.

That being said the performance shown and experiencing is sadly that of BQ. We even temp tried without BQ and noticed massive drastic performance Improvements.

The idea of this option be a optional config for server admins who have large numbers / large quest pack to help reduce most of the lag. That being said I do know that your trying to work on a proper solution but till then it might not be a bad idea if it's not a hard feature to add as right now it's getting to the point we either shutdown the server, limit the number of players in massive numbers or remove BQ.

Once again I know you guys are working hard and I will keep testing out bleeding edge builds that keep enhancing the performance of the server. I'm sure you don't see a lot of people using established packs willing to forge their users to change out mods by hand but I am and willing.

Thanks :)

**Comment by Funwayguy** [comment]
I'm going to consider this issue mostly resolved now that all the handling has been rewritten and properly cached for performance.
