### ISSUE TITLE
Breaking Quests/Random Auto Completing

### ISSUE THREAD

**Issue by FruityPewps** [Funwayguy/BetterQuesting#519]
![quest corruption](https://user-images.githubusercontent.com/45872135/50605295-2e2f5480-0e7f-11e9-8c58-6dbf77847bed.png)

The above was when running the command on a fresh save for testing. However, this occurs at any time. After editing/ testing quests and running the reset.

So this happens. When I run a reset all command in or out of edit mode it seems to produce varrying results. Not sure if derping on my end or what is going on. Running the latest BQ/BQS versions.

EDIT: Also, quests will randomly auto-complete on their own upon world load. I know this has been a continuing issue and I will try to pay attention to the log and see if it throws anything.

**Comment by FruityPewps** [comment]
This is what I got in the log when I ran the command:

`
Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: ID cannot be negative 	at java.util.concurrent.FutureTask.report(Unknown Source) 	at java.util.concurrent.FutureTask.get(Unknown Source) 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 	at java.lang.reflect.Method.invoke(Unknown Source) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.IllegalArgumentException: ID cannot be negative 	at betterquesting.api2.storage.BigDatabase.add(BigDatabase.java:66) 	at betterquesting.network.handlers.PktHandlerQuestSync.handleClient(PktHandlerQuestSync.java:36) 	at betterquesting.network.PacketQuesting$HandleClient.lambda$onMessage$0(PacketQuesting.java:110) 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 	at java.util.concurrent.FutureTask.run(Unknown Source) 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) 	... 9 more
`

EDIT: Same error when reloading with /bq_admin default load

**Comment by FruityPewps** [comment]
Lastest update may have fixed the corrupting when commands are run. The fatal is still there, but apparently looking at past issues *which I should have done sorry* it is known and ??intended??... so closing this for now.

If you ever need someone for large modpack testing I can help... as I am currently updating MSB3 and what not so I do a lot of large movement of the quest book.

**Comment by Funwayguy** [comment]
Funny that I didn't actually change any code todo with networking or commands just yet. None of this looks intended and the error is still a bit concerning. I wonder if it had anything to do with the quest cache.

As for testing, reporting what broken things you find is plenty.

**Comment by FruityPewps** [comment]
Yeah so far, just been having issue with the auto completing of quests randomly on world load, and corrupting with the commands being used. I ran a brief test today with the newest update... and it didn't break when I used a command so idk.

**Comment by FruityPewps** [comment]
@Funwayguy since the last 2 updates no longer getting book breaking upon command usage
The fatal will still occur at times. However, it isn't breaking things anymore. Progress.
