### ISSUE TITLE
Localise and document editor variables

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#52]
First off, I'm really sorry for spamming up your repo with issues, but I just keep thinking of things to say. I really like this mod and I want to see people using it more and more but I think something that will really turn users off is that creating quests can be very confusing. There are a lot of options for what you can do but some of the values you can edit have no localization and their names don't exactly explain what they do. I was thinking it'd make the interface way easier to use if there was a little ? bubble or something next to some of the options that you can click on and it further explains what that does. I'd actually be willing to document all the options for you if it makes it easier on you.

**Comment by Funwayguy** [comment]
I really like the idea of documenting the options however the editor is a raw JSON editor and isn't specific to any particular set of variables so it's very difficult to know where or what is currently being edited. If I can implements a form of JSON hierarchy tracking I can use that to generate localised variable names and documentation.

Feel free to post any improvement ideas you may have. It gives me a good idea for how the editors can be improved for pack developers and players alike.

**Comment by ghost** [comment]
Just curious, is this being implemented?

**Comment by Funwayguy** [comment]
Not this update but hopefully later down the track when I figure out a good way of implementing it

**Comment by Funwayguy** [comment]
I really should have updated this thread a while ago...
anyway, I implemented support for documentation tooltips and localisations on editor variables as of 2.x.x releases but me being lazy, I haven't written much, if any of it up yet. The prospect of writing out documentation for hundreds of variables isn't very motivating to be fair
