### ISSUE TITLE
Unable to claim reward.

### ISSUE THREAD

**Issue by remclave** [Funwayguy/BetterQuesting#520]
3.5.281

Okay. The quest is completed. I have a legitimate issue where I've chosen my reward but the Claim button just won't highlight.

![2019-01-02_16 50 29](https://user-images.githubusercontent.com/31051239/50616703-41f2af00-0eaf-11e9-9170-34e8baba28e5.png)

![2019-01-02_16 50 47](https://user-images.githubusercontent.com/31051239/50616706-46b76300-0eaf-11e9-85a7-df2b2d7d1f1d.png)

**Comment by remclave** [comment]
It does appear to be related to Choice-based claims.

**Comment by Funwayguy** [comment]
After selecting an option, does it work after leaving the screen and coming back? It's likely just a side effect of the UI refreshing events not yet being implemented (also sometimes makes the detect/submit button not change automatically if you have the screen open when it autocompletes)

**Comment by remclave** [comment]
Just got back from dinner... Nope. It doesn't work. Initially, (earlier that is) there was a weird blinking effect with the claim button and then it went dead.

**Comment by Funwayguy** [comment]
Odd... never seen it blink before.

Edit: Current code is a bit all over the place at the moment so I might not get to testing this right away

**Comment by remclave** [comment]
Yeah. It is weird. and when I logged in after a recipe fix, I tried the quest item again. For an Nth of a second I saw a flash and then it was off again...

**Comment by remclave** [comment]
I was finally able to claim the reward but that was after I restarted my pc.

**Comment by remclave** [comment]
I haven't had reports from any of our other players on our server experiencing this issue.

**Comment by remclave** [comment]
The problem has continued to plague our pack and I have finally determined how to actually trigger the claim button.

After selecting a choice reward, grab and move the slide bar down. This will activate the claim button.

**Comment by Funwayguy** [comment]
Finally got around to testing this (sorry about the delay) and yea this is a bit broken. I'll get it fixed up for the next Standard Expansion update. Hopefully shouldn't prove too difficult.

**Comment by ghost** [comment]
I put this in the E2E issue, but I thought I'd share what I found:
BQ can be made to light up the "claim" button by dragging the scroll bar for the reward selection box, even if there's no need to scroll.

**Comment by Funwayguy** [comment]
Yea that's because the GUI checks the states of things if something in the GUI was clicked but it doesn't work if the reward state was updated by say, a network packet from the server. This has been fixed in dev already for next release.

**Comment by ghost** [comment]
Great! Glad I could help. ;)

**Comment by Funwayguy** [comment]
Fixed in 292/293
