### ISSUE TITLE
Crash After Updating with NPC Integration

### ISSUE THREAD

**Issue by jelaw21** [Funwayguy/BetterQuesting#523]
Forge: 14.23.5.2796
Better Questing: 3.5.282
Better Questing: Standard:3.4.147
Better Questing NPC Integration: 3.4.25

I have a large questbook which has a number of Custom NPC dialog tasks. When I updated, I got this error report: 
[crash-2019-01-08_18.49.23-server.txt](https://github.com/Funwayguy/BetterQuesting/files/2738824/crash-2019-01-08_18.49.23-server.txt)

So I reloaded the save, loaded up fine the second time, but questbook was empty. However, the QuestDatabase in the save file is not. 

Quest Database in saved file: 
[QuestDatabase.txt](https://github.com/Funwayguy/BetterQuesting/files/2738836/QuestDatabase.txt)

so I did /bq_admin default load  and got an "unknown error had occured while ... " error.  

Default Quest Database:
[DefaultQuests.txt](https://github.com/Funwayguy/BetterQuesting/files/2738838/DefaultQuests.txt)

So it seems my old quests are not compatible with this new update. I don't want to redo all my quests.  How can I remedy this?

**Comment by Funwayguy** [comment]
I hadn't yet updated NPC Integration to work with build 282 but I've uploaded one just now. The quest data itself _should_ be fine as I haven't changed any formatting requirements. That said, you did run the default load so I'm not entirely sure what is and isn't going to be there.

**Comment by GreatOrator** [comment]
I can make this a separate issue if you wish, but it is N
[crash-2019-01-24_14.28.23-client.txt](https://github.com/Funwayguy/BetterQuesting/files/2793718/crash-2019-01-24_14.28.23-client.txt)
PC integration causing a crash with BQ

**Comment by jelaw21** [comment]
No, its fine. Thanks.

**Comment by Funwayguy** [comment]
Pretty sure this has been fixed for a while. Closing issue...
