### ISSUE TITLE
Server crash on starting 3.5.283

### ISSUE THREAD

**Issue by yaroslav4167** [Funwayguy/BetterQuesting#524]
Report: https://hastebin.com/odexicihuy.hs
Forge: 14.23.5.2805
Sponge: 1.12.2-2768-7.1.5-RC3516

**Comment by Funwayguy** [comment]
Whoops, forgot to isolate that client side code. I'll try and get a build out tomorrow to address this.

**Comment by ghost** [comment]
I have just ran into this problem aswell

**Comment by Funwayguy** [comment]
A fix for this has been uploaded to Curse Forge
