### ISSUE TITLE
Quests which are repeatable send completion message over and over

### ISSUE THREAD

**Issue by Luke616** [Funwayguy/BetterQuesting#527]
Hello,

I'm having an issue with BetterQuesting 3.5.284 in which once a repeatable quest is first finished, the player to receives the "quest complete" popup over and over. In my pack I've made a repeatable quest that requires a checkbox, runs the command "/bq_admin default load" and has a repeat timer of 1. When this command is completed, it now sends messages over and over. Eventually this causes the following error:
https://paste.dimdev.org/oburorahok.mccrash

Any help would be appreciated! Thanks!

Versions:
Better Questing 3.5.284
Standard Expansion 3.4.148
Minecraft 1.12.2
Forge 14.23.5.2807

**Comment by Funwayguy** [comment]
The first part of your issue involving the notification is actually a bug that I didn't pick up on. Not even sure how I missed it. I forgot to so much as even check quest claim states or progression before firing resets. That's my bad and I'll probably have an update out by tomorrow (if nothing else breaks before then).

The second part however isn't so much a bug but rather a side effect of trying to concurrently modify the quests while auto-claiming. People keep using `/bq_admin default load` in command rewards then wonder why it breaks things. I'm probably going to have to write a workaround for people who keep doing this, either that or blacklist such BQ admin commands from being used in such cases.

If you want to allow the user to auto update quests on their own and _without_ having to use cheat mode, make use of the versioning tags in the quest settings (same place you'd set the home background). BQ will notify and provide users with a one-click button to update once it detects a version difference.

**Comment by Luke616** [comment]
Oh! Did not realize that was a feature, thanks for the info! Guess I should have read up on the documentation a bit more.

**Comment by Funwayguy** [comment]
It's actually not in the documentation yet and was only added very recently. The docs are mostly written for 2.x.x and earlier and are missing a lot of new stuff I've been improving on since.

**Comment by Luke616** [comment]
Nice! I'll start using this feature for the future and let other packdevs know about it if I see them using /bq_admin default load in command rewards too
