### ISSUE TITLE
Major Console spam with Betterquesting

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#529]
Our console is being spammed by Capability QUEST_CACHE attached to player over and over and wont stop. Any ideas what's causing this?

**Comment by Funwayguy** [comment]
That's a debug line but I was sure that removed before the current release version although it shouldn't be getting spammed. Should only fire once per player (re)spawn or dimension change. What version are you using?

**Comment by ghost** [comment]
@Funwayguy if its fixed in the new version then don't worry about as I was not updated to the new version
