### ISSUE TITLE
Importing QuestDatabase.json from local results in double questlines

### ISSUE THREAD

**Issue by TinkerWorX** [Funwayguy/BetterQuesting#53]
As the title says, when I import QuestDatabase.json, I get double up on questlines.

**Comment by Funwayguy** [comment]
Do you have a before and after copy of your json file? (not the imported one)

**Comment by TinkerWorX** [comment]
This is the one I import: [QuestDatabase (before).json](https://gist.github.com/TinkerWorX/95be54b57585b0ea37ffbfecea6008c9#file-questdatabase-before-json)
This is how it looks afterwards, found in the Saves folder: [QuestDatabase (after).json](https://gist.github.com/TinkerWorX/95be54b57585b0ea37ffbfecea6008c9#file-questdatabase-after-json)
The array in "questLines" have been duplicated.

**Comment by Funwayguy** [comment]
I think I know what's happening here but just to be sure, you didn't have any existing quest lines before importing right?

**Comment by TinkerWorX** [comment]
None. I'm testing with fresh worlds. So basically, creating a world and then importing.

Related, is there a global way to add quests, so they're visible in all newly created worlds automatically?

**Comment by Funwayguy** [comment]
Okay thanks, I'll get that fixed up for you though I'm away on holiday so I might not get the update out for a while.

As for your question, once you are happy with your quest setup use:
/bq_admin default save

That makes it the default for new worlds
