### ISSUE TITLE
Adding new team member allows all completed quests to be claimed again, duping rewards

### ISSUE THREAD

**Issue by Goldenlion5648** [Funwayguy/BetterQuesting#532]

**Comment by Funwayguy** [comment]
Which version are you using? I cannot seem to recreate this in 3.5.287

**Comment by Goldenlion5648** [comment]
I'm playing Project Ozone 3 which is using 3.5.287

**Comment by Funwayguy** [comment]
Odd, changed the tasks I was testing with and it started happening. At least I can recreate it now. I'll see about getting a fix out for the next release build.

Update: Found and fixed it.
