### ISSUE TITLE
Crash with Object submission station 

### ISSUE THREAD

**Issue by mxnmnm** [Funwayguy/BetterQuesting#533]
https://paste.dimdev.org/doxazeboda.mccrash

I accidentally chose a quest that I hadn't worked on yet in the object submission station and I got this crash

**Comment by Funwayguy** [comment]
Lucky for you, I already stumbled across this one in-dev and have fixed it. As an added bonus it comes with a minor improvement to task panels updating themselves with progress changes. I need to finish up a bunch of editor tool upgrades and then I'll post build 289 which will get this fixed up for you. Thanks for the report anyway.
