### ISSUE TITLE
[PO3] Only one person on a team can submit progress toward reward

### ISSUE THREAD

**Issue by Goldenlion5648** [Funwayguy/BetterQuesting#534]
My party was trying to get the flight totem, which costs 768 RAQ (the pack currency), but only one of us was able to submit RAQ to make progress. Everyone else that submitted had their RAQ eaten, with no progress given. It might be relevant that this is a repeatable reward.

**Comment by Funwayguy** [comment]
That sounds like a really odd task setup and I'd have to contact the pack dev on how they've configured the quests. There's a good chance this isn't a bug but a pack setup issue.

**Comment by Funwayguy** [comment]
By "no progress given" do you mean they weren't given additional copies of the reward or the task itself wasn't accounting for the currency input of other members of the team?

**Comment by Goldenlion5648** [comment]
The task was not counting currency input from other team members

**Comment by Funwayguy** [comment]
Should be fixed as of BQ 3.5.294 and SE 3.4.153
