### ISSUE TITLE
Server only crash

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#536]
[crash-2019-01-29_18.00.16-server.txt](https://github.com/Funwayguy/BetterQuesting/files/2810273/crash-2019-01-29_18.00.16-server.txt)

There seems to be a conflict stemming from loot chests, the problem only occurred on startup of a dedicated server.

**Comment by Funwayguy** [comment]
Huh... odd. The item doesn't even make use of the THEME_REG variable but still crashes anyway. I'll have to change it back in the base mod.

EDIT: Fix has been submitted to Curse Forge
