### ISSUE TITLE
AA Oil Generator disabled

### ISSUE THREAD

**Issue by Lohoydo** [Funwayguy/BetterQuesting#537]
In the Actually Additions chapter there is a quest to make an Oil Generator, however this machine is disabled.  I've tried using bq_user refresh and admin load both, but the quest remains, making it incompleteable without cheating

**Comment by Funwayguy** [comment]
This is an issue for the modpack dev who setup the quests.

**Comment by Lohoydo** [comment]
Whoops, wasn't paying enough attention and thought I was on the modpack's git.  sorry
