### ISSUE TITLE
??? crash (changeme)

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#538]
https://paste.dimdev.org/xizukayufa.mccrash

**Comment by Funwayguy** [comment]
That's a first. Panel tried to refresh before it was even done setting up. I assume this was a one of crash? I can probably fix it but considering the unlikely circumstances required to trigger I'm probably going to hold off on a hotfix until the next major set of changes for a new build is done.

**Comment by Funwayguy** [comment]
Fixed for next update
