### ISSUE TITLE
[bug/suggestion] Location quest one axis

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#539]
As an idea for a misc quest, I thought it might be a good idea to include a location one for reaching the world border, because why not. Unfortunately, the location task type appears to require all 3 axis specified, I would like to request a wildcard be able to be specified.

Additionally, assuming I specify all 3, I get (ERROR) after the location name, hinting that there may be a bug
![screenshot001195](https://user-images.githubusercontent.com/17183816/52096763-0de5d900-2596-11e9-8a88-9a657b6b1c04.png)

**Comment by Funwayguy** [comment]
The error looks like a dimension ID lookup failure. Are you sure the ID is correct?

As for the location task, I could probably accomplish what you want by inverting the distance check so that you have to be X blocks away from the specified location. Specifically asking for a single coordinate parameter would probably better left to something like a scriptable task (something I want to add in future)

**Comment by ghost** [comment]
The ID is 0 (overworld). While I do have OTG handling things, the id is the same.

That sounds like it would result in the same problem, but in a different manner. I'll wait for the scripting. Is bumping against the world border or getting near it a detectable event?

In case you're curious, my plan was to have hidden x and y location quests and then have them autocomplete and use them as an OR for the main quest with the rewards.

**Comment by Funwayguy** [comment]
The inverted check would actually work just fine if its location is set to 0,0,0 and the distance to 29999980. I can probably add an option to use Manhattan distance math to make that more useful/accurate in your case.

Also I wouldn't hold out on that scriptable task support. Like a lot of the future content I want to add, there's a lot of more important stuff to finish first.

**Comment by ghost** [comment]
Oh I see. It doesn't need to be super precise, I had the range set at 25 or so, just to be where the world border would be right about in your face when you got it.

**Comment by ghost** [comment]
Thank you for implementing this.

As an addition, is it possible to make it so that you have to pass within a certain distance of the range to get it? say for instance 11 million +-50 blocks from 0,0,0 in any axis. It'd be nice to have as an anti-cheat (hide these, force players to go through them so they couldn't just tp to the edge).

**Comment by Funwayguy** [comment]
Considering you can hide the specific location information as part of the task options and the quest could run two location tasks in simultaneous mode if you really needed it, I'm probably not going to add a specific two part range check option right now. Wouldn't be too difficult to accomplish though so I'll think about it in a later update.

PS: If teleporting is already an allowable thing, you've kinda lost on the whole anti-cheat idea already. In that case it'd probably be more reliable to setup a scoreboard task hooked up to the distanced walked statistic.

**Comment by ghost** [comment]
I'll look into the simultaneous thing, perhaps I'm going about it wrong. I tried adding a couple of hidden quests with set distances but it didn't work as expected. I still have a lot to learn about BQ though.

As for teleporting to the world edge, technically it isn't possible without cheats. It's more of an attempt to thwart people doing things I didn't want them doing.
