### ISSUE TITLE
OSS consumes items but doesn't advance the quest

### ISSUE THREAD

**Issue by TinkerWorX** [Funwayguy/BetterQuesting#54]
It's simple to reproduce. Create a quest, create an OSS, target the quest, place a hopper, use the hopper to deliver items. The items disappear, but the quest doesn't register.

**Comment by Funwayguy** [comment]
Minecraft version? It might be relevant

**Comment by Funwayguy** [comment]
I've tested this in my dev environment but cannot recreate your issue. How is your task and OSS setup?

**Comment by TinkerWorX** [comment]
Sorry for the late response. This was tested with forge 1969 and BQ 126. I'll confirm that it's still a problem, and if so, get back to you.

**Comment by TinkerWorX** [comment]
Alright, I gave it a try with forge 1987 and BQ 130. It still happens. You can try it with the `16x Stone -> 1n` quest in this [collection](https://gist.github.com/TinkerWorX/dac0070e0f5ee3181e503e0c5c7890c2).

**Comment by Funwayguy** [comment]
Try setting the task to ignore NBT

**Comment by TinkerWorX** [comment]
That doesn't change anything, it still happens. I'll see if I can try it without any other mods. Maybe it's a bad interaction.

**Comment by Funwayguy** [comment]
It seems I was testing on the wrong version, my bad. Issue now confirmed. I'll try and get this fixed up for next update.

EDIT: I've found the bug and fixed it
