### ISSUE TITLE
Partys do not work properly

### ISSUE THREAD

**Issue by Koopamillion** [Funwayguy/BetterQuesting#540]
I am unable to join my friends party, leave one, or invite him and he is unable to join mine.

**Comment by Funwayguy** [comment]
Can you confirm if this is still happening after build 3.5.291?

**Comment by Koopamillion** [comment]
> Can you confirm if this is still happening after build 3.5.291?

They are fixed although now i get an internal server error, (i made a new issue) however this is 3.5.291
