### ISSUE TITLE
When a new player joins an existing party, all current members of party are able to reclaim quests.

### ISSUE THREAD

**Issue by hotdog218** [Funwayguy/BetterQuesting#546]
Enigmatica 2 Expert 1.5.4, Betterquesting version 3.5.288

It only seems to happen when the new player on the team claims a quest. For example, a new player joins and claims a thaumcraft reward, then the entire thaumcraft tree is reset to unclaimed for everyone who is already in the group.

**Comment by Funwayguy** [comment]
This was fixed in build 289 already (forgot to include it in the changelog notice though).
