### ISSUE TITLE
Automated OSS Suggestion

### ISSUE THREAD

**Issue by TinkerWorX** [Funwayguy/BetterQuesting#55]
For quests that support auto claim, it would be very useful to give the OSS the ability to automatically output items from the reward. For example by placing a hopper below it to extract the reward. This would be ideal for repeatable quests especially, to allow a constant reward through automation. Perfect for industrial/automation challenges.

**Comment by Funwayguy** [comment]
This would only work for item based rewards which is a very small subset of what the reward could potentially be. It would also not work if the rewards required user interaction like the choice rewards. Another problem would be that the reward could consist of millions of items which would make things difficult to process and save to NBT without overloading something along the way.

As much as this idea seems useful for automation, the technical hurdles involved for such a small subset of rewards doesn't seem worth it.
