### ISSUE TITLE
[Question for NBT strings]

### ISSUE THREAD

**Issue by Freebi85** [Funwayguy/BetterQuesting#551]
Hello =)

Is there a way to customize the NBT data of an item for the quest to recognize it?

For example this jetpack is not recognized. But I can't ignore the NBT data otherwise every jetpack recognizes it because the stupid mod designed the items that way.
<simplyjetpacks:itemjetpack:10>.withTag({Energy: 0, JetpackParticleType: 0})

I'd have to shorten the NBT tag maually for the book to recognize the jetpack.
Like this: <simplyjetpacks:itemjetpack:10>

is this possible?^^

**Comment by Funwayguy** [comment]
Of course. When editing the item list, click the `...` button net to the item you wish to modify and select `Raw NBT`. Here you'll be able to add, edit and remove whatever NBT tags you choose. After this make sure the task is set to use `partialMatch` and you should be all setup. The task will now only match against the tags you've specified and ignore the rest. This approach also still works against ore dictionary items so for example, you can search for any type of pickaxe with a specific enchantment NBT tag.

**Comment by Freebi85** [comment]
Ah awesom! So wehen i delete all "tag" entries then all I have left is the item without the extended nbt tag?

**Comment by Funwayguy** [comment]
Yes but at that point you might as well just use the `ignoreNBT` option in the task properties.
