### ISSUE TITLE
[Suggestion] Improvements to Advancements Selection

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#552]
Advancements are listed in a jumbled mess order. It would be nice to put them in some sort of order (such as by mod or alphabetical). It could also do with a search function.

Add-on: How hard would it be to add a thing for detecting the completion of every advancement? This is more of for my misc "congrats, you put in a lot of effort" set of quests.

**Comment by Funwayguy** [comment]
Nice and sorted with a search bar now. Will be included in the next SE update:
![image](https://user-images.githubusercontent.com/6048596/53318969-c34d4780-391c-11e9-931e-ba56511bce97.png)

EDIT: You could add several tasks that point to the end of each advancement tree. Alternatively it might be better to use something like Triumph to make an advancement with that condition in mind.

**Comment by ghost** [comment]
Thank ye very kindly :D

That was a considered method, but by the time you get through doing that for the 25+ mods/vanilla in my pack that include them it turns into a mess even including one per tab, let alone the 4-5 some require. I'll give triumph a look, thanks :)
