### ISSUE TITLE
Project Ozone 3 quest reset.

### ISSUE THREAD

**Issue by lespaul5895** [Funwayguy/BetterQuesting#557]
I've been playing PO3 for a couple of weeks now in single player.  Today for some reason while playing my quest book disappeared (the quest book would still open but nothing was in the book).

I went to my latest 4 backups but they all seem to have the same issue.  So reinstalled that file after backing up the old and lost all of my quest progress.

I'm having a hard time going through completing all of the quests I already did as there's no "quick complete" function that I can find, only the "/bq_admin complete" command.  This wouldn't be an issue, but holding down shift doesn't display the quest number for some reason.  SO it's a complete guessing game.

Is there any way that I haven't found to use cheat mode to complete quests without the command, or is there a way to re enable the holding shift showing me the quest number?

**Comment by Yakaita** [comment]
/bq_admin edit 
- turn this on
-open the book and in the designer for the quest lines there should be a button that completes the quets you press on
complete the ones you did
/bq_admin edit off
make sure you turn it off or you cant complete quests regularly again

**Comment by lespaul5895** [comment]
> /bq_admin edit
> 
> * turn this on
>   -open the book and in the designer for the quest lines there should be a button that completes the quets you press on
>   complete the ones you did
>   /bq_admin edit off
>   make sure you turn it off or you cant complete quests regularly again

I'm not seeing what you're referring to.  I've clicked in each menu but I'm not seeing it.

https://i.imgur.com/8oaJAlD.png

**Comment by Yakaita** [comment]
![2019-03-02_11 13 59](https://user-images.githubusercontent.com/42159319/53684516-64048400-3cdc-11e9-8587-5b2f08edcbc8.png)
![2019-03-02_11 14 10](https://user-images.githubusercontent.com/42159319/53684517-649d1a80-3cdc-11e9-8537-57b059fc13e4.png)

![2019-03-02_11 14 16](https://user-images.githubusercontent.com/42159319/53684515-64048400-3cdc-11e9-9349-0d3e6873d3f1.png)

**Comment by lespaul5895** [comment]
> /bq_admin edit
> 
> * turn this on
>   -open the book and in the designer for the quest lines there should be a button that completes the quets you press on
>   complete the ones you did
>   /bq_admin edit off
>   make sure you turn it off or you cant complete quests regularly again

Dude, you're my hero.  THANKS SO MUCH!
