### ISSUE TITLE
Edit mode breaking slightly

### ISSUE THREAD

**Issue by Cazadorsniper** [Funwayguy/BetterQuesting#558]
I'm trying out edit mode in BQ 3.5.292 and BQ:SE 3.4.152 and if I edit 1 quest I can't immediately edit another, I have to exit to questlines then go back to the quest to edit it.

**Comment by Cazadorsniper** [comment]
Within the designer to clarify.

**Comment by Funwayguy** [comment]
It was a little more than "slightly" broken but I've uploaded build 293 to Curse to get that resolved along with a few other minor fixes.
