### ISSUE TITLE
1.7.10 crash - Item Loot Chest method missing

### ISSUE THREAD

**Issue by Yzjdriel** [Funwayguy/BetterQuesting#56]
I have 137 other mods, so I downloaded just the base mod before adding packs to see if there were conflicts since I didn't want to get my hopes up.

The good news?  No conflicts.  XD

The bad news?  After downloading just the standard pack, my launcher crashed.

I was given a NoSuchMethodError when I tried to launch.  The relevant line in the crash report:

```
Description: There was a severe problem during mod loading that has caused the game to fail

Caused by: java.lang.NoSuchMethodError: bq_standard.items.ItemLootChest.setMaxStackSize(I)Lnet/minecraft/item/Item;
    at ((path))
```

**Comment by Funwayguy** [comment]
Do you have the full crash report because the whole file is relevant not just that line.

**Comment by Yzjdriel** [comment]
Did it not attach to the op?  Appears not.  I'll try again.
[crash-2016-06-23_19.25.11-client.txt](https://github.com/Funwayguy/BetterQuesting/files/335316/crash-2016-06-23_19.25.11-client.txt)

**Comment by Funwayguy** [comment]
Seems you installed the developer version (deobfuscated) of Standard Expansion instead of the release version. Installing the correct version should resolve your crash.
