### ISSUE TITLE
Recent Version broke colors of overworld theme

### ISSUE THREAD

**Issue by Darkmega18** [Funwayguy/BetterQuesting#561]
As the name suggests, a recent update seems to have broken the color formatting or changed it for the overworld theme and possibly others. As when I checked my quests just now ingame some of the main worlds that used to be white become black on gray.
![image](https://user-images.githubusercontent.com/8104689/53866890-ba5c2480-4046-11e9-8abf-e030d12fad46.png)
quest text also went bust it seems.
![image](https://user-images.githubusercontent.com/8104689/53866974-ea0b2c80-4046-11e9-86f0-c8f6445c5875.png)

but it's fine in popups.
![image](https://user-images.githubusercontent.com/8104689/53867010-ff805680-4046-11e9-9901-53958b7a32ae.png)

standard dark still works out though:
![image](https://user-images.githubusercontent.com/8104689/53867063-1d4dbb80-4047-11e9-8977-e404b8156045.png)

(also, yeah, still having that optifine thing, but thats just the optifine thing that you said you couldn't fix or see how to fix)

**Comment by Funwayguy** [comment]
Is this version 152 of Standard Expansion? Because for me it looks fine:
![image](https://user-images.githubusercontent.com/6048596/53874281-d6af8f80-404d-11e9-8520-a2a849398fe2.png)

At first I thought it could be a JSON reading issue but that would cause issues for other themes, not just this one. Weird how isolated this seems.

**Comment by Darkmega18** [comment]
BetterQuesting-3.5.293.jar and StandardExpansion-3.4.152.jar.

heckin oof. :V are you telling me something you might've done recently once more doesn't like optifine perhaps? D: But I swear it was fine when I played on the server the other day... although I never checked it today when I just updated. should I backdate and take a check at some point?

**Comment by Funwayguy** [comment]
Thing is I only changed how the themes are loaded in, not how they render text. Once loaded they should be functionally the same as they were before. To make matters more interesting, Overworld is set to inherit text colours from the Dark theme which as you've show works fine. I am reaaaally confused how the heck you got this to happen. Is it happening on any other theme or just this one by chance?

**Comment by Funwayguy** [comment]
Just had a crazy theory of what could have happened. Need to go do some reading on the GSON library and if the JSON array read order is consistent. If not that could break the parenting and the colour inheritance.

EDIT: Nope. JsonArray read order is the same as it's written. The broken parenting idea still has some potential... but how if the parent is known working already?

_thinks to self_

I'll have to do some digging on this tomorrow.

**Comment by Darkmega18** [comment]
standard dark worked as shown, but overworld and I think stronghold theme was doing it with only the editable text/name colors. I haven't gone into it and checked stuff yet because was catching up on some warframe stuff with friends and I gotta get off now, But if you want to investigate it deeper before I get onto it get my modpack, Transcendence (cause you could potentially have a nice faster computer that can load the pack a lot quicker than my 5-10 minutes depending on computer's mood). 

Check version 0.2.0 first where i remember it working, then check 0.2.1 where I updated only a few mods and changed some configs etc. and if nothing happens, attempt latest current version of optifine with either or both to see if it's yet another opti-screw.

**Comment by Darkmega18** [comment]
so I loaded my newest version up and I got this:
![image](https://user-images.githubusercontent.com/8104689/53932231-bedb1880-40ec-11e9-9efb-02ac89ad4b60.png)

it's like, "windows current theme isn't compatible with your program, do you want to set it to classic mode?" or whatever that error that happens in some old games is. xD

Overworld, Nether, Stronghold, all have the black written text it seems. is it a quest loading/saving/reading issue perhaps...?

**Comment by Funwayguy** [comment]
That's a very interesting screenshot you've got there. Those are the fallback textures (slightly different to vanilla) and something has gone very wrong to end up in that state (or somehow set to an invalid theme ID in the config). Your game instance just seems to be the gift that keeps keeps on giving when it comes to weird and wonderful visual bugs.

Just out of curiosity, can you put together a clean MC instance with just BQ and SE installed and test that. Want to see if it's a system related IO issue or some wacky cross-mod interference somehow.

**Comment by Darkmega18** [comment]
I can do that. it won't be able to load my quests without some serious jank though to test for load issues. :V

**Comment by Darkmega18** [comment]
So is this not meant to happen? I thought this was the vanilla theme?
![image](https://user-images.githubusercontent.com/8104689/53974902-c2f05000-4157-11e9-8daa-c1387d64a9ee.png)
overworld example text etc are still black instead of white. :V 
![image](https://user-images.githubusercontent.com/8104689/53974945-e1564b80-4157-11e9-9c53-01e5b5699e8d.png)

only one where the written text is white like it should be is standard dark.
![image](https://user-images.githubusercontent.com/8104689/53975021-0f3b9000-4158-11e9-9641-44bcaf920db6.png)

Bonus picture: [oof]
![image](https://user-images.githubusercontent.com/8104689/53975119-398d4d80-4158-11e9-85b2-e20e6c53beb1.png)
could a java version be doing this? One other has mentioned that his quests had switched to vanilla mod but retained my backing image for the main screen and stuff.

**Comment by Funwayguy** [comment]
This is crazy.

Is there any errors in your logs related to theme parsing?

EDIT: Not sure if it has any effect on this issue but I noticed that the file reading code wasn't set to use proper UTF8 encoding so I've changed that out for 294 whenever that gets released.

**Comment by Funwayguy** [comment]
Uhhhhh... okay then Minecraft.

Randomly started happening to me today.
![image](https://user-images.githubusercontent.com/6048596/54009272-e34ef780-41b5-11e9-945a-6008427facde.png)

Well at least I can start debugging it. Still have no idea how it's doing this though 🤔 

Bonus Fact: This was after the UTF8 fix and there's still no parsing errors in the log. This is going to be a fun one to figure out.

**Comment by Darkmega18** [comment]
did you actually change anything to do with text or themes in the last 3 or 4 uploaded versions? cause it hasn't happened before except with these last 2 after there was something like: "Added an all new JSON theme loading system with much more powerful capabilities"

whatever that was. Cause pretty sure 0.2.0 in my modpack had the version prior to that from feb 7 and it was fine. so probably start there since this seems to be something related to themes, but only some specific themes that have the default color of customizable text edited.

**Comment by Funwayguy** [comment]
Oh I know it has something to do with the change to JSON but my first screenshot of it working was using that new system. This is literally the first time since implementing it that it has flipped out on me like this, even during testing.

**Comment by Darkmega18** [comment]
sure it didn't just bug and you didn't switch it over? cause I got no idea or than what I'm seeing. I'm just starting up game with the versions which weren't from a few days ago. gimme a sec.

**Comment by Darkmega18** [comment]
thats done it. they're also in a much different order it seems. vanilla theme still seems to be there, but at the bottom.
![image](https://user-images.githubusercontent.com/8104689/54013018-e9e86980-41cb-11e9-9d8e-0fa980efb557.png)
![image](https://user-images.githubusercontent.com/8104689/54013077-18664480-41cc-11e9-870c-dee5773a5a91.png)

**Comment by Funwayguy** [comment]
Yea those are all the hardcoded version of the themes so I'm not all that surprised they still work. The order is just because the newer versions have the listing sorted in alphabetical order (although vanilla still doesn't feel like abiding by that order for whatever reason).

My debugging did turn up something... interesting:
![image](https://user-images.githubusercontent.com/6048596/54013921-9f182300-41c6-11e9-8737-b0dc8d146ce4.png)

I kinda feel dumb now that I somehow double-stacked the domain names on theme IDs.

EDIT: It's now fixed in dev for next version and with that the saga of weird theme colours comes to an end 👌

**Comment by Darkmega18** [comment]
Well played. GG. I hope I can get that relatively soonish then. meanwhile my quests in my minor update will just have to use standard dark in the meantime for readability.
