### ISSUE TITLE
Sometimes, items have to be dropped and picked back up for a quest to register them

### ISSUE THREAD

**Issue by Dimentive** [Funwayguy/BetterQuesting#563]
I’m playing [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.61](https://minecraft.curseforge.com/projects/enigmatica2/files/2684481) for Minecraft 1.12.2), and sometimes, both I and the person I’m playing with have to sometimes drop the items we need for a quest and then pick them back up again to get the game to register that we have the items; clicking “Detect/Submit” doesn’t do anything. This happens if we grab the items we need for a quest from a chest or other inventory.

This isn’t a major problem, as it doesn’t take that long to drop items and pick them back up, and the quests are still obtainable, but I thought I’d let you know anyway.

I’m not sure if this is a problem with the mod or the modpack.

**Comment by Funwayguy** [comment]
Is this using the early build I gave you? The interesting thing about this report is that the pickup and detect events point to the same checking code in retrieval tasks so why one works and the other doesn't is rather odd to me.

**Comment by Dimentive** [comment]
Yes, I’m using the early build.

**Comment by Dimentive** [comment]
Yes, we’re using the early build.

**Comment by Funwayguy** [comment]
Just confirming that yes, this is indeed busted somehow and I can recreate it in dev. Considering it's not game breaking nor requires much testing to validate a fix, I probably won't need to send you a new test build... but if you _reaaaaaaally_ need it after I find and fix the bug, let me know.

**Comment by Dimentive** [comment]
If you send us a new early build, we’ll use it, but like you say, it’s nothing major, so it’s not _that_ essential. It’s a fix that would be nice to have in the next release of the mod, though.

**Comment by Dimentive** [comment]
If you send us a new early build, we’ll use it, but as you say, it’s nothing major, so it’s not _that_ essential. It’s a fix that would be nice to have in the next release of the mod, though.

**Comment by Funwayguy** [comment]
Found the bug. Silly me made the checks fail early on the first empty slot. Considering a pickup aims for that slot first, that's why that seemed to always work. Anyway, it's fixed for the next update. In the mean time just keep that bug in mind. It's annoying but easy to workaround.

**Comment by Dimentive** [comment]
Awesome! That was quick.

**Comment by Funwayguy** [comment]
It seems quick, but there are plenty of other bugs I need to get to fixing up before release. For example, this and your previous report needs to be applied to fluid tasks as well and I still need to go through every other task type to make sure there aren't similar stupid mistakes I've made (I've already found a few).

**Comment by Dimentive** [comment]
Well, I really appreciate that you’re squashing these bugs, and I’m very grateful for the early build that fixed #562. 👍
