### ISSUE TITLE
Odd quest glitch

### ISSUE THREAD

**Issue by Humongous** [Funwayguy/BetterQuesting#565]
Ever since yesterday, I've been having this issue where, if you were to go onto a quest line in designer mode, doing anything that would change the quests would crash the game, such as moving them. Also, if you zoom out, they all disappear, and creating a new quest would crash the game. This only started happening since yesterday, and there doesn't seem to be any reason for this. I'm running 1.12.2-14.23.5.2808.

**Comment by Funwayguy** [comment]
Do you have the crash report? I can't really debug this much without it.

**Comment by Humongous** [comment]
Whenever it crashes, I don't recieve any kind of crash report and the game just closes. Nothing exactly describing why it crashed. It'll freeze for a couple seconds, then promptly close with no report of any kind.

**Comment by Funwayguy** [comment]
Anything in the logs by chance?

Crashing without a report usually isn't a good sign especially if nothing has been changed in your instance. The freezing is also concerning. I suspect there's something outside of Minecraft contributing to this but why that screen specifically triggers it I don't know.

**Comment by bittergg** [comment]
i have the same issue, there's nothing in logs or in crash logs
EDIT: i've found something on my server, where i'm making quests : `121piotr121 lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer`
and right after it: `Mar 17, 2019 4:23:21 PM io.netty.util.ResourceLeakDetector reportUntracedLeak SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.`

EDIT2: suprisingly, crashes do not happen to my friend, who is also on my server

**Comment by Humongous** [comment]
Yeah, can confirm that we're both having the same problem. Got this message from my server.

>  Hamangas lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

**Comment by DevTimur** [comment]
Yes, got similar issue, exept i don't crash. Game just freeze
Forge-1.12.2-14.23.5.2807-universal
BetterQuesting-3.5.294.jar (also 293 got same issue, other versions didn't test)

Way to re-create issues:
Issue 1: set /bq_admin edit ON
Open EDIT mode for quests, try to move screen, icons will just dissapear as if you go to unknown coords.
https://i.gyazo.com/9a4f9053bcec767c2de739117b5b4dc8.gif

Issue 2: (Continuation of issue 1?)
Open EDIT mode for quests, **switch to icon move mode**, try to move screen, game just froze.
https://i.gyazo.com/441bcc3038467f76fe92a5042f79b1bc.gif

**Comment by Funwayguy** [comment]
The server side errors you two are seeing are a symptom of the crash not the cause. Seems the crash was so uncontrolled that not even the networking had a chance to shutdown and the server just errored out on the cut connections.

I have no idea if the forge version has anything to do with it considering I develop on version 2768 but I'll whip up clean MultiMC instances with 2808 and 2768 and see if that changes anything between them.

**Comment by DevTimur** [comment]
update
BetterQuesting-3.5.291 does not have this issue, with same 2807 forge
update 2
BetterQuesting-3.5.292 **do** have this issue, with same 2807 forge
See what you deed in between :)

**Comment by Funwayguy** [comment]
Well this is interesting. Managed to recreated it in 2768 both release builds and in-dev. How did I miss this? I use the designer all the time for testing and should have run into this before.

Also just to clarify for future reference, isn't a crash but rather a soft lock. Profiling tests shows what seems to be an infinite loop in the grid rendering (hence why it's specific to that screen and not immediate).

So far I've fixed the infinite loop but the designer is still behaving _really_ strangely with drag navigation completely non-functional. The infinite loop appears to be the side effect of something much more broken under the surface.

**Comment by Slowwloriss** [comment]
+1 to that glitch. I have that thing when im in the designer and i scroll whit mouse wheel the game crash.  the same like the autor of the post. Nice mod Funwayguy i apreciate it.

**Comment by Funwayguy** [comment]
Although I've fixed the freezing (actually sped up some render math doing so) I'm still working on pinning down the second cause of the issue. Somehow the scroll values are snapping to the integer limit of 2.14B. Might have something to do with a math error somewhere in the new scroll smoothing introduced in build 292. I'll update the issue if I find anything.

**Comment by Funwayguy** [comment]
Found the second issue. Integer overflow in the smoothing math as suspected. Caused by a lazy long to integer cast on this line in particular:
https://github.com/Funwayguy/BetterQuesting/blob/1.12/src/main/java/betterquesting/api2/client/gui/controls/io/FloatSimpleIO.java#L57

Currently fixed for next build but I need to clean up a few WIP stuff before I can prepare it for release.

**Comment by Humongous** [comment]
Sounds good. Hopefully there isn't any other errors, but I doubt there will be any left. Great mod, btw.

**Comment by Funwayguy** [comment]
Closing issue now that the fixed build has been published.
