### ISSUE TITLE
Crafting Task Not working it seems

### ISSUE THREAD

**Issue by BedrockLegends** [Funwayguy/BetterQuesting#567]
I have Tinker's Smeltry set up as a crafting task in my pack but when anyone craft said item that is under crafting task it does not work, I have tested this with ignore NBT and without and still nothing.

**Comment by Funwayguy** [comment]
What method of crafting are you using? Crafting tasks don't work on a lot of things and are mainly meant for non-automated methods like crafting tables, anvils and furnaces.

**Comment by AdaraChristine** [comment]
I had the same problem. I was using the minecraft crafting table. I reverted back to version BetterQuesting-3.5.291  and it worked.

**Comment by Funwayguy** [comment]
Crafting tasks seem to be detecting just fine on my end as of BQ 3.5.295 and SE 3.4.253. Are you sure you didn't run into the bug in SE 3.4.149 which defaulted all crafting detection methods to disabled? They should look like this in later versions where the tick marks denote what's allowed:
![image](https://user-images.githubusercontent.com/6048596/54975778-f0584d00-4fe3-11e9-83c4-46cf4cab31a0.png)
