### ISSUE TITLE
[Suggestion] Database file improvement

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#568]
I would like to suggest that the quests json file save all variables set for a quest, even if they're default. Yes, it would make the file a tad bigger, but would prevent the following:

I realized that I need to change a bunch of quests (150+) from normal visibility to unlocked visibility because they're showing up when they shouldn't and causing a lot of brokenness. Instead of this being a simple 5 second replace task in n++ I now have to spend a lot of time in the designer going through every single quest to change this.

**Comment by Funwayguy** [comment]
It already should be saved to the file. I've never intentionally excluded default variables.

**Comment by ghost** [comment]
In that case it isn't. I searched for '"visibility:8"' before and after going through everything and it went from 21 or so to 160+. Here's a screenshot of before (left from my prior pack update) and right (after I went through everything), notice before doesn't have a visibility tag.

![Screenshot001240](https://user-images.githubusercontent.com/17183816/54960871-e3305500-4f34-11e9-9181-ccd50f085e31.png)

**Comment by Funwayguy** [comment]
The other defaults appear to be there except that one. I think I might know where that issue is so I'll take a look at that today.

In the mean time you could try doing a find-and-replace on another default tag and append the visibility tag after it (would leave duplicates on the one's you've already done though)

**Comment by ghost** [comment]
I thought about that initially, but decided I didn't want to risk breaking something so I did it manually. It also forced me to comb over everything, which was helpful.

**Comment by Funwayguy** [comment]
Build 3.5.296 is now up on Curse Forge. Should generate populate all the default visibility values for you.
