### ISSUE TITLE
Location Task - Current Location

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#57]
This kind of seems like an oversight or something, but could you add a button in the creation menu of location tasks that sets the destination to your current location? It would make things a bit simpler.

Oh, and while I'm here, how do you make completion of one quest lock other quests?

**Comment by Funwayguy** [comment]
I'll try and add a quick location button in at a later date.

Locking other quests involves setting up the correct 'Quest Logic'. It might be worth looking up Logic Gates if you don't know what each of the options mean. If you wanted something along the lines of what HQM does, you'd likely want NOR logic linking optional quest together (allows only one to complete then locks the others) and possibly set the visibility to show only when unlocked (hides the optional quests when unavailable)

**Comment by ghost** [comment]
I understand how logic gates work, so do I just set them all to NOR and link them all to the same parent quest?

**Comment by Funwayguy** [comment]
Yes link them to the parent quest AND all of the optional quests (they need to be aware of each other's state). If you have a parent quest XOR logic might work better for you

EDIT: I should really make a whole wiki page on how this works and examples

**Comment by ghost** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10859516/16546987/827dc442-412a-11e6-98c2-cf0cc328c334.png)
So I have something like this. The nether star is the parent quest. It has AND logic and is set to be a main quest. Each of the three child quests are linked to the parent quest and each other like you said and have XOR logic. They are set isMain = false. Even though after I completed the quest on the left, it greyed out the others, it still allowed me to complete them for some reason. Why is this?

**Comment by Funwayguy** [comment]
You are still in edit mode I presume

**Comment by ghost** [comment]
Oh alright I see.
