### ISSUE TITLE
Suggestion! Hardcore Server Improvement

### ISSUE THREAD

**Issue by SirAron111** [Funwayguy/BetterQuesting#575]
Suggestion! Option for Hardcore questing mode command to be player targeted at the player using it instead of simply activating hardcore mode for everyone on the server.

There is currently a big problem with having the hardcore mode activated with a quest and that is that if a player on a server activates it everyone in the server gets set to hardcore and not just the player using it. Is it not possible to make this command target only the player who claimed the quest?  (There is an option 0/1 to set the commands by player but that doesn’t work)

**Comment by SirAron111** [comment]
Also for some reason Hardcore sometimes resets and turns itself off without anyone using a quest to do so. (Or is that because I made the hardcore enable quest using the command a repeatable quest with /bq_admin hardcore true as the command reward? But I have to make it repeatable or else if it turns itself of people won’t have away to turn it on again)

**Comment by Funwayguy** [comment]
That's a bug I've fixed in dev. Currently busy working on SF4 so I don't have an ETA on the build release
