### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#58]
After we edit a Quest on my Server we get this crash:

https://gist.github.com/Dream-Master/8b86ae77702c27d5b458f13a78e2fd9c

Modpack : https://github.com/GTNewHorizons/NewHorizons

Better Questin 1.0.124
Standart Expansion 1.0.81

(Yes i know there is a more up to date version but at the time i update the server we not have this files. Are this bug fixed with a newer Version?)

**Comment by SanMan911** [comment]
Yeah, and what's weird, is that the quest works perfectly fine in Single Player. It's just Multi Player that seems to be bugged :/

**Comment by Funwayguy** [comment]
It appears that an item somewhere has been registered with null names server side. Any idea which mod or item may be doing this?

EDIT: It might also be beneficial to post the JSON for that particular quest if possible

**Comment by Dream-Master** [comment]
sure these are the whole Questfile:  

https://raw.githubusercontent.com/GTNewHorizons/NewHorizons/master/config/betterquesting/DefaultQuests.json

and the Quest we try to edit. 

```
{
      "questID": 237,
      "name": "\"Stores 50 Vis\" Wand",
      "description": "Now combine your new wand, and be more powerfull than before! You have a feeling, that this new wand will become handy very soon",
      "isMain": false,
      "isSilent": false,
      "lockedProgress": false,
      "simultaneous": false,
      "globalParticipation": 0.0,
      "globalQuest": false,
      "globalShare": true,
      "autoClaim": false,
      "repeatTime": -1,
      "sounds": {
        "complete": "random.levelup",
        "update": "random.levelup"
      },
      "logic": "AND",
      "taskLogic": "AND",
      "icon": {
        "id": "Thaumcraft:WandCasting",
        "Count": 1,
        "OreDict": "",
        "Damage": 9,
        "tag": {
          "aqua": 5000,
          "ignis": 5000,
          "terra": 5000,
          "cap": "gold",
          "rod": "greatwood",
          "ordo": 5000,
          "perditio": 5000,
          "aer": 5000
        }
      },
      "visibility": "UNLOCKED",
      "tasks": [
        {
          "partialMatch": true,
          "ignoreNBT": false,
          "consume": false,
          "autoConsume": false,
          "requiredItems": [
            {
              "id": "Thaumcraft:WandCasting",
              "Count": 1,
              "OreDict": "",
              "Damage": 9,
              "tag": {
                "aqua": 5000,
                "ignis": 5000,
                "terra": 5000,
                "cap": "gold",
                "rod": "greatwood",
                "ordo": 5000,
                "perditio": 5000,
                "aer": 5000
              }
            }
          ],
          "taskID": "bq_standard:retrieval"
        }
      ],
      "rewards": [
        {
          "rewards": [
            {
              "id": "Thaumcraft:ItemLootBag",
              "Count": 1,
              "OreDict": "",
              "Damage": 1
            }
          ],
          "rewardID": "bq_standard:item"
        },
        {
          "rewards": [
            {
              "id": "dreamcraft:item.CoinDarkWizard",
              "Count": 10,
              "OreDict": "",
              "Damage": 0
            }
          ],
          "rewardID": "bq_standard:item"
        }
      ],
      "preRequisites": [
        234,
        235,
        236
      ]
    }
```

**Comment by Funwayguy** [comment]
Which item were you trying to edit?

**Comment by SanMan911** [comment]
We were trying to edit the Iron capped wooden wand of the <<"50 vis storage" wand>> quest logically require a gold capped greatwood wand.

**Comment by Dream-Master** [comment]
Wands using NBT Data.

**Comment by Funwayguy** [comment]
Seems this bug doesn't occur in newer versions of Better Questing:
http://puu.sh/pVylm/7fd3bf456c.png
http://puu.sh/pVyrk/28e977b60c.png

I did change slightly how items are saved/loaded so that NBT formatting is preserved in later versions. Might want to consider updating Better Questing if you want to continue using Thaumcraft.

**Comment by Dream-Master** [comment]
ok then i will update the server as soon as possible and report back to you.

**Comment by Dream-Master** [comment]
Ok this is fixed with newer version. Thanks
