### ISSUE TITLE
Cant edit and view quest

### ISSUE THREAD

**Issue by cyber01** [Funwayguy/BetterQuesting#581]
I again launched modpak, which I hadn’t launched (and didn’t change) for a long time, but could not open or view quests. All quests look like this: https://puu.sh/Da5kX.png
Edit mode does not help.

**Comment by Funwayguy** [comment]
What version of Minecraft and BQ are you using?

EDIT: The only way I can seem to recreate this is if the quest database was created in 3.5.296 or newer but loaded into a build older than that. This is because the new icon sizing can't be read by older versions.

**Comment by cyber01** [comment]
1.12.2
3.5.295

**Comment by Funwayguy** [comment]
Can you update it to 3.5.296 and try reloading the quests in that?

**Comment by cyber01** [comment]
i will try

**Comment by cyber01** [comment]
it didnt help :(

i`ll wait update of modpack
