### ISSUE TITLE
[1.7.10]crash on startup with RfExpansion

### ISSUE THREAD

**Issue by skull1** [Funwayguy/BetterQuesting#582]
forge: 10.13.4.1614
BetterQuesting: BetterQuesting-3.0.297
StandardExpansion: StandardExpansion-3.0.155
RfExpansion: RFExpansion-deobf-3.0.29
With betterquesting and StandardExpansions seems to work, but If i add the rf expansion jar it crash before load the game
crash report: https://pastebin.com/6HYMLQhV

btw ty for the 1.7.10 update

**Comment by Funwayguy** [comment]
That's the deobfuscated dev version of RF Expansion. It won't work in a normal instance. Please download the correct build and try again.

**Comment by skull1** [comment]
ops, mb, sry, 
by the way, i think the rf submission station has problems:
simple rf charge quest
- with detect button it steal some rf(8k rf for every click, a bit boring) from the cell in my inventory
- if i try with the station, it let me check the quest, then it locks but no charge happens,the internal rf storage of the station is at 0 even with power cable connected 
screens: http://puu.sh/DaqSC/2b3781e832.jpg  http://puu.sh/DaqUk/c8a8569eb8.png
i am missing something?
