### ISSUE TITLE
Taming tasks not successfully completing upon taming animal

### ISSUE THREAD

**Issue by katubug** [Funwayguy/BetterQuesting#586]
Hi! I'm a new user of your mod so it's very possible the issue here is on my end.

I'm using BetterQuesting-3.5.296 and StandardExpansion-3.4.154.

I'm creating a task to tame a cow. I have set the task as bq_standard:tame, and the target set as cow. I haven't edited anything else except for the rewards.

When I tame the cow, even if I click Detect/Submit, the quest does not complete, and it says I'm 0/1 on taming cows. It does this when I have editing mode on or off, when I'm in creative or survival.

The only thing that I can think of is that the random skins from Quark might be affecting this somehow? I'd really appreciate your advice. Thank you for the wonderful mod!

Here is a link to my entire modlist: http://bit.ly/ECModlist

**Comment by katubug** [comment]
Hmm. So I changed the trigger from taming a mob to achieving Best Friends Forever, and upon testing it, no dice. So I guess the issue is actually something in my modlist preventing animals from flagging as tamed. I'm going to guess that doesn't have anything to do with BQ, but I'll test without other mods, just to be sure.

Edit: If you want to close this for now, I'll post whatever I figure out.

**Comment by katubug** [comment]
Welp. It's happening even in pure vanilla with no forge. So either this is a bug in 1.12.2, or I've totally misunderstood how animal taming works. In any case, I'm sorry to bother you with this! Haha.

**Comment by Funwayguy** [comment]
Not sure what animal you're attempting to test this with but it appears to work just fine for me when taming a wolf. Have you ensured you're out of edit mode before testing?

![example](https://puu.sh/Ddrqs/11695e2afd.gif)

EDIT: Yes I realise the quest name is grammatically incorrect.

**Comment by katubug** [comment]
Ah! I'm sorry, I forgot to update with my findings. I was testing it with things like cows, pigs, sheep and chickens. As soon as I tested it on a llama, it fired off just fine. Worked with dogs and horses as well (I didn't test cats). So I'm guessing it's just that vanilla doesn't count the previous animals as being "tamed" when you feed them. My mistake. Thank you very much for your help!

**Comment by Funwayguy** [comment]
I think you may be confusing breeding and taming. Minecraft treats those seperately. I believe there's another advancement for that though.

**Comment by katubug** [comment]
Yes, I thought that when an animal had the hearts appear, that meant they were tamed. I've got my quests all fixed now. Thank you so much for your help. Also I didn't realize I could close this on my own, or I would have! Doing so now. Thanks again!
