### ISSUE TITLE
Enhancement: a quest task special interaction.

### ISSUE THREAD

**Issue by SirAron111** [Funwayguy/BetterQuesting#591]
Enhancement: a quest task special interaction.

For example I wanted to make a quest that was a bit like a ritual where I wanted d the player to place a specific item onto a pedestal and have him place certain items in chests around the pedestal.

But I couldn’t find a way to make the item interaction task work that way. First of all many modded blocks won’t get registered when I hit them with the item or when I click them with the item and it hops into the pedestals inventory for example.

Here is an example I wanted it to register that I clicked the item onto the altar basically but that didn’t work so I tried other means like hitting the altar with the item or the altars around it the only thing that did work was when I set the it so that the item I wanted to be originally on the pedestal hitting a piece of stone or the air and that worked. But hitting anything that isn’t a normal block didn’t work.  Is the only option I have to make a hopper under the altar and have it feed into a quest acceptor item? Here is apicture of how it should look the quest should complete the moment the player puts the item on the middle

![2019-04-13_15 41 38](https://user-images.githubusercontent.com/39855956/56083876-0448df00-5e2b-11e9-9410-c89d44bb93d0.png)

**Comment by Funwayguy** [comment]
This sounds like a job specifically for a purpose built task. Trying to rig a standard task to do something this complex isn't feasible.

**Comment by SirAron111** [comment]
I solved it in a crude way XD i made an ender crystal (entity in the middle instead of the pedestal) and people have to hit it with a special item to activate it (the stuff around it has to be collected in e previous quest and gets taken by the quest book) after that with a command line from a building mod I load the schematic of the ritual site with all things placed and the crystal appears. (Only that in your newest build the command quests are all broken so I can’t update)
