### ISSUE TITLE
/bq_admin default load causes "An unknown error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by katubug** [Funwayguy/BetterQuesting#593]
On my server, I'd like to use the latest version of all the quests, but /bq_admin default load doesn't seem to be working. None of the new quests are showing up, it just reset all the progressed quests to uncompleted. This is on version 3.5.296.

**Comment by Funwayguy** [comment]
Is there any additional error information in the server logs after the command was attempted?

**Comment by katubug** [comment]
Here's what the server log says when I try to execute the command: https://hastebin.com/ozomafiwok.sql

**Comment by Funwayguy** [comment]
Found it... actually a bug in the Standard Expansion, specifically taming tasks. I'll try and get a build out later today to fix that

**Comment by katubug** [comment]
Awesome, thank you for all your hard work!

**Comment by Funwayguy** [comment]
Build 3.4.158 of Standard Expansion is now up on Curse with a fix included for this. There's also build 3.5.299 of Better Questing available too.
