### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by ApolloMCC** [Funwayguy/BetterQuesting#595]
Hello! 
My server tps drops randomly and seems like it happens because of better questing mod. 
https://pasteboard.co/Ic6eyd0.png

Random question: where does bq store player's quests files

**Comment by Funwayguy** [comment]
Seems BQ isn't really responsible for this. Better Builder's Wands is firing a TON of inventory change calls when used. BQ is set to listen to changes and only update tasks in such cases, i.e. if you were to pick an item up or move something in your inventory. If a mod unnecessarily spams player inventories likes this then of course BQ is going to have a hard time trying to check every change.

EDIT: Player progress data is stored within `QuestProgress.json`

**Comment by ApolloMCC** [comment]
Thank you so much for your detailed response. Cheers
