### ISSUE TITLE
Quests are lagging

### ISSUE THREAD

**Issue by Shadeus84** [Funwayguy/BetterQuesting#596]
Hello! This may have been answered, but I can not find the answer for the life of me! So apologies in advanced if this has been answered. 

I'm playing Modern Skyblock 3 right now (I also had the same issue on StoneBlock) which uses your BQ Mod. Everytime I complete a quest, I have to back out of the quest and the click to back into it to actually claim the Loot Chest. Now that I think about it, it's only LootChests I have a problem with. If it's a regular reward, the claim button lights up normally. 

The button will also light up normally if there's multiple steps to complete. For example "Collect 9 cobble stone" then click the arrow to go to the second quest "make compressed cobble". When I complete those and click the arrow, the claim button will light up. 

Perhaps it's my PC, but I don't know.

**Comment by Funwayguy** [comment]
Do you know which version of BQ and Standard Expansion is installed?

**Comment by Shadeus84** [comment]
Standard Expansion: 3.4.151
Better Questing: 3.5.291

Also this: 
Better Questing Quest Book
3.1EXP_NET2-1.12 

Don't know if the latter helps. 
On Thursday, May 2, 2019 Funwayguy <reply@reply.github.com> wrote:

Do you know which version of BQ and Standard Expansion is installed?

**Comment by Funwayguy** [comment]
First, those are several versions out of date. Second, that's an experimental version of the Quest Book that shouldn't even be in a release pack (frankly it should be crashing becase the base mod doesn't support it)
