### ISSUE TITLE
Where do localization files go?

### ISSUE THREAD

**Issue by kylev** [Funwayguy/BetterQuesting#599]
What are the valid paths for me to place an `en_US.lang` file? I'd like to write my modpack in such a way that the quests can be translated, but the [brief localization wiki](https://github.com/Funwayguy/BetterQuesting/wiki/Localisation) page doesn't provide enough information to get me started.

I've converted my quest names to something like `foopack.tier0.name` and use that when editing the book, but the `en_US.lang` file that I've placed in a variety of folders never seems to get loaded. And the names in the quest line always appear as their bare translation keys rather than their translated strings.

I've placed my `en_US.lang` file in:
- config/betterquesting/resources
- config/betterquesting/resources/lang
- config/betterquesting/foopack/resources/lang

Is there something I'm missing? Could the wiki page be expanded to include a trivial working example?

**Comment by Funwayguy** [comment]
The wiki is over a year out of date but you almost got it. The file should be placed like so:

`config/betterquesting/resources/foopack/lang/en_US.lang`

You can think of anything placed after `config/betterquesting/resources` behaves the same way as the `assets` directory inside a resource pack. When I first wrote the wiki I figured once people knew how the resource directory behaved they could just use existing information on making resource packs or to make full use of it.
