### ISSUE TITLE
[1.10.2] Broke Inventory Crafting

### ISSUE THREAD

**Issue by teagan75** [Funwayguy/BetterQuesting#603]
I updated my pack to version 3.3.298 and when players tried to craft in their inventory grid, it wouldn’t allow it. It would allow placing items and show a completed product but wouldn’t let them take it.

**Comment by Funwayguy** [comment]
Are there any errors in the console log when this happens?

**Comment by teagan75** [comment]
I don't see any but this is my console log after trying to make a crafting table https://pastebin.com/tCsT5XQ8

**Comment by Funwayguy** [comment]
I still can't seem to recreate this in-dev and that log doesn't appear to have anything relevant to the reason as to why it wouldn't work. Tried both in single player and on server too. I wonder if it has something to with another mod interaction interfering with the detection.

**Comment by teagan75** [comment]
I am sure it is. Would have to go mod by mod at this point. It is a problem when I update your mod only. Crafting works with all the other mods hehe

**Comment by Funwayguy** [comment]
Well yes it would likely have something to do with the newer hooks that listen to inventory changes. If it's related to #605 then something was changed with the assumption that all inventory listeners are players.
