### ISSUE TITLE
[1.12.2] Cant choose between different Quests in editing mode.

### ISSUE THREAD

**Issue by Lylithrea** [Funwayguy/BetterQuesting#604]
So i installed a whole lot of mods, and also better questing mod. 
I wanted to create my whole own quest line for me and my friends to play on.

But when i got into creating quests, i looked up some videos on YouTube on how to do it and all. And then i saw that i couldn't choose between the different kind of quests. Neither themes and all. Whenever i create a quests with task and all it would say "betterquesting.placeholder". I have no clue on how to fix this. I've tried downloading the newest 1.12.2 version (beta (3.5.300)) but also the released version (3.5.299)

![60b5133478951a6dd156c38a6d2b4d8e](https://user-images.githubusercontent.com/51161758/58556401-4633b600-821c-11e9-95b0-9798b69f18e9.png)
![123c3a98c63a7a7cc61f4a7a3e8ef0a9](https://user-images.githubusercontent.com/51161758/58556402-4633b600-821c-11e9-95bb-12af5c779f63.png)
![02add063e22523d1f1ca6844057e97dd](https://user-images.githubusercontent.com/51161758/58556403-4633b600-821c-11e9-99e1-0ac717641f4c.png)

**Comment by Funwayguy** [comment]
You have the base mod but no expansions to make quests with. Standard Expansion includes all your basics that most packs are built on, RF Expansion has energy based task types, NPC Integration can hook into Custom NPCs, and may be some additional 3rd party add ons for more content.

**Comment by Lylithrea** [comment]
Thanks, im stupid :)
