### ISSUE TITLE
special quests for bees

### ISSUE THREAD

**Issue by TheNimbleNinja** [Funwayguy/BetterQuesting#607]
i am wanting to makea  breeding quest line for bees. would it be possible to make a special quest function that looks for the species of a bee and nothing else?

**Comment by Funwayguy** [comment]
Like setting up a partial NBT match in an item retrieval quest? Already possible.

**Comment by TheNimbleNinja** [comment]
how would i do this i dont know how to do that?

**Comment by alterdim** [comment]
You might want to take a look at what nbt tags are in minecraft, it's not that complicated.

**Comment by Funwayguy** [comment]
This is a bit of an old issue now so I'll be closing this but for future reference you may be interested in this:
https://www.curseforge.com/minecraft/mc-mods/bq-forestry
