### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by FoGzone** [Funwayguy/BetterQuesting#611]
[crash-2019-06-19_17.40.25-server.txt](https://github.com/Funwayguy/BetterQuesting/files/3306848/crash-2019-06-19_17.40.25-server.txt)

I've updated my FTB Continuum server with the latest Better Questing by replacing the BetterQuesting jar file in the mods folder because of the submission station bug.
As soon as I want to start my server, it crashes.
My client is working normally after the update.

**Comment by Funwayguy** [comment]
By latest you mean 16 versions out of date...

Current release version is 3.5.299. Crash report says you're running 2.5.283. In fact this exact crash was fixed the day after 283 came out.
