### ISSUE TITLE
[Suggestion] Merge base mod with Standard Expansion

### ISSUE THREAD

**Issue by Monniasza** [Funwayguy/BetterQuesting#613]
Standard Expansion is required for BQ to function properly, so they might become one self-contained questing mod.

**Comment by Funwayguy** [comment]
BQ and all its editors does actually work just fine without SE. You could build an entire non-standard set of task types and use that instead if you wanted to.

SE also serves as an example for expansion devs on how they too can add aditional content to the mod. Merging them would make it extremely difficult to see which code is for what module.

I would also like to keep the base mod as a clean slate and not load it up with junk that may not be used in every case.
