### ISSUE TITLE
Username quest transfer

### ISSUE THREAD

**Issue by HungieSpoon** [Funwayguy/BetterQuesting#614]
Hi. So I have a save file that my friend gave to me, and the modpack he was playing had BQ. I would like to transfer his quest progress to my username. I also changed the player.dat file to my username to preserve his items

**Comment by Funwayguy** [comment]
Better Questing operates off of UUIDs and it's usually not that straight forward to transfer ownership of progression in some automatic fashion.

If you have your friends UUID and your own UUID, you can find and open the `QuestProgress.json` file in the world save directory and do a Find & Replace using notepad and that should work.

(also sorry for the late reply. Had a lot going on over the last two months)
