### ISSUE TITLE
New world but use previous quest data

### ISSUE THREAD

**Issue by MavDarkness** [Funwayguy/BetterQuesting#615]
Im a server admin and was curious if its possible to start a new world but transfer all the quests from the old world to the new one? id like to retain all information from better questing. so im assuming that i would just have to transfer the betterquesting folders from config and world and then the player data to the new world?

**Comment by Funwayguy** [comment]
Yes. It is as simple as moving the `.json` files over. Nothing quest related is stored in the player `dat` files.
