### ISSUE TITLE
Simultaneous Cooldowns going Negative

### ISSUE THREAD

**Issue by jelaw21** [Funwayguy/BetterQuesting#619]
My cooldowns worked, until I ran a default load. Then any current cooldown timers, all went negative.

**Comment by jelaw21** [comment]
Nope it wasn't default load. If you have multiple quests on cooldowns, they won't reset until they are ALL off of cooldowns.  I had 4 quests going negative and one positive. When the positive one hit zero, ALL of the quest reset to completed.

**Comment by Funwayguy** [comment]
Could be dimension time differences. There's a known display bug there that occurs when you're in a non-overworld dimension. I plan to change how that math works in later builds to fix that.

**Comment by jelaw21** [comment]
I'm in the overworld.  If it was a display bug, wouldn't it still say completed/unclaimed but the time would just be negative?  Mine show completed/claimed until the positive one reset.

**Comment by Funwayguy** [comment]
Then the only other thing I could think of would be edit mode. Resets are disabled while that's on.

**Comment by jelaw21** [comment]
Not in Edit mode, but I am in Creative.

**Comment by jelaw21** [comment]
I got two quests on cooldown now, one at 10 min and 1 at 11 min. I'll let
you know the results.

**Comment by jelaw21** [comment]
![image](https://user-images.githubusercontent.com/21100827/60931886-63cb5500-a289-11e9-9830-8a7e58b6107c.png)
![image](https://user-images.githubusercontent.com/21100827/60931923-8e1d1280-a289-11e9-8f28-05ff4f74ba56.png)
![image](https://user-images.githubusercontent.com/21100827/60931911-82c9e700-a289-11e9-8b2f-699d0ca5dabb.png)

So the top two were the 10 and 11 min quests, both now showing negative cause I still had a 30min cooldown going.  You can see that they are still showing as completed/claimed.

**Comment by jelaw21** [comment]
![image](https://user-images.githubusercontent.com/21100827/60932970-64b2b580-a28e-11e9-9e47-383fc0f8ff49.png)
This one shows the treant quest completed, and the other now completed to. At the same time.

**Comment by dierke9** [comment]
I can second this, cooldowns going negative have never been in edit world in this world (i am always in edit mode in a seperate test world tho)
Almost allways in the overworld, yet if i remember correctly i have claimed the rewards with the claim all button don't know if that makes anything different

**Comment by Funwayguy** [comment]
Oh... OHHHH. I think I figured it out. I did a dumb and sorted the scheduled resets backwards by mistake. That's why it seemingly 'works' all at once when the last reset passes 0s.

Unfortunately due to WIP code I can't put out a fix for 1.12.2 just yet. Will be included with the network change beta builds when those are ready.

**Comment by jelaw21** [comment]
That's great news!!!  Awesome!
Might I add a suggestion?  Any way to get the cooldowns timers to tick only
when the player is online?  Its fine for single player, but for
multiplayer, since the server runs all the time, a player just logs off at
night and in the morning all cooldowns have reset.

**Comment by Funwayguy** [comment]
On the surface that may seem easy but it wouldn't scale well with several hundred players all needing timers for each repeatable quest.

BQ doesn't actually even 'tick' those. It's just a timestamp of when the quest was last completed with some math to figure out how long till it reaches the reset duration.

It may seem overkill, but BQ needs to account for hundreds of players running thousands of quests on a server with hundreds of other mods.

**Comment by jelaw21** [comment]
Was the last update supposed to fix this, or am I still waiting for another BETA build update?

**Comment by Funwayguy** [comment]
I did fix the sort order in the beta I just sent out. Did it still happen?

**Comment by jelaw21** [comment]
Testing now, will let you know the results.

**Comment by jelaw21** [comment]
Ah, works now. Thanks.

**Comment by dierke9** [comment]
Yesterday all the negative cooldowns fixed itself, not sure if this was bc another cooldown was finished or not. They all had different cooldown times even in negative but all got off cooldown at the same time. I did not update anything of mods

**Comment by Funwayguy** [comment]
dierke9, becuase of the broken sort order it does appear to 'fix' irself when the last timer passes 0s but in reality it'll still break the next time you have several in waiting again.

**Comment by Funwayguy** [comment]
Going to close this as it has been fixed in beta
