### ISSUE TITLE
Reward.command problem with sponge (ICommandSender need to be implemented)

### ISSUE THREAD

**Issue by emil18250** [Funwayguy/BetterQuesting#62]
Hi , i have some problem with the mod in spongeforge , when we press claim for an command reward it make the players kick with fatal error terminated connexion error .
I ask in the sponge forum and they say to contact mod author , (i don't know how to post in requests sry ^^" , don't really know how to use github proprely)

I don't know if need log but i post it , maybe will need ^^ : 
https://www.mediafire.com/?cziytab7584bmmy
Thanks.

**Comment by Funwayguy** [comment]
Going to close this thread as I don't intend to do support for Sponge. It has a habit of breaking things that work just fine in Forge alone
