### ISSUE TITLE
Quest icons should be saved as namespaced strings

### ISSUE THREAD

**Issue by endumiuz** [Funwayguy/BetterQuesting#620]
Minecraft: 1.7.10
Forge: 1614
Better Questing: 3.0.303

Icons are saved like this:
```json
"icon:10": {
  "id:2": 4178,
  "Count:3": 1,
  "Damage:2": 8500,
  "OreDict:8": ""
},
```

They should be saved like this:
```json
"icon:10": {
  "id:8": "gregtech:gt.meta.rockGt",
  "Count:3": 1,
  "Damage:2": 8500,
  "OreDict:8": ""
},
```

**Comment by Funwayguy** [comment]
Saw this before and kept wondering why this was happening. Think it finally clicked in my head though. Old serialization still used numbers despite IDs being supported elsewhere.

This is gonna be annoying to fix

**Comment by Funwayguy** [comment]
Closing this as it was fixed in build 304
