### ISSUE TITLE
Need help finding solution to Minecraft crash

### ISSUE THREAD

**Issue by Solarixx** [Funwayguy/BetterQuesting#622]
"The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen"

Crash report below:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/14/19 10:15 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_147044_g(InventoryEffectRenderer.java:72)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:42)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_147044_g(InventoryEffectRenderer.java:72)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:42)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (240, 127). Absolute: (960, 508)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,30,0), Chunk: (at 0,1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 20886384 game time, 21012539 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityPainting['Painting'/107713, l='MpServer', x=187.06, y=58.50, z=-291.50], EntityPainting['Painting'/107712, l='MpServer', x=190.50, y=59.50, z=-292.94], EntityPainting['Painting'/107715, l='MpServer', x=191.00, y=67.50, z=-288.06], EntityChicken['Chicken'/107714, l='MpServer', x=186.41, y=74.00, z=-294.28], EntityChicken['Chicken'/107717, l='MpServer', x=186.41, y=33.00, z=-309.41], EntityPainting['Painting'/107716, l='MpServer', x=189.00, y=67.00, z=-288.06], FancyEntityItem['item.item.InfiTool.Broadsword'/107719, l='MpServer', x=178.09, y=83.13, z=-310.00], EntityChicken['Chicken'/107718, l='MpServer', x=191.44, y=33.00, z=-308.44], EntityPainting['Painting'/107721, l='MpServer', x=189.00, y=36.00, z=-285.94], FancyEntityItem['item.item.InfiTool.Shovel'/107720, l='MpServer', x=176.81, y=83.13, z=-310.16], EntityChicken['Chicken'/107724, l='MpServer', x=186.32, y=33.00, z=-295.67], EntityClientPlayerMP['Solarixxx'/107698, l='MpServer', x=170.56, y=81.62, z=-299.64], EntityPainting['Painting'/107708, l='MpServer', x=190.00, y=44.00, z=-292.94], EntityPainting['Painting'/107710, l='MpServer', x=189.00, y=59.00, z=-292.94], EntityPainting['Painting'/107711, l='MpServer', x=190.50, y=58.50, z=-292.94], EntityPainting['Painting'/107712, l='MpServer', x=190.50, y=59.50, z=-292.94], EntityPainting['Painting'/107713, l='MpServer', x=187.06, y=58.50, z=-291.50], EntityPainting['Painting'/107715, l='MpServer', x=191.00, y=67.50, z=-288.06], EntityPainting['Painting'/107716, l='MpServer', x=189.00, y=67.00, z=-288.06], EntityPainting['Painting'/107721, l='MpServer', x=189.00, y=36.00, z=-285.94], EntityChicken['Chicken'/107701, l='MpServer', x=160.53, y=33.00, z=-307.34], MoCEntitySnake['Snake'/107700, l='MpServer', x=162.78, y=33.00, z=-303.91], EntityItem['item.item.ItemManaBean'/107703, l='MpServer', x=169.09, y=80.13, z=-299.72], EntityItem['item.item.grapeItem'/107702, l='MpServer', x=170.31, y=79.13, z=-300.31], FancyEntityItem['item.item.InfiTool'/107705, l='MpServer', x=175.69, y=30.94, z=-305.13], FancyEntityItem['item.item.InfiTool.Shovel'/107704, l='MpServer', x=175.69, y=30.84, z=-305.13], EntityChicken['Chicken'/107707, l='MpServer', x=166.44, y=33.00, z=-301.59], FancyEntityItem['item.item.InfiTool'/107706, l='MpServer', x=175.69, y=31.35, z=-305.13], EntityChicken['Chicken'/107709, l='MpServer', x=179.56, y=33.00, z=-305.47], EntityPainting['Painting'/107708, l='MpServer', x=190.00, y=44.00, z=-292.94], EntityPainting['Painting'/107711, l='MpServer', x=190.50, y=58.50, z=-292.94], EntityPainting['Painting'/107710, l='MpServer', x=189.00, y=59.00, z=-292.94]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 296109112 bytes (282 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 38
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D6 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	movillages{1.4.2} [Mo' Villages] ([1.7.10]MoVillages-1.4.2.jar) 
	UCHIJA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1462-universal.jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.1} [CoFH Core] (CoFHCore-[1.7.10]3.1.1-324.jar) 
	UCHIJA	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
	UCHIJA	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
	UCHIJA	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
	UCHIJA	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
	UCHIJA	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCHIJA	CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7-1.7.10.jar) 
	UCHIJA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.1.1.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10k.jar) 
	UCHIJA	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (Pam's WeeeFlowers 1.7.2b.zip) 
	UCHIJA	ProjectE{1.7.10-PE1.9.3} [ProjectE] (ProjectE-1.7.10-PE1.9.3h.jar) 
	UCHIJA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.24' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.1-324
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Katebrigas Vanilla Resource Pack (1).zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Funwayguy** [comment]
1) This crashlog has nothing to do with BetterQuesting and should not be reported here
2) You have OptiFine installed. Rendering based crashes should be expected. It even tells you:
`Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine`
3) Even if I wanted to debug this, there is little to no information in this log for me to even start looking
