### ISSUE TITLE
There is no clear fucking tutorial on how to change the default image in the quest book

### ISSUE THREAD

**Issue by jennymcdermott** [Funwayguy/BetterQuesting#624]
All I can find is "This is such a great mod!" and changing themes yet I want to change the default fucking image in the god damn book!! There is only one tutorial on it (In English about this topic) and it isn't even on your wiki or F.A.Q, it's from some guy who can't even do a good job at explaining the topic clearly. Please, put SOMETHING on this topic because it frustrates me to no fucking end and every time I fucking try to do it, it comes up as a missing texture and not the god damn image.

**Comment by Funwayguy** [comment]
How about you go cooldown and come back when you're willing to behave reasonably.
