### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by JustGamma** [Funwayguy/BetterQuesting#626]
Hello, when im using BetterQuesting w/ StandardExpansion i get this error whenever a player tries to use their inventory crafting grid. The player just gets kicked with internal server error message or they crash.

The server is running on Thermos 1.7.10

[07:46:27 WARN]: Failed to handle packet for /*
java.lang.ClassCastException: bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:105) ~[aap.class:?]
        at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:153) ~[aae.class:?]
        at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
        at net.minecraft.inventory.Container.func_75144_a(Container.java:418) ~[zs.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[07:46:27 INFO]: ItzzGamma lost connection: Internal server error
[07:46:27 INFO]: [DiscordSRV] Player ItzzGamma quit with silent quitting permission, not sending a quit message
[07:46:27 INFO]: ItzzGamma left the game.

Im using version 3.0.297 BetterQuesting (and yes i have tried downgrading/upgrading) and StandardExpansion(3.0.155)

Mods:

[B#407]  	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
[B#407]  	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
[B#407]  	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
[B#407]  	UCHIJA	appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
[B#407]  	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
[B#407]  	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
[B#407]  	UCHIJA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
[B#407]  	UCHIJA	OpenComputers|Core{1.7.4.1265} [OpenComputers (Core)] (minecraft.jar) 
[B#407]  	UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
[B#407]  	UCHIJA	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
[B#407]  	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
[B#407]  	UCHIJA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
[B#407]  	UCHIJA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
[B#407]  	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
[B#407]  	UCHIJA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
[B#407]  	UCHIJA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
[B#407]  	UCHIJA	ItemBlacklist{1.2.0.8} [ItemBlacklist] (ItemBlacklist-1.7.10-1.2.0.8.jar) 
[B#407]  	UCHIJA	feudalrox_whetstone{v1.0.0} [The Whetstone Mod] ([1.7.10] The Whetstone Mod-v1.0.1.jar) 
[B#407]  	UCHIJA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
[B#407]  	UCHIJA	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22-core.jar) 
[B#407]  	UCHIJA	BuildCraft|Silicon{7.1.22} [BC Silicon] (buildcraft-7.1.22-silicon.jar) 
[B#407]  	UCHIJA	BuildCraft|Transport{7.1.22} [BC Transport] (buildcraft-7.1.22-transport.jar) 
[B#407]  	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
[B#407]  	UCHIJA	WailaAddonBC{1.0.5.1} [WailaAddonBC] ([1.7.10]WailaAddonBC-1.0.5.1.jar) 
[B#407]  	UCHIJA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
[B#407]  	UCHIJA	appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
[B#407]  	UCHIJA	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
[B#407]  	UCHIJA	betterquesting{3.0.297} [Better Questing] (BetterQuesting-3.0.297.jar) 
[B#407]  	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
[B#407]  	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
[B#407]  	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
[B#407]  	UCHIJA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
[B#407]  	UCHIJA	BuildCraft|Factory{7.1.21} [BC Factory] (buildcraft-7.1.21-factory.jar) 
[B#407]  	UCHIJA	BuildCraft|Builders{7.1.22} [BC Builders] (buildcraft-7.1.22-builders.jar) 
[B#407]  	UCHIJA	BuildCraft|Energy{7.1.22} [BC Energy] (buildcraft-7.1.22-energy.jar) 
[B#407]  	UCHIJA	BuildCraft|Robotics{7.1.22} [BC Robotics] (buildcraft-7.1.22-robotics.jar) 
[B#407]  	UCHIJA	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
[B#407]  	UCHIJA	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
[B#407]  	UCHIJA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
[B#407]  	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
[B#407]  	UCHIJA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
[B#407]  	UCHIJA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
[B#407]  	UCHIJA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
[B#407]  	UCHIJA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
[B#407]  	UCHIJA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
[B#407]  	UCHIJA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
[B#407]  	UCHIJA	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
[B#407]  	UCHIJA	endercore{1.7.10-0.2.0.35_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.35_beta.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
[B#407]  	UCHIJA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
[B#407]  	UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
[B#407]  	UCHIJA	FlatBedrockx{1.0.2} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.0.2.jar) 
[B#407]  	UCHIJA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
[B#407]  	UCHIJA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
[B#407]  	UCHIJA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden+Magic-1.7.10-0.575.jar) 
[B#407]  	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
[B#407]  	UCHIJA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
[B#407]  	UCHIJA	thermaltinkering{1.0} [Thermal Tinkering] (ThermalTinkering-1.7.10-1.2.1.jar) 
[B#407]  	UCHIJA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
[B#407]  	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
[B#407]  	UCHIJA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
[B#407]  	UCHIJA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
[B#407]  	UCHIJA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
[B#407]  	UCHIJA	GalaxySpace{1.2.12} [GalaxySpace] (GalaxySpace-1.7.10-1.2.12.jar) 
[B#407]  	UCHIJA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
[B#407]  	UCHIJA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
[B#407]  	UCHIJA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
[B#407]  	UCHIJA	OpenComputers{1.7.4.1265} [OpenComputers] (OpenComputers-MC1.7.10-1.7.4.1265-universal.jar) 
[B#407]  	UCHIJA	voltzengine{1.11.0.452} [Voltz Engine] (Voltz-Engine-1.7.10.jar) 
[B#407]  	UCHIJA	icbm{2.15.4.497} [ICBM] (ICBM-1.7.10-2.15.4b497.jar) 
[B#407]  	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
[B#407]  	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
[B#407]  	UCHIJA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
[B#407]  	UCHIJA	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
[B#407]  	UCHIJA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.1.1031.jar) 
[B#407]  	UCHIJA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.7.10-9.1.1.1031.jar) 
[B#407]  	UCHIJA	mffs{0.50} [Modular Forcefield System] (Mffs-1.7.10-0.1.0b147.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UCHIJA	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker.jar) 
[B#407]  	UCHIJA	numina{1.7.10} [Numina] (Numina-0.4.1.106.jar) 
[B#407]  	UCHIJA	powersuits{1.7.10-0.11.1.117} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.7.10-0.11.1.117.jar) 
[B#407]  	UCHIJA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
[B#407]  	UCHIJA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
[B#407]  	UCHIJA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
[B#407]  	UCHIJA	openmodularturrets{2.2.11-243} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.11-243.jar) 
[B#407]  	UCHIJA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.7.10Lb.jar) 
[B#407]  	UCHIJA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
[B#407]  	UCHIJA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
[B#407]  	UCHIJA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
[B#407]  	UCHIJA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
[B#407]  	UCHIJA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
[B#407]  	UCHIJA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
[B#407]  	UCHIJA	ResourceLoader{1.0} [Resource Loader] (ResourceLoader-1.0.jar) 
[B#407]  	UCHIJA	bq_standard{3.0.155} [Standard Expansion] (StandardExpansion-3.0.155.jar) 
[B#407]  	UCHIJA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
[B#407]  	UCHIJA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
[B#407]  	UCHIJA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
[B#407]  	UCHIJA	thaumicenergistics{1.1.3.0} [Thaumic Energistics] (thaumicenergistics-1.1.3.0.jar) 
[B#407]  	UCHIJA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
[B#407]  	UCHIJA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
[B#407]  	UCHIJA	voltzenginemodcompat{1.11.0.452} [Voltz Engine Mod Compatibility Loader] (Voltz-Engine-1.7.10.jar) 
[B#407]  	UCHIJA	voltzenginemodflag{1.11.0.452} [VoltzEngine mod protection, flag, and region system] (Voltz-Engine-1.7.10.jar) 
[B#407]  	UCHIJA	weather2{v2.3.19} [Localized Weather & Storms] (weather2-1.7.10-2.3.20.jar) 
[B#407]  	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
[B#407]  	UCHIJA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
[B#407]  	UCHIJA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
[B#407]  	UCHIJA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
[B#407]  	UCHIJA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
[B#407]  	UCHIJA	UniDict{1.7.10-2.9.2} [UniDict] (UniDict-1.7.10-2.9.2.jar) 
[B#407]  	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
[B#407]  	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)

**Comment by Funwayguy** [comment]
This is a known bug in Thermos due to it making an unsafe unchecked cast in their patch code:
https://github.com/Funwayguy/BetterQuesting/issues/605#issuecomment-497985636
