### ISSUE TITLE
Repeatable Quests with multiple choice break questing.

### ISSUE THREAD

**Issue by CaiganMythFang** [Funwayguy/BetterQuesting#63]
**Current Quest Database** : https://drive.google.com/open?id=0B7jvvxp1wXVVUEI5NTNiZUdkcTQ
**Download for the entire modpack (currently in a Beta phase)** :  https://forum.feed-the-beast.com/threads/1-7-10-the-ferret-business-wip-hqm-350-quests-v-0-1-4.64930/page-222#post-1714281
**Minecraft Version** : 1.7.10
**Forge Version** : 1614
**Better Questing version** : 1.0.141
**Other BQ Extensions** : Questbook, Standard, RF

When I complete the Bones of Dragons quest in the Special Research quest page, it seems to break questing completely. UI Scrolling breaks outside of the Edit windows, I cannot select from multiple choice rewards, and many other UI issues.

As well, when I complete the quest, this happens : http://i.imgur.com/m2UTzFI.png

The lines flash on and off constantly. They don't connect to any valid quests, and looking through the JSON I cannot find any quests that connect to those Quest ID's. (the lines are probably a visual bug from the UI breaking)

The issue is not with just that quest, but others in that questline : 
Bones of the Dragon
Tools of the Wyvern
Simple Draconic Devices
A Powerful Charge
Somewhat Dislocated
Helpful Devices
Awakened Tools
Awakened Armor
Awakened Weapons

All these quests have a Choose reward as well as are repeatable(cooldown amount doesn't matter).  I have tested this with  a new quest, unconnected to anything, and the issue is reproducible. 

Resetting that quest's completion status fixes questing.

Tested with version 1.0.137 of Better Questing as well, with the same result.

**Comment by teagan75** [comment]
I am having the same issue as above with a repeatable quest and choice award. I have tested this on the newest version of the mod.
Other BQ Extensions : Questbook, Standard, NPC integration
The quest completion notification flashes constantly on screen until i reset the quest
Edit: after resetting quest progression it is still flashing on screen that the quest is complete. It just repeats itself over and over.

**Comment by Funwayguy** [comment]
It may be the progress associated with the task isn't being cleared properly resulting in a refresh loop (which with a reset delay of 0 makes for a very fast refresh). Having UIs constantly refresh does tend to cause rendering issues outside of my control such as the lines between quest icons acting up.

I will look into the cause of the bug and see what I can do. In the mean time you can disable the refreshing by setting the task's repeat time to -1.

**Comment by teagan75** [comment]
The refresh timer for my quest was set to 1200 (20mins) but once the tasks complete it immediately goes into that loop that locks out the whole quest book at that point. No more quests can be completed until the progress for the repeat is reset. This only happens when there is a refresh timer AND multiple choice rewards. I have tested a refresh quest with set rewards and it doesn't happen. I also tested a one time complete quest with multiple choice rewards and it doesn't happen. This bug is very specific.

**Comment by Funwayguy** [comment]
Thanks for the info. Managed to recreate it in my development environment. Currently in the process of debugging the cause. Will let you know if I find anything.

EDIT: Found it but fixing it without breaking reward claims is going to be somewhat interesting.

**Comment by Funwayguy** [comment]
Managed to fix it. Preparing to push update out shortly.
