### ISSUE TITLE
Unable to invite others to quest party

### ISSUE THREAD

**Issue by NielsPilgaard** [Funwayguy/BetterQuesting#630]
Hi again!

Some of my users are reporting an inability to invite others to their questing party.
Original issue: https://github.com/NillerMedDild/Enigmatica2/issues/522

### Versions
- BetterQuesting-3.5.305
- StandardExpansion-3.4.161

**Comment by Funwayguy** [comment]
Fixed in BQ build 3.5.307

**Comment by credomane** [comment]
This seems to still be an issue in Enigmatica 2 with BQ 3.5.308. Invites just don't appear on the receiving side.
