### ISSUE TITLE
Crash single game

### ISSUE THREAD

**Issue by SeagalKru** [Funwayguy/BetterQuesting#631]
Hello!
After installing your mod, my game began to crash. Removing your mod from the assembly did not remove the problem: there was a reference to your mod in the log file.
Any mod can still require the presence of your mod?
[crash-2019-07-21_23.35.03-client.txt](https://github.com/Funwayguy/BetterQuesting/files/3415024/crash-2019-07-21_23.35.03-client.txt)
[latest.log](https://github.com/Funwayguy/BetterQuesting/files/3415025/latest.log)
Thank!

**Comment by Funwayguy** [comment]
Known issue that was fixed in SE 161. Alternatively just install JEI for the time being.

**Comment by SeagalKru** [comment]
Please forgive me: explain what is "SE 161"? Is it a mod? ;)

**Comment by Funwayguy** [comment]
Standard Expansion 3.4.161 (last number is the build number)
