### ISSUE TITLE
[1.7.10-GTNH] Crafting Quest won't complete

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#635]
Crafting Quests not complete if you craft it in a Vanilla Crafting Table or in Hand.
Not working in the full GTNH 2.0.7.5 pack or only only with Better Questin 3.0.304 ,Standart Expansion 3.0.160 and Nei.

I tried with vanilla stuff like gravel to flint or gt tool crafting.

https://cdn.discordapp.com/attachments/570900229503844383/602941728718323712/unknown.png
https://cdn.discordapp.com/attachments/570900229503844383/602941794526822441/unknown.png
https://cdn.discordapp.com/attachments/570900229503844383/602941867511775232/unknown.png
https://cdn.discordapp.com/attachments/570900229503844383/602597788047638565/unknown.png
https://cdn.discordapp.com/attachments/570900229503844383/602597839599828993/unknown.png

**Comment by bartimaeusnek** [comment]
Can confirm this issue for 1.7.10, crafting tasks not working with a minimal installation. If you need help/want a PR, it would be great to get the location of the code that is responsible for checking the Crafting Tasks.

**Comment by Funwayguy** [comment]
Forgot 1.7.10 had to event buses and the crafting events were on the old one. Sorta fixed it in dev now but now I have to dig up the old hack that I made to fix Forge's inability to report shift click crafting properly.

**Comment by Dream-Master** [comment]
Works thanks. Not tested shift click
