### ISSUE TITLE
IMPORTANT: Reordering Chapters Clears All Quest

### ISSUE THREAD

**Issue by jelaw21** [Funwayguy/BetterQuesting#637]
I noticed after update StandardExpansion-3.4.161.jar, that the order of my chapters were all messed up. So I tried, in edit mode, to change the order, and it deleted the entire book. I waited til the next release and tried again. Same effect. 

Here is a gif showing the problem: 

![questbook bug](https://user-images.githubusercontent.com/21100827/62171468-ff863900-b2fc-11e9-9cff-aaca387eb569.gif)

Technical Details: 
BetterQuesting-3.5.307.jar
StandardExpansion-3.4.163.jar
Minecraft Version: 1.12.2 (modded) forge-14.23.5.2838

**Comment by Funwayguy** [comment]
Oh.... oh no.

I'll try and get a hotfix put this afternoon as soon as I get back to my desk.

**Comment by jelaw21** [comment]
That's cool. Also, care if I make a Wiki on the Github?

**Comment by Funwayguy** [comment]
Well there is a wiki already, I just haven't updated it since BQ1

**Comment by jelaw21** [comment]
I'd love to update it and kinda explain a bit on what all the options do
and things. I'm getting quite good at using it.

**Comment by Funwayguy** [comment]
Currently I just use my Discord for assisting and explaining how things work as I develop new features. Feel free to join and I can go over the wiki contents some time.

https://discordapp.com/invite/AevsYGa
