### ISSUE TITLE
[Suggestion] 1.14.4 version?

### ISSUE THREAD

**Issue by Wissi** [Funwayguy/BetterQuesting#648]
Great Work, we love your mod.

We use it in all our modpacks. Will you be porting over to 1.14.4 soon?
We'd love to start testing it as we are now moving to port our mod and modpacks to 1.14.4 as well.

Thanks.

**Comment by Funwayguy** [comment]
Sorry but that is still a very long way away. There's still plenty of work left to do on the 1.12.2 version and even if I had a 1.14 version, it wouldn't be cross compatible thanks to the huge internal changes. I haven't even familiarised myself with the new rewritten Forge system yet

**Comment by Wissi** [comment]
Yeah, well not cross compatible for sure. 
We're having to do major re-writes to our mod as well.
Hope to see your work soon in 1.14 it's extremely useful and great to have.

Thanks.
