### ISSUE TITLE
Game stoppes working during the launch and close

### ISSUE THREAD

**Issue by Kaio-Cesar** [Funwayguy/BetterQuesting#650]
I'm tryed to play a modpack named Gregblock, but, the modpack stoppes working during the game load, serching for the cause, i'm found that better questing is the cause, i'm launch only the better questing, and the same thing occurs.
The console log: https://paste.ee/p/XH8Gp (i'm alredy tried BQ .300)

**Comment by Funwayguy** [comment]
I think that's the wrong log.

If I had to guess based on the version numbers, you're mixing the beta version of the base mod with incompatible versions of the expansion.

**Comment by Kaio-Cesar** [comment]
On an clean launch with a new profile and relese versions
its don't generete crash log
console log: https://paste.ee/p/Gbo1M
![9](https://user-images.githubusercontent.com/43482905/64496423-38f68080-d27b-11e9-86f6-1fdb7b9562f0.PNG)

**Comment by AsrielOver** [comment]
The same thing happens to me, do you have any solution to this problem?

**Comment by Kaio-Cesar** [comment]
Problem solved!
It's because of old hardware,
like, I'm used an Intel Core duo
