### ISSUE TITLE
Having a problems with cooldown timer

### ISSUE THREAD

**Issue by Wiral2** [Funwayguy/BetterQuesting#652]
Version : 1.12.2
Mod Version : BetterQuesting-3.5.300
Forge: 14.23.5.2837

Cooldowns for quests go into negative whenever theres another quest thats in a longer cooldown. For example, quest 1 has a 2 hour cooldown and quest 2 has 5 seconds cooldown. After 5 seconds, quest 2 cooldown timer goes into negative and stay negative until quest 1's cooldown timer is finished. Also was not in edit mode.

**Comment by Funwayguy** [comment]
This was already fixed in the beta builds. The scheduler sort order was backwards.

**Comment by Wiral2** [comment]
Any idea when it'll be released for 1.12.2?
