### ISSUE TITLE
LAN Party issues

### ISSUE THREAD

**Issue by NielsPilgaard** [Funwayguy/BetterQuesting#657]
Hey, I have yet another LAN issue for you. The description is from original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1375

- BetterQuesting-3.5.311
- StandardExpansion-3.4.167

```
**Modpack version**
1.69

**Can the issue be reproduced?**
unknown

**Issue**
basically i cannot complete any quest whether i complete them or if my party member completes them, the quest book glitches between them being completed and being uncompleted but when i make a quest item it allows my party member to get the reward.. i tried manually completing the quest in edit mode which did not work either, resetting the quest book. and leaving the current party and resetting then.

i do want to try and keep my party part member quest if there is any methods of solving this issue.
```

**Comment by YakoSWG** [comment]
Bump

**Comment by Funwayguy** [comment]
Can this be narrowed down to a specific quest type. The conditions are way too vague to even begin debugging this.

**Comment by YakoSWG** [comment]
I've only had it occur with retrieval type quests.

To reproduce:
1. Join a LAN world (bug does not occur for host)
2. Create a party
3. Complete a retrieval task
3.5. The task might not complete for "Player 2"
5. After completing the task (manually or via sharing) it will cause an infinite loop of completing then uncompleting the task. The loop can be stopped by using /bq_user refresh causing it to be permanently uncompleted. By leaving the party the task can be completed normally

**Comment by Funwayguy** [comment]
I'll check this tomorrow. In the mean time it would likely be a good idea to get that base version updated to 3.5.312 as there's a bug in 3.5.311 that reads some large item stacks as air.

**Comment by YakoSWG** [comment]
I already updated hoping this issue was fixed already unfortunately it still persists.

**Comment by Funwayguy** [comment]
Managed to recreate it although its consistency is very strange. Seems to bar access to reward claims in the process too. Besides running into some other issues with party management related to issue #658 this is one of the more stranger bugs I've seen in a while.

**Comment by YakoSWG** [comment]
Found something that also might be related to this (also on LAN). If I join my friend on local LAN then complete a retrieval type quest (no party or sharing) claim the reward and then give him the item to complete it as well I can complete the quest again and claim the reward. (It was pretty inconsistent though)

**Comment by Funwayguy** [comment]
I think I've fixed it. Try build 3.5.313 and let me know how that goes.

**Comment by NielsPilgaard** [comment]
@YakosWG Would you mind testing it? I don't have a setup for replicating the bug.

**Comment by YakoSWG** [comment]
Seems to work just fine. I'll create a new issue report should I find anything else. Thank you for your time and being so nice.
