### ISSUE TITLE
Cannot send/receive quest invites.

### ISSUE THREAD

**Issue by rollerce** [Funwayguy/BetterQuesting#658]
Playing Seablock: Rustic Waters. When I send an invite to my BF, he doesn't receive it/cannot see it, and the same happens in reverse. The modpack is running BetterQuesting-3.5.312, questbook-3.1.1-1.12, and StandardExpansion-3.4.167 as far as the BQ mods go.

Any thoughts on how I can fix it? I dug around in the configs and couldn't find any settings that might be preventing the invites from going through or being seen.

**Comment by Funwayguy** [comment]
I fixed up some things in build 3.5.313 related to party invites and tested it works in LAN but I'm not certain if it fixes your particular case. Can you give the new build a try and see if how it goes?
