### ISSUE TITLE
Object Submission Station still crashes the game in 2019

### ISSUE THREAD

**Issue by WarpZone32** [Funwayguy/BetterQuesting#659]
Seems like Funwayguy closed the previous thread about this issue without claiming it was fixed or explaining why people were mistaken about it being broken.

**To reproduce:**
- Download MultiMC
- Create a fresh Minecraft 1.12.2 modpack instance using MultiMC
- Launch the instance once to generate files and folders.
- Using MultiMC, install whatever version of Forge it puts a star next to by default.  (looks like in my case, this was 14.23.5.2768)
- Download BetterQuesting-3.5.314.jar , StandardExpansion-3.4.169.jar , and questbook-3.1.1-1.12.jar from Curse and drop into the new mod's .minecraft/mods/ folder.
- Relaunch the modpack and Create a New World with Allow Cheats: On
- Type the command "/bq_admin edit" without the quotes into chat
- Press ` key (AKA the ~ key)
- Create a new Quest Line, Quest, and Retrieval Task (1 block of dirt.)
- Type /gamemode 1
- put down a new Object Submission Station and attach a Hopper to it.
- Type /gamemode 0
- Break a dirt block
- Right-click the Hopper
- Place dirt block into Hopper.
**Game crashes on next block tick.**

**Comment by Funwayguy** [comment]
Closing this due to duplicate #660

**Comment by WarpZone32** [comment]
I remember editing this twice.  Not sure how both of them got uploaded though.  Weird.
