### ISSUE TITLE
Better Questing Edit Mode Glitch

### ISSUE THREAD

**Issue by teagan75** [Funwayguy/BetterQuesting#66]
When in edit mode only, if I get out of the GUI and hit any key, it reopens the book again as well as executing the action the key represents. So if i hit W I keep running forward until I exit the book again. Small minor annoyance.

**Comment by Funwayguy** [comment]
Is this specifically with the book expansion?

**Comment by teagan75** [comment]
No it happens when I enter the gui via the tilda/grave key. It only started happening after updating better questing.

**Comment by Funwayguy** [comment]
Closing...
Reason: Pre-rewrite (2.x.x) issue(s)

You can pester me on Discord if this still happens :P
