### ISSUE TITLE
Object Submission Station still crashes  (1.12.2 single-player)  (Includes steps to reproduce)

### ISSUE THREAD

**Issue by WarpZone32** [Funwayguy/BetterQuesting#660]
Seems like Funwayguy closed the previous thread about this issue (https://github.com/Funwayguy/BetterQuesting/issues/408) without claiming it was fixed or explaining why people were mistaken about it being broken.  It's still broken in 2019, even though Better Quests isn't abandoned.  (It's still being updated literally to this day!  Or at least yesterday.)

**To reproduce:**
- Download MultiMC
- Create a fresh Minecraft 1.12.2 modpack instance using MultiMC
- Launch the instance once to generate files and folders.
- Using MultiMC, install whatever version of Forge it puts a star next to by default.  (looks like in my case, this was 14.23.5.2768)
- Download BetterQuesting-3.5.314.jar , StandardExpansion-3.4.169.jar , and questbook-3.1.1-1.12.jar from Curse and drop into the new mod's .minecraft/mods/ folder.
- Relaunch the modpack and Create a New World with Allow Cheats: On
- Type the command "/bq_admin edit" without the quotes into chat
- Press ` key (AKA the ~ key)
- Create a new Quest Line, Quest, and Retrieval Task (1 block of dirt.)
- Type /gamemode 1
- put down a new Object Submission Station and attach a Hopper to it.
- Type /gamemode 0
- Break a dirt block
- Right-click the Hopper
- Place dirt block into Hopper.
**Game crashes on next block tick.**

I really hope this gets fixed, because it really would be the best way to do quests involving mass-production.

**Comment by Funwayguy** [comment]
Considering there was no crash report included in the original issue report and that I wasn't able to recreate it till now (not entirely sure how I missed it every time), I closed it assuming that it was fixed during one of my mass rewrites over the last year.

Now that I _have_ recreated it I can start debugging why it's doing this and how to fix it. I'm aiming to have this fixed in 3.5.316

**Comment by Funwayguy** [comment]
Got this fixed in dev ready for next release whenever that might be.

**Comment by WarpZone32** [comment]
Sweet! :smiley:  I'll alert the developers of GregTech.  This has been a long time coming!

**Comment by GregoriusT** [comment]
Uhh someone with the name shdthdshsfhs notified me on IRC about an Issue being fixed that I do not know about in the first place? Pretty sure this might be a confusion between one of the many Ports of GregTech 5 and the official GregTech 6 for MC 1.7.10?

I looked at the linked Issue, MC 1.12? Isn't that the responsibility of GregTech "Community" Edition? You should notify Archengius about this and not me.

**Comment by Funwayguy** [comment]
Uh... I have no idea how this relates to greg tech but yes this is a fix for 1.12.2 not 1.7.10.

**Comment by WarpZone32** [comment]
Oh...

Nevermind. XD

I knew that GregTech had that problem (I think I saw a youtube video recently where somebody complained about having to mass-click the items into their questbook) but I didn't realize GregTech was 1.7.10.

Please disregard, maintainers of GregTech.

**Comment by Funwayguy** [comment]
The clicking is a separate issue entirely and is part of the ongoing redesign process.

As for this fix, I'll back port it with the rest of the network and party changes once I'm satisfied it's stable enough in 1.12.2

**Comment by WarpZone32** [comment]
:+1:

**Comment by Funwayguy** [comment]
Build 3.5.316 is now up on Curse Forge for 1.12.2 and includes a fix for this
