### ISSUE TITLE
Server Side Only Crash

### ISSUE THREAD

**Issue by ElvenChaos** [Funwayguy/BetterQuesting#661]
When loading on a server setup, this crashes the server. Works fine loading on client-side.

[Crash log](https://pastebin.com/LN2d49kb)
The following might be the root of the issue from the log:
`Caused by: java.lang.RuntimeException: Attempted to load class betterquesting/api2/client/gui/events/CommonPanelEvents for invalid side SERVER`

Forge: 2847
BetterQuesting-3.5.314
StandardExpansion-3.4.169

EDIT: If it helps, the issue was not present in BQ 313.

**Comment by Funwayguy** [comment]
Was fixed in 315
