### ISSUE TITLE
Minecraft crashed whilst rendering screen

### ISSUE THREAD

**Issue by muriloonunes** [Funwayguy/BetterQuesting#665]
[crash-2019-11-16_10.11.29-client.txt](https://github.com/Funwayguy/BetterQuesting/files/3854204/crash-2019-11-16_10.11.29-client.txt)
Here is the crash report. Can someone help me? 

****MOD LIST:**
Better survival
Bookshelf
Classic Combat
Craftable Horse Armor 
Creeper Confeti
Custom Mob Spawner
Doggy Talents
Mo' Creatures
Dynamic Surroundings
Dynamic Trees
Enchanting Plus
Ender Core
Ender IO
Ender Zoo
Extra Utilities 2
Genetics Reborn
Ice and Fire
Inventory Tweaks
It's raining food
JEI
Levels+
LevelUp!
LLibrary
MCLib
Metamorph
OpenBlocks
Open Blocks Lib
Optifine
Pam's Simple Recipes
Potion Core
Primitive Mobs
Quality Tools
Scaling Health
Silent Lib
So Many Enchantments
Waila
Want To Be a Superhero
Wearable Backpacks
Xaeros Minimap**

**Comment by Funwayguy** [comment]
Incorrectly setup advancement. Nothing to do with BQ
