### ISSUE TITLE
I need an NBT editor.

### ISSUE THREAD

**Issue by GoblinCwl** [Funwayguy/BetterQuesting#669]
It's very tedious to modify NBT in the client, or can I overload the data file?
Thanks!

**Comment by GoblinCwl** [comment]
sorry

I just found out that I can take items directly from my inventory

my bad!

**Comment by Funwayguy** [comment]
Besides picking items out of your own inventory, there is an NBT editor. Click the `...` button next to the item in the list and you should be able to edit whatever tags you need to (or add new ones)
