### ISSUE TITLE
How can I make the modified JSON file take effect in the game immediately?

### ISSUE THREAD

**Issue by GoblinCwl** [Funwayguy/BetterQuesting#671]
I like this mod, I am applying it to the server, but it is very troublesome to edit NBT data in the game, so

How can I make the modified JSON file take effect in the game immediately?
 Is there any instruction or method similar to overload

I use machine translation English, maybe there is a problem with language expression, sorry!

**Comment by Funwayguy** [comment]
BQ only loads from file when loading the world the first time however you can change it live by instead editing `config/betterquesting/DefaultQuests.json` and then running `/bq_admin default load`.

Be warned that if you have made a mistake in the formatting you will likely lose all if your progression data even if you restore the previous quests. Backup your questing files in the world directory before attempting this.
