### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by Tyrius1** [Funwayguy/BetterQuesting#675]
1. additional book mark tabs
2. ability to name the bookmarks with the name showing up on mouse when hovered over the           bookmark
3. what if when you opened quests it was also a pop out like the bookmarks are?

**Comment by Funwayguy** [comment]
1) I'd need to make a new system to handle those and I'm trying to avoid adding anything new right now. Also I'd personally rather call it "pinned" quests.
2) See 1
3) I thought about doing this but it starts making the UI code far more complicated and harder to maintain. Plus the theming system would have a hard time implementing cohesive overrides for such complex UIs.
