### ISSUE TITLE
Party Invites aren't received/sent

### ISSUE THREAD

**Issue by NielsPilgaard** [Funwayguy/BetterQuesting#679]
Reported by a player:
> When I invite one of my friends in my quest book they won't see my invitation. So they can't accept it.

The friend cannot send invites either.

It is on a dedicated server.

### Versions
- Enigmatica 2: Expert 1.74
- BetterQuesting-3.5.319
- StandardExpansion-3.4.171

Original issue: https://github.com/NillerMedDild/Enigmatica2/issues/596

**Comment by NielsPilgaard** [comment]
The issue behind this is PC clocks out of sync, Funwayguy has implemented a fix for it.
The issue where the server clock and multiple player clocks are out of sync also affects shared party progression - If clocks are out of sync, players can be unable to complete quests the other person is completing, eventhough they're online at the same time.

**Comment by Funwayguy** [comment]
It affects party progression too now?

**Comment by NielsPilgaard** [comment]
I guess so :/ syncing clocks fixes it.

**Comment by Funwayguy** [comment]
Huh... very strange. I don't use the client side system time for anything besides invites but that was fixed. I also just located a desync bug unrelated to time. Might have to dig a bit deeper elsewhere if this is the case

**Comment by Funwayguy** [comment]
Fixed as of 3.5.320

**Comment by NielsPilgaard** [comment]
Thank you very much. I have updated all the Enigmaticas to this version.
