### ISSUE TITLE
loot chest

### ISSUE THREAD

**Issue by Pligzy88** [Funwayguy/BetterQuesting#681]
i am playing the Engineer's life pack and i got a loot chest and when opened it just said NULL    this is what i got   https://paste.dimdev.org/ofuqajuyen.mccrash

**Comment by JFMillerUSA** [comment]
Same here

**Comment by Funwayguy** [comment]
Crash has already been fixed in a Standard Expansion update.
NULL is intended when no loot groups have been setup (name will be changed next update to be more clear).

NOTE: It used to default to dungeon loot in previous versions but that has since been removed as it caused a few issues with unintended rewards.

**Comment by Pligzy88** [comment]
I mean you can keep saying it's been fixed all you want that doesn't help us because in the pack we play it hasn't been fixed....I don't care what needs to be done to fix the pack.....It should be done...It's not His fault that a mod messed up in his pack

**Comment by Funwayguy** [comment]
1. The change to the dungeon loot fall back items was stated in Standard Expansion change log 3.4.168 and it is up to the pack developer read and adjust their quests as necessary if they choose to update.
2. At any point in time the _pack developer_ was and still is free to contact me on how to adapt to this change but as of this comment they have not as far as I'm aware.
3. It is not my job to fix issues related to pack developers who blindly update mods without reading change logs and what it means for their packs. I will not be an excuse for laziness.
4. You not caring and demanding things to be fixed is not how issue reports are handled here. If you continue behave like this with complete disregard for the information that is being presented, you will not be permitted to participate in further discussions.

The pack developer can contact me if they want info on how to update their quests accordingly and _properly_ but until then, this thread is locked.
