### ISSUE TITLE
Mod crashes at PreInitialization (1.12.2)

### ISSUE THREAD

**Issue by TakenNameh** [Funwayguy/BetterQuesting#684]
I have a pretty old PC so these kinds of problems are expected, but I haven't found similar problem to this one in other mods expect the mods like OpenBlocks, Immersive Engineering, and Buildcraft. Most other mods work fine except these 4, I am not a developer so I don't know what all of these mods have in common. so I wanted to give it a shot anyway hoping that there is a fix for this problem or a temporary solution. Here's the multimc crash log :
https://paste.ee/p/LUk0a
Thanks for reading this!

**Comment by Funwayguy** [comment]
Unfortunately that isn't a crash log and doesn't tell me anything abour what went wrong. Once you have the proper logs we can work from there.

**Comment by TakenNameh** [comment]
I apologize for that, I tried this with a normal launcher and here's the crash log
https://paste.ee/p/IRmvs
I hope this is the crash log you are looking for! If it's not can you please tell me where its stored? I'm not very knowledge able about this.

**Comment by Funwayguy** [comment]
That one is also a FML debug log unrelated to the crash. Try looking in a folder labelled `crash-reports` and you should find a bunch of `.txt` files in there with timestamps of when the crash occurred. You can open up the file in notepad and check that it has `---- Minecraft Crash Report ----` written at the top to be sure.

**Comment by TakenNameh** [comment]
I did some research and I found out that it didn't actually generate a crash log, that's why I couldn't find it, somehow the game crashes without generating a crash report. I guess there is nothing to do now huh, well I'm getting a new PC soon anyway, Thanks.

**Comment by TakenNameh** [comment]
There isn't some kind of a software I can use to force the game to generate a crash report, is there?

**Comment by Funwayguy** [comment]
I could possibly use the general Minecraft log which is usually called `latest.log` in the `logs` folder. That might have some information we could use

**Comment by TakenNameh** [comment]
https://paste.ee/p/QyA6Z
I highly doubt that there is any info in this file.

**Comment by Funwayguy** [comment]
There actually was enough information to figure out why it won't start. Unfortunately yes it does have to do with the age of your computer. Minecraft only had 800MB of RAM allocated to it (usually you want about 4-6GB for modded 1.12.2) however because your computer is still running a 32bit operating system this could only ever support a max of 4GB even if you installed more. To make matters worse, the graphics is being run off the CPU which would not bode well for your playable frame rate even if it did launch.

Sorry I can't do more for you.

**Comment by TakenNameh** [comment]
Ah, it's alright! Thanks for taking the time to answer me, I just wanted to make sure that the problem is from the hardware, not the software.
