### ISSUE TITLE
When I use 1.7.10 newest version mod on curseforge, the user will quit the server whenever they use 2x2 craftingtable, err

### ISSUE THREAD

**Issue by yuesha-yc** [Funwayguy/BetterQuesting#685]
When I installed 1.7.10 newest version mod of BQ and standard expansion on curseforge on my server, the user will quit the server whenever they use 2x2 craftingtable, saying "Internal Server Error". Is it a bug? 
![Screen Shot 2020-01-23 at 12 49 37](https://user-images.githubusercontent.com/52098789/72957516-d8598180-3dde-11ea-8bea-9273d027e101.png)
This is the mod list that I use. 
Server is Thermos, 1.7.10. 
3.0.304 Better Questing
3.0.162 Standard Expansion

**Comment by Dream-Master** [comment]
it's a Thermos bug. I link later the file you need @yuesha-yc 
Hope that is ok @funwayguy

**Comment by Funwayguy** [comment]
That's fine. Wondering if it needs to be put up on Curse Forge as a patch mod

**Comment by Dream-Master** [comment]
https://github.com/juanmuscaria/Gambiarra-BetterQuesting

**Comment by Dream-Master** [comment]
@Funwayguy @yuesha-yc

**Comment by yuesha-yc** [comment]
> https://github.com/juanmuscaria/Gambiarra-BetterQuesting

Thank you. However, when I tried to launch the game with this mod, I got this crash-report.

[crash-2020-02-05_10.45.09-client.txt](https://github.com/Funwayguy/BetterQuesting/files/4157184/crash-2020-02-05_10.45.09-client.txt)
