### ISSUE TITLE
Questlines Overwritten

### ISSUE THREAD

**Issue by MaelstromPhx** [Funwayguy/BetterQuesting#7]
I have a friend who wrote up some quests on their client and then sent me the quest database file so that I could take a look at them. Whenever I start or exit a SP game, it overwrites the questline quests to nothing. I can still see them in the database however.

**Comment by Funwayguy** [comment]
Can you post the database file in question? Also, where are you placing the file?

**Comment by MaelstromPhx** [comment]
Heres the file. It's a son but labeled txt so I can upload it here since GitHub doesn't support .json
[QuestDatabase.txt](https://github.com/Funwayguy/BetterQuesting/files/76254/QuestDatabase.txt)

The file is going in the world save for my SP world.

**Comment by Funwayguy** [comment]
@MaelstromPhx Seems to load relatively fine for me so far:
http://puu.sh/mkb4V/48f844b59b.png

**Comment by Slind14** [comment]
I believe he means that they are being corrupted once he closes the game. So he can see them just fine, but once the client is restarted it doesn't load them anymore.

**Comment by Funwayguy** [comment]
@Slind14 Nope, they save/load just fine even after a full client restart.

@MaelstromPhx Are you sure you're using the latest version of Better Questing? There a was a slight quest line format change in a recent build. If your friend wrote the quest lines in a newer version, then they will not be able to be loaded with a version prior to 1.0.4

**Comment by MaelstromPhx** [comment]
Updating fixed the issue. I was using the updated dev version last time on accident and it kept crashing so I was still on 1.0.3. Updating to 1.0.4 non-dev fixed the issue :3

Sorry about that :stuck_out_tongue:
