### ISSUE TITLE
Picture in the Description

### ISSUE THREAD

**Issue by DoktorAerzt** [Funwayguy/BetterQuesting#70]
Hello Funwayguy,

can you maybe add a function to set a picture in the description? 
I have looked in your code but GUI isn´t a part of coding i can do.

Maybe you can show me the code were you exactly draw the string on the screen. 

I hope you unterstand what i mean.

Have a nice day
DoktorAerzt

**Comment by Funwayguy** [comment]
The description box is specifically a scrolling text list. You'd need to program your own scrolling list that supports multiple GUI elements. I'm also in the planning on completely rewriting how those lists work from the ground up but the new method should support what you're looking for. The current piece of code used to draw text lists is here:
https://github.com/Funwayguy/BetterQuesting/blob/1.9/src/main/java/betterquesting/client/gui/misc/GuiScrollingText.java

**Note:** This is a modified version of the scrolling lists used in Forge's mod list screen so you can find the original version there. This is also one of the more complicated pieces of rendering code within BetterQuesting so I recommend you know your way around OpenGL calls before attempting this sort of thing.
