### ISSUE TITLE
Saving Quests

### ISSUE THREAD

**Issue by deni500** [Funwayguy/BetterQuesting#71]
Hi, can somebody help me ? I have 7 quests lines and I dont know how can I import them into all world ... When you create world you dont have quests .. so who creating new world he must import quests ?

**Comment by Funwayguy** [comment]
To set the current questline as the default for new worlds use the command "/bq_admin default save"

**Comment by deni500** [comment]
Ok, thank you .. and how I can set more lives ? I want have more than 10 lifes ??

**Comment by deni500** [comment]
And I found something in 1.10.2 when I create Retrieval Task with Consume:no and I take the item wood and when I click on detect/submit nothing happend :(

**Comment by Funwayguy** [comment]
Closing...
Reason: Pre-rewrite (2.x.x) issue(s)
