### ISSUE TITLE
Copy Quest Progress Between Server Online/Offline

### ISSUE THREAD

**Issue by MrDrStevenson** [Funwayguy/BetterQuesting#715]
I recently switched my server to online mode so that my friends and I from college can play together long-distance.  We had an issue where our inventories were lost, but we resolved this by copying playerdata .dat files.  Is there a similar way I would be able to change these over?

Background: Offline and Online UUID's for players are different, so the online server sees my account as a new person.  My old questing data still exists, but updating QuestingProgress.json with the new UUID in world/betterquesting didn't sync it with my "new" character.

**Comment by Funwayguy** [comment]
If you're on a recent build, a UUID swap in `QuestProgress.json` using find-and-replace should have been enough but needs be done while the server is off. `NameCache.json` may also pose some issues but usually that updates itself (you can just delete it to be sure). I'm starting to wondering if the `.dat` file you copied contains a conflicting UUID cache.

I don't really know many other things to try besides manually completing what you had with commands. Switching servers between offline and online is generally not recommended for these reasons.

**Comment by MrDrStevenson** [comment]
Yeah, I figured that one out the hard way.

Turns out the UUID switch did work, some other settings were just being squirrely, thank you for the help though!
