### ISSUE TITLE
All Quests Showing Complete

### ISSUE THREAD

**Issue by jelaw21** [Funwayguy/BetterQuesting#72]
When a new player enters my server, it shows all the quests as complete. Also, if I am in edit mode, I can go in and see all the quests and non-completed, then when I switch edit mode off, all the quests show as completed again.

*EDIT:  It also does this on single player mode. Am I doing something wrong here?  I go into bq_admin edit on   reset all quests to not completed,  do bq_admin edit off and they all complete again.

**Comment by Funwayguy** [comment]
Would you happen to be in offline mode? That currently has some issues at the moment.

**Comment by jelaw21** [comment]
Nope. Its online. I have players joining the server.

**Comment by jelaw21** [comment]
I should mention its the 1.9.4 version.

**Comment by jelaw21** [comment]
Figured it out!  /bq_admin reset all  deletes all the tasks from the progress JSON.

**Comment by jelaw21** [comment]
And then something happens when the server refreshes and all the tasks are eliminated.  But this happens regardless of /bq_admin reset all. 

File before server: 
[QuestProgress.txt](https://github.com/Funwayguy/BetterQuesting/files/486930/QuestProgress.txt)

File after server:
[QuestProgressAfter.txt](https://github.com/Funwayguy/BetterQuesting/files/486932/QuestProgressAfter.txt)

**Comment by jelaw21** [comment]
Interesting.....
Now I'm getting this:  and the only thing I've done is upload a fresh QuestProgress from a working save in SPM. Using the same File before server from above....

[malformed_QuestProgress.json0.txt](https://github.com/Funwayguy/BetterQuesting/files/486971/malformed_QuestProgress.json0.txt)

**Comment by Funwayguy** [comment]
Very strange malformed file there.

**Comment by jelaw21** [comment]
Yep. Anyway you can walk me through the steps to set- up a server using
better questing? I notice you can make a default file? Do I place that in
the config for the server and allow it to generate its own questing files?
Or do I copy the questing files from my single player mode into the world
folder on the server?

**Comment by jelaw21** [comment]
OMG, delete this thread, burn it, take those ashes, drown them, dry them
out and burn them again. I never want to be reminded of this again.   I
forgot to add StandardExpansion pack to my server.  Works great now, great
mod by the way. You need some help with the Wiki?

**Comment by Funwayguy** [comment]
(sets fire to thread as requested)
