### ISSUE TITLE
The Task and other stuff isn't appearing

### ISSUE THREAD

**Issue by Honeysucklegames** [Funwayguy/BetterQuesting#723]
I've tried all I can but I can't get the Task,rewards,and themes to appear.
i have the base mod- Basic questing and the Standard Expansion both on and still nothing! help me!
![2020-07-22_17 24 43](https://user-images.githubusercontent.com/68655475/88235617-dc0c7a80-cc40-11ea-805a-0a2cc4daa67b.png)
![2020-07-22_17 28 12](https://user-images.githubusercontent.com/68655475/88235619-dca51100-cc40-11ea-9086-2e39f6f36a83.png)
![2020-07-22_17 28 25](https://user-images.githubusercontent.com/68655475/88235621-dca51100-cc40-11ea-9217-e100b3db1666.png)

**Comment by Funwayguy** [comment]
Are you sure the expansion is loaded correctly? Check your in game mod list to see if it is there and you have downloaded the right  version

**Comment by Honeysucklegames** [comment]
I have the better questing-3.5.329 and standardExpansion-3.0.181 the two newest versions of the mod I could find

**Comment by Funwayguy** [comment]
Did you happen to check that the 3.0.xxx versions of Standard Expansion are meant for 1.7.10?
Curse is lazy and just lists what is 'newer' but that may not be for the version of Minecraft you are using.

The version of Standard Expansion you need is 3.4.173.
Check your versions before downloading in future
