### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by 3iivil** [Funwayguy/BetterQuesting#726]
.

**Comment by Funwayguy** [comment]
You're missing the Standard Expansion add on. BQ by itself doesn't add the task add reward types, it only serves as the base menus and tools.

**Comment by 3iivil** [comment]
> You're missing the Standard Expansion add on. BQ by itself doesn't add the task add reward types, it only serves as the base menus and tools.

Ok thank you ❤️

**Comment by BraveCaperCat** [comment]
Rename to:
missing expansion
