### ISSUE TITLE
Suggestion: Allow players to skip landing page

### ISSUE THREAD

**Issue by thebrianlenz** [Funwayguy/BetterQuesting#73]
I'm happy that when you click on the "Quests" button, you can get taken to your most recent quest, but why bother with that first page every time the book is accessed?

It would be pretty handy if the book remembered exactly where we were when the book was last opened, instead of having to navigate the initial landing page. This is pretty amplified when using BetterQuesting in a single-player setting. I'll never need to press the Party button, and the theme button will only be used once usually throughout the entire playthrough (setting it to the theme you like the first time and you'll leave it there for the rest of the time you're playing).

An easy answer is adding a config option. I saw there is one for going straight to the last quest, so that might be a bit redundant. Perhaps having an option within the questbook itself would be possible, as that would allow players who realize they do or don't want that feature to enable or disable at their whim (probably the most valuable on servers when players join or leave other parties or something along those lines).

Additionally, if you've just finished a quest, the book forgets which chapter you were in. Again, super minor, just a small QoL change that would be a very big positive.

**Comment by RedSnt** [comment]
I can't tell what version I used that allowed me to click an item in the book which took it to the NEI recipe of said item - but by doing so the book would always open on the same page that I left it. Only "hacky" way I could made the book go to the current task I was on.  
I agree that it is annoying that you have to go through the trivial steps to find your current task again. It would be nice if there was some workaround at least, maybe a way to jot down the tasks on a clipboard item you could hold ingame? That's what I'd be content with anyway.

**Comment by Funwayguy** [comment]
I'll be moving the bookmarking to the first page for the next release. I've been talking to some other people about it and they feel pretty much the same about it.
