### ISSUE TITLE
GUI Scroll List Overflow

### ISSUE THREAD

**Issue by Enginecrafter77** [Funwayguy/BetterQuesting#738]
So, basically the issue is that whenever an element is supposed to be wrapped inside a scrollbar, it's contents overflow the screen instead of being hidden (the expected behavior).

![[ScreenShot](https://imgur.com/a/6FkSeAq)](https://i.imgur.com/jOVOTo4.png)

In the screenshot the list overflows downwards, but it also overflows upwards.

I have narrowed the issue down, and it turns out to be an issue with Optifine. I know Optifine is closed source which makes it extremely hard to pinpoint these issues, but I guess it must be somehow tampering with the way you render GUIs.

So feel free to mark this as a low priority issue, since the obvious workaround is simply to get rid of optifine.

**Comment by Elibikerdude** [comment]
I seem to have this problem as well, I also discovered that this could be caused by OpenGL not being able to load the stencil buffers.

**Comment by Funwayguy** [comment]
That is correct. Something broke the OpenGL stencil buffers and BQ is no longer capable of cropping it's UIs. I cannot fix this from my side.
