### ISSUE TITLE
Can't finish quests with "Break Block Task"

### ISSUE THREAD

**Issue by pfmd86** [Funwayguy/BetterQuesting#74]
Hi,
I have found an error or I'm using it the wrong way. Let me discribe:

I added a new quest with one single task. The task ist "Break Block Task" 1 minecraft_stone.
When I break a block and submit it in the task, the task get status "complete" but the quest will be uncompleted.
What am I doing wrong?

I have version Vetter Questing 1.3.161 with Standard Expansion 1.3.92

![screen001](https://cloud.githubusercontent.com/assets/8144485/19021550/bdc61324-88c4-11e6-9488-687b0fc2df51.png)
![screen002](https://cloud.githubusercontent.com/assets/8144485/19021551/bde386c0-88c4-11e6-98c3-a51b69db0b69.png)

**Comment by Biochao** [comment]
I am also having this issue. 
Better Questing version 1.3.161 with Standard Expansion 1.3.92 and RF Expansion 1.3.19.
![2016-10-04_12 54 20](https://cloud.githubusercontent.com/assets/6515654/19083864/0588f21c-8a32-11e6-8478-940b972ecaa9.png)

**Comment by TheOnlyRupert** [comment]
Same problem here.

**Comment by Funwayguy** [comment]
A legacy fix has been sent out for this. Sorry for the long wait.
