### ISSUE TITLE
[1.7.10] BetterQuesting has problem with Authme plugin

### ISSUE THREAD

**Issue by Dragsio** [Funwayguy/BetterQuesting#740]
I have a BetterQuesting mod and an AuthMe plugin on my server. When I type the **/bq_admin edit** command, the edit button doesn't appear in the GUI. When I temporarily removed AuthMe, it worked. But I need AuthMe on the server.
Please help me!

I have:
* server Thermos 1.7.10-1614.57
* BetterQuesting 3.0.328
* AuthMe plugin 5.2-legacy with MySQL connection

**Comment by Funwayguy** [comment]
Thermos or any other Bukkit derivative is not, and never will be supported
