### ISSUE TITLE
Screen Black Out

### ISSUE THREAD

**Issue by teagan75** [Funwayguy/BetterQuesting#75]
Using the current versions of Better Questing, Standard Expansion, and Questbook found on curse. Sometimes the screen blacks out when auto completing a quest. I have to shut down minecraft and restart for it to stop.

**Comment by teagan75** [comment]
Tested without the questbook addon and the screen still blacks out when the "Skyrim-like" quest completion words are suppose to come on screen. Sorry that is the best I can describe. 

Edit: Just started a fresh run through with my quests. I noticed the black screen started after Thaumcraft did a warp consequence, i.e. "Strange whispers reveal secrets to you..." Do you think something is conflicting with Thaumcraft 4?

**Comment by Kataiser9** [comment]
I have also noticed this recently. I can confirm that the black screen can happen even before you get any warp, so I doubt it's related to Thaumcraft specifically.

**Comment by Funwayguy** [comment]
Fixed this a while ago in BQ2 releases. Closing issue...
