### ISSUE TITLE
[Suggestion] Disable Crafting Recipe Until Quest Completion

### ISSUE THREAD

**Issue by MokahTGS** [Funwayguy/BetterQuesting#76]
I'm not sure if this is possible, but I'd love a way to disable a crafting recipe of a specific item until after a quest is complete.  For example, you can't craft a wooden axe until after you hand in the Collect a Log quest.

Is there any way to do this currently or could this be added?

**Comment by teagan75** [comment]
the progression mod does this already

**Comment by Funwayguy** [comment]
Closing this thread. This would require a custom expansion that I don't have time or motivation to create any time soon. If you can find a developer willing to try then by all means go ahead but that developer isn't me
