### ISSUE TITLE
Quests randomly showing up as complete - then becoming uninteractable.

### ISSUE THREAD

**Issue by cpeake9** [Funwayguy/BetterQuesting#77]
Looked around and didn't see it. Odd issue where sometimes upon loading into the game a random quest will pop up as complete. Going to the quest will show it colored as if it had been completed but the reward was unclaimed. However the reward cannot be claimed and the quest can no longer be completed as normal basically causing it to lock up.
![654faacb9eca4b53b807f3befed949f9](https://cloud.githubusercontent.com/assets/9260773/19212891/4c027e00-8d22-11e6-9a07-22fb4e6ead50.png)
![d0b702f3993040cb84fc216a9a4d6ba7](https://cloud.githubusercontent.com/assets/9260773/19212892/4c059194-8d22-11e6-9374-b94211ec8c5f.png)

**Comment by Funwayguy** [comment]
Closing issue...
Reason: Pre-rewrite (2.x.x) issue
