### ISSUE TITLE
BQ + Smooth Font: Texts exceed quest & item tooltip boxes within the questbook (from GTNH)

### ISSUE THREAD

**Issue by haobawobufu** [Funwayguy/BetterQuesting#786]
Your Pack Version
2.7.0-beta4

Your Server
SP

Type of Server
Single Player

Your Expectation
I would like to suggest implementing a new setting option, similar to 'textWidthCorrection', that allows users to adjust the length of tooltips. 

The Reality
Texts exceed quest & item tooltip boxes when using Smooth Font mod
<img width="1799" alt="1" src="https://github.com/user-attachments/assets/40339895-0371-4e4b-976e-823192f87eb0">
<img width="1801" alt="2" src="https://github.com/user-attachments/assets/332f87e1-a68f-4db2-adb7-526960d7c1b6">

**Comment by Funwayguy** [comment]
This looks to be a modified version of BQ3. I'm assuming it's the GTNH version. You'll have to report it to their github repo and developers.

PS: I am currently working on BQ4 for 1.20+ and haven't touched BQ3 in years.
