### ISSUE TITLE
Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [Funwayguy/BetterQuesting#787]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if Better Questing mod was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks. It would be nice if such a cool mod could be downloaded from the second most popular Minecraft modding site.

**Comment by Funwayguy** [comment]
Nope, and this is not the first time Modrinth has been advertised to me with such wording.

![image](https://github.com/user-attachments/assets/fca2658a-3c9a-4680-adcd-77dab18fa6dd)

**Comment by Alter73** [comment]
I don't know, I'm not on your Discord and I've never written to you yet. It's just that apparently I'm not the only one who likes Modrinth. I don't really understand why you don't like it. I don't see any difficulty in releasing a mod on both CurseForge and Modrinth, as many others do. You would just help people who only use Modrinth for whatever reason. Of course, Modrinth is not so popular, since it appeared quite recently and did not gain that base, but for me personally it remains many times more convenient to use, especially its launcher. If it's just because of monetization, then that explains a lot. Anyway, thanks for the reply!

**Comment by Funwayguy** [comment]
Modrinth may be convenient for _pack_ devs but that's where it ends. Compensation for _mod_ developers has been absolutely abysmal. Not every developer can work for pennies or for 'exposure' and to imply as much only serves to devalue their work. Not seeing the difficulty behind the scenes or the circumstances of the real people behind mods is also not a valid excuse.

Nobody is entitled to having access to CurseForge mods on Modrinth. If you pick one over the other, you accept the consequences of that choice and the choices that platform has made towards its contributors.

As stated in my previous message, I intend to revisit Modrinth after BQ4 development reaches full release to see if platform conditions have improved. Until then there will be no parallel BQ releases on Modrinth.
