### ISSUE TITLE
[1.3.161] Crash to desktop when moving quest

### ISSUE THREAD

**Issue by SPMoo66** [Funwayguy/BetterQuesting#79]
Was moving quests around for a bit in the designer when the game crashed

http://pastebin.com/6apm2KFr

Edit: Just had a second crash doing the same thing, but a different crashlog this time

http://pastebin.com/xq6hH8Sm

**Comment by Funwayguy** [comment]
Closing...
Reason: Pre-rewrite (2.x.x) issue(s)
