### ISSUE TITLE
 Crash with new Quick tools (Auto)

### ISSUE THREAD

**Issue by GenDeathrow** [Funwayguy/BetterQuesting#8]
Got a crash when I clicked auto sort on quest page, I didn't have any quest made so.. must of gotten a null error.. 

version: BetterQuesting-1.0.8

http://pastebin.com/SjLMB7KB

Wasn't sure if you had already caught this or not

**Comment by Funwayguy** [comment]
@GenDeathrow You be breaking my shiny new mods now? :P

No I didn't pick up on this bug yet but I'll get it fixed today. Thanks for the report

**Comment by GenDeathrow** [comment]
I hate null errors... they are so easy to forget or overlook
