### ISSUE TITLE
not detecting shapering kits from tinkers construct (1.10.2)

### ISSUE THREAD

**Issue by SDUBZ** [Funwayguy/BetterQuesting#80]
i made a quest for people to craft 63 of each kit  and it couldnt detect the crafting ,so i switched to retrieval and still no luck also i went to ignore nbt and it just completes the quest even tho only 2 types were i my inventory

replay asap

**Comment by Funwayguy** [comment]
Closing...
Reason: Pre-rewrite (2.x.x) issue(s)

PS: NBT detection was rewritten as well to be much more accurate. You can also delete tags of the requested item so that it's more lenient when partial NBT detection is enabled
