### ISSUE TITLE
spamming /bq_admin load default causes it the complete and corrupt quest lines 1.10.2

### ISSUE THREAD

**Issue by SDUBZ** [Funwayguy/BetterQuesting#81]
also affects quest when doing /bq_admin edit and most of the time it autocompletes a quest and then when you reset quest status it removes rewards

**Comment by Funwayguy** [comment]
I think I've finally fixed this now as of 2.0.210 and 2.3.211. Turns out it was a side effect of orphaned quests that were supposed to have been deleted. Not sure if this was also related to task and reward data resets, I can't seem to recreate it though.

**Comment by SDUBZ** [comment]
ok i will test later on and see if it still happens
