### ISSUE TITLE
SubmitStation.getStackInSlot

### ISSUE THREAD

**Issue by Sasikaa** [Funwayguy/BetterQuesting#83]
Hy!
Trying the AUTOMATA 2 modpack, and the OSS.
The oss put the EnderIO item conduit, and hopper. Insert the oss COBBLESTONE, and BUM crash!
Here is my crash report!
http://pastebin.com/Tdd6z2xa

And my world is weird... The not loading, because crash, crash, crash...

**Comment by Funwayguy** [comment]
This got fixed a while back but I forgot to close this particular duplicate thread.
