### ISSUE TITLE
MC ModVersion false Version number

### ISSUE THREAD

**Issue by ShadyDemoness** [Funwayguy/BetterQuesting#84]
Dear Funwayguy

I tried to use you beta version with betterquesting NPC integration, RF Expansion, Questbook and Standard Expansion. Now the thing is The MCModversion and a few other things in the newest 1.7.10 beta hava a Version number like this: "CL-Mod Version". This issue is also in the standard expansion pack. So it is obvious that none of the other addons can notice the mod like this. They are saying they need a minimum version of 1.0.23 although this is the newest version. 

Please Fix this issue quickly

**Comment by Funwayguy** [comment]
Um no. These are intentionally unversioned test builds. Expansions built for the 1.x.x BetterQuesting core will not work in this new version (which will be 2.x.x). Properly versioned builds will be released when I deem them stable enough for experimental pack use.

EDIT: Versioned beta builds are now available
