### ISSUE TITLE
Crashes Game When Adding a New Quest

### ISSUE THREAD

**Issue by jelaw21** [Funwayguy/BetterQuesting#86]
I have included the crash report, but sometime when I add a new quest to a set it crashes the game. 

BetterQuesting 1.3.161
Standard Expansion - 1.3.98

[crash-2016-11-19_08.45.32-server.txt](https://github.com/Funwayguy/BetterQuesting/files/601470/crash-2016-11-19_08.45.32-server.txt)

**Comment by Funwayguy** [comment]
Closing...
Reason: Pre-rewrite (2.x.x) issue(s)
