### ISSUE TITLE
[1.10.2] Crash on pumping an unvalid item into the OSS with the eio conduits

### ISSUE THREAD

**Issue by jawsawn** [Funwayguy/BetterQuesting#87]
https://gist.github.com/JAWSAWN/203b0369523b988359009fe1c9c80d81

I seted up a chest to oss system with the eio ender conduit. And put an irrelevant item for the quest. It crashed. And everytime i enter that world it crashes again.

**Comment by jawsawn** [comment]
Also happened with the item buffer from ender io when i set the output side to the oss.

https://gist.github.com/JAWSAWN/7bba1fa62f04994d90e4be8370e36605

Not sure if this one is enderio's end.

**Comment by Funwayguy** [comment]
This was fixed a number of versions ago. Closing issue...
