### ISSUE TITLE
Editing quests in multiplayer

### ISSUE THREAD

**Issue by Rozzers** [Funwayguy/BetterQuesting#89]
In a server players are able to edit quests and make their own quest lines and rewards. Potentially making 
1 dirt = 64 diamonds. I want to avoid that.
They aren't OP and I don't know how to stop them.

Edit: I found out about a command for disabling editing.

**Comment by Funwayguy** [comment]
I'm going to assume you're using a 1.x.x build for this. Yes anyone can access the editors when they have been enabled serverside however, any changes made by the client will ONLY be accepted by the server if they are an operator. If a non-OP attempts to change anything, the edit will be ignored by the server and logged to console with a warning sent to the player.

Side Notes:
- You really shouldn't have edit mode enabled on a server unless you're specifically co-developing a quest line with other users.
- This has been improved in BQ2.x.x beta builds where non-OPs aren't allowed to see the editors either.
