### ISSUE TITLE
Add ability to accept items that are Ore Dictionaried together

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/BetterQuesting#9]
I'm trying to learn your mod and created a retrieval task to get 1x Oak Wood (itemID 17).  I have partialMatch = true and ignoreNBT = true.  I had hoped harvesting a Birch Wood (itemID 17:2) would satisfy the requirement.  Is there an option I am missing?  If not can you add the ability to match to Ore Dictionary items?

**Comment by Funwayguy** [comment]
Ore Dictionary support is already being developed for the next update of Standard Expansion.

**Comment by Drethic** [comment]
I've been trying to test out the OreDict options you added with Better Quest 1.0.15 and Standard Expansion 1.0.10.  However, when I go into the item, under Raw NBT, and fill in the following fields:
```
id -> minecraft:log
Count -> 1
OreDict -> ore:logWood
Damage -> 0
```
I would expect it to look for Oak Wood, but accept anything linked in the dictionary, which in this case is:
```
Ore entries for <ore:logWood> :
    <minecraft:log:*>
    <minecraft:log2:*>
    <Natura:tree>
    <Natura:tree:1>
    <Natura:tree:2>
    <Natura:tree:3>
    <Natura:redwood:1>
    <Natura:Rare Tree>
    <Natura:Rare Tree:1>
    <Natura:Rare Tree:2>
    <Natura:Rare Tree:3>
    <Natura:willow>
    <Natura:Dark Tree>
    <Natura:Dark Tree:1>
    <BiomesOPlenty:logs1:*>
    <BiomesOPlenty:logs2:*>
    <BiomesOPlenty:logs3:*>
    <BiomesOPlenty:logs4:*>
    <Thaumcraft:blockMagicalLog>
    <Thaumcraft:blockMagicalLog:1>
    <harvestcraft:pamMaple>
    <harvestcraft:pamPaperbark>
    <harvestcraft:pamCinnamon>
    <Forestry:logs:*>
    <Forestry:logsFireproof:*>
    <witchery:witchlog:*>
    <arsmagica2:WitchwoodLog>
    <TwilightForest:tile.TFLog:*>
    <TwilightForest:tile.TFMagicLog:*>
    <Thaumcraft:blockMagicalLog:*>
```
But it still only comes us looking for Oak Wood and doesn't accept the Birch Wood I'm holding.  What did I do wrong? :)

**Comment by Funwayguy** [comment]
Seems to work just fine for me using the ore dictionary entry "logWood". Did you have NBT checks on?

**Comment by Drethic** [comment]
After removing ore: both the crafting and retrieval quests started working.  I did have ignoreNBT set to false and partialMatch set to true
