### ISSUE TITLE
crash on load up after updating to betterquesting{2.3.172}

### ISSUE THREAD

**Issue by SDUBZ** [Funwayguy/BetterQuesting#90]
[crash-2016-12-01_09.59.16-client.txt](https://github.com/Funwayguy/BetterQuesting/files/623231/crash-2016-12-01_09.59.16-client.txt)

**Comment by ghost** [comment]
I too am getting the java.lang.NoClassDefFoundError: betterquesting/network/handlers/PktHandler error

**Comment by Funwayguy** [comment]
You cannot use 1.x.x expansions for 2.x.x builds
