### ISSUE TITLE
[READ] 1.x.x Expansions Crash with 2.x.x Builds

### ISSUE THREAD

**Issue by Funwayguy** [Funwayguy/BetterQuesting#93]
BQ1 (1.x.x) expansions are NOT compatible with BQ2 (2.x.x)!

**DO NOT REPORT THIS**

**Comment by xSparky911x** [comment]
The RF expansion changelog says "Updated to support BQ2.0.x builds" but infact it does not. Crashes on loading. Is there going to be an update for RF expansion?

**Comment by Funwayguy** [comment]
Care to provide said crash report? Preferably on the correct Github project

**Comment by xSparky911x** [comment]
https://github.com/Funwayguy/RFExpansion/issues/5
