### ISSUE TITLE
Item Rewards revert to a quantity of 1 in GUI Editor

### ISSUE THREAD

**Issue by Biochao** [Funwayguy/BetterQuesting#95]
When setting a quantity of more than 1 for item rewards, after 'done' is clicked the reward shows a quantity of 1. 
A text editor can edit the default_quests.json to get around this issue until it is fixed.

BetterQuesting version 2.3.178 and Standard Expansion 2.3.110.

**Comment by Lgk2** [comment]
Change the reward quantity and then click somewhere else so that the text field isn't focused.

**Comment by Funwayguy** [comment]
This issue was fixed as of build 2.0.190
