### ISSUE TITLE
Issues playing in Lan world.

### ISSUE THREAD

**Issue by YourPapy** [Funwayguy/BetterQuesting#96]
I am trying to play some packs with a friend and it wont let me invite him to my party. Also, the overlay keeps randomly popping up and getting in the way,  getting real frustrating if you can imagine.

**Comment by YourPapy** [comment]
Quest book opening randomly happens when someone else in the world opens up the BetterQuesting GUI.

**Comment by Funwayguy** [comment]
What versions of BetterQuesting are you using? Also the book expansion is 3rd party and not maintained by me.

**Comment by atlasagain** [comment]
I don't know about the other user but I am having almost the exact same issue, along with the other player being stuck in edit mode. Using BQ version 2.3.179 and Better Questing Triggerer 0.4 in the Forever Stranded modpack on curse.

**Comment by MokahTGS** [comment]
Confirmed.  Tried with BQ 178 and BQTrigger .4

Removing triggerer and updating to v180.  Will update with results.

**Comment by MokahTGS** [comment]
Now getting a crash with BQ 1.3.180 trying to create a new world.  BQ Triggerer has been removed.

http://pastebin.com/vSqZVupS

**Comment by Funwayguy** [comment]
Edit/Hardcore mode syncing was fixed as of 2.0.185 and party issues were fixed as of 2.0.194
