### ISSUE TITLE
[1.10.2] Crash on loading a world with 1.3.180 (possibly caused by removing other mods)

### ISSUE THREAD

**Issue by jawsawn** [Funwayguy/BetterQuesting#97]
https://gist.github.com/JAWSAWN/3e6f031239caf6920935366c29747fb0

I removed mekanism that might had some quests associated with it. It crashed on a world gen.
Any way to not crash the world but also not render the used mods items?

**Comment by jawsawn** [comment]
I re added the mods, but still getting a crash:
Do you know why would it be?
https://gist.github.com/JAWSAWN/f4c300853ac36808e928621b8cee9e4e

**Comment by Funwayguy** [comment]
Well for starters you're using a BQ2.x.x expansion with BQ1.x.x which is incompatible

**Comment by Lgk2** [comment]
"BQ1 (1.x.x) expansions are NOT compatible with BQ2 (2.x.x) releases! Always check your versions before updating" - Notes in Better Questing project. And since it doesn't seem to be a real issue you should close the thread.

**Comment by jawsawn** [comment]
My worlds doesn't load far than the loading world screen. Is it might be caused by this?
better questing 2.3.179
standard expansion 2.3.144

**Comment by MokahTGS** [comment]
The problem is that you released a 1.x.x update as the "latest" 1.10.2 file and the curse launcher will see that as a needed update.  Modpack authors update and crashes galore.

**Comment by Funwayguy** [comment]
I have marked the versions separately as Release and Beta but Curse is still sending them both out as recommended updates... >_>
